### ISSUE TITLE
Generating runner from cached/preprocessed and not main test

### ISSUE THREAD

**Issue by MeKarsten** [ThrowTheSwitch/Ceedling#101]
I am using Ceedling 0.20.4.

When generating runner for a test the test cases are not collected from the preprocessed test file. Instead it is generated from the main test file.
Is this intentional?

It restricts possibilities of having macros expanding test cases. 

I have tried having Ceedling extract test cases from the preprocessed/cached file by replacing the following in generator.rb, generate_test_runner() (line 64), and it seems to work:
**Original**
`test_cases  = @generator_test_runner.find_test_cases( @file_finder.find_test_from_runner_path(runner_filepath) )`
 **Proposed**
`test_cases  = @generator_test_runner.find_test_cases(  @file_finder.find_test_input_for_runner_file(runner_filepath) )`

**Comment by mvandervoord** [comment]
Fixed.
