### ISSUE TITLE
Not pre-processing test files

### ISSUE THREAD

**Issue by 0ge** [ThrowTheSwitch/Ceedling#102]
When running tests the test source files are also preprocessed, which is unnecessary and should thus not be pre-processed.

This has the side effect that there exist no linkage back to the test source and so tools like C/C++ Unit Test in Eclipse can not trace tests to lines in test source.

**Comment by mvandervoord** [comment]
Thanks for posting this! I'll do my best to get this fixed. :)

**Comment by MeKarsten** [comment]
Does this affect [https://github.com/ThrowTheSwitch/Ceedling/issues/101](url) ?

**Comment by mvandervoord** [comment]
Yes, it definitely would effect that. It would make it so issue 101 is not a possible option at all.

**Comment by MeKarsten** [comment]
Would it be possible to keep the preprocessing and have Ceedling use the preprocessed file only for parsing and extracting test cases? Then build and link with the original test source file?

The idea of 101 is to let Ceedling work on a file with content closer to the information used when actually compiling the test.

**Comment by mvandervoord** [comment]
I think I see where you are going with this. Do you have a little code snippet of a test file that might benefit from this behavior?

**Comment by MeKarsten** [comment]
In the following example Ceedling expects test_BlahBlah to exist event though BLAH_BLAH is not defined. This means linking fails since the runner is generated based on other input than given to the compiler.
```
#ifdef BLAH_BLAH
void test_BlahBlah(void)
{
  TEST_ASSERT_EQUAL(3, 3);
}
#endif
```
Another example could be macros expanding test cases. (For this subject there may exist better solutions?)
```
CONDITIONAL_TEST_MY_API_VARIANTX_AVAILABLE(MyTest,
    TEST_ASSERT_EQUAL_INT16(0x1234U, MyApi_1234());
    TEST_ASSERT_NOT_EQUAL(0x4321U, MyApi_1234());
)
```
Where the macro can be defined in another file such as
```
#ifdef MY_API_VARIANTX_AVAILABLE
/*lint --e{9026} --e{9024} --e{970} --e{9075} --e{9045} --e{9029} --e{737} */
#define CONDITIONAL_TEST_MY_API_VARIANTX_AVAILABLE(NAME, CONTENT) \
  void test_##NAME(void) { CONTENT }
#else
#define CONDITIONAL_TEST_MY_API_VARIANTX_AVAILABLE(NAME, CONTENT) \
  void test_##NAME(void) { TEST_IGNORE_MESSAGE("Test ignored due to MyApi not available"); }
#endif
```
Note that things like PC-Lint options and ignore/fail messages can be defined consistently across tests making it easier to parse output from tests with external tools. An example could be parsing all ignore messages by an external tool which will fail if any ignore messages are not expected for a build setup.

**Comment by Letme** [comment]
I also got into this issue as I have updated Ceedling to 0.24.0 (actually on current master (873a6d2b5b7048b09d99f78edbc7cd8a49906c85)). This was working in 73ed8b7 (if that helps). Any timeline when this would be fixed?

**Comment by Letme** [comment]
Heya,
I did some bisecting and found out following:
de8524d6521d2a94bdd23c448d9a3513413bfe0a is the first bad commit
commit de8524d6521d2a94bdd23c448d9a3513413bfe0a
Author: Hiroaki Yamazoe <PastelParasol@gmail.com>
Date:   Mon Sep 19 18:31:52 2016 +0900

    use UnityTestRunnerGenerator to find test cases

:040000 040000 cd02d88f4e3e7535dd1e8e2fd79003c3d39d9f74 29735b10d07da8deabfe62d5cb3430944a15025d M	lib

Hope this helps.

**Comment by mvandervoord** [comment]
Are any of you fine people in a position to be able to pull in the latest Ceedling straight off git? I think I have solved it but would like to check before pushing it out as a new release.

**Comment by Letme** [comment]
I have pulled the master and preprocessing works. Thanks for the fix.

**Comment by mvandervoord** [comment]
Thank YOU for all your help!
