### ISSUE TITLE
tearDown not called on after TEST_IGNORE() and TEST_FAIL()

### ISSUE THREAD

**Issue by dpostorivo** [ThrowTheSwitch/Ceedling#103]
I'm pretty sure the issue is inside Unity rather then Ceedling itself, but since it affects and can cause Ceedling to blow up I'm posting it here. 

I've noticed that when the  TEST_IGNORE() and TEST_FAIL()  and there variants are called, the tearDown function is never called. This is improper for a few reasons with the most curtail being if any memory is allocated in setUp and freed in tearDown will not be freed to issues testing. The tearDown should always be called after the setUp to allow the user to guarantee their modules are setup and cleaned up properly. 

Here's a basic test file to show this behavior:

```
#include "unity.h"
#include  <stdio.h>

void setUp(void)
{
    printf("Setup\n");
}

void tearDown(void)
{
    printf("TearDown\n");
}

void test_passes(void)
{
    printf("Passed\n");
}


void test_ignored(void)
{
    printf("Ignored\n");
    TEST_IGNORE();
}

void test_fails(void)
{
    printf("Failed\n");
    TEST_FAIL();
}
```

And this is the result.

```
Test 'test_example.c'
---------------------
Generating runner for test_example.c...
Compiling test_example_runner.c...
Compiling test_example.c...
Linking test_example.out...
Running test_example.out...

-----------
TEST OUTPUT
-----------
[test_example.c]
  - "Setup"
  - "Passed"
  - "TearDown"
  - "Setup"
  - "Ignored"
  - "Setup"
  - "Failed"
  - ""
  - ""

--------------------
IGNORED TEST SUMMARY
--------------------
[test_example.c]
  Test: test_ignored
  At line (24)

-------------------
FAILED TEST SUMMARY
-------------------
[test_example.c]
  Test: test_fails
  At line (30)

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  3
PASSED:  1
FAILED:  1
IGNORED: 1

---------------------
BUILD FAILURE SUMMARY
---------------------
Unit test failures.
```

**Comment by mvandervoord** [comment]
As you mention, this is an issue with Unity, not Ceedling. It's also the better of the two bad behaviors possible. We're currently exploring how to best fix it. See the thread on the Unity Issues Forum.

https://github.com/ThrowTheSwitch/Unity/issues/114
