### ISSUE TITLE
Multiple plugin load paths does not work

### ISSUE THREAD

**Issue by MeKarsten** [ThrowTheSwitch/Ceedling#105]
I am using Ceedling 0.20.4.

When having multiple load paths for plugins the following error is reported:
```
NameError: undefined local variable or method `old_script_plugin_path' for #<ConfiguratorPlugins:0x2c82030>
```
A suggestion is to replace line 59 in configurator_plugins.rb since `old_script_plugin_path` no longer exists.
**Original**
```
if @file_wrapper.exist?(script_plugin_path) or @file_wrapper.exist?(old_script_plugin_path)
```
**Proposed**
```
if @file_wrapper.exist?(script_plugin_path)
```

**Comment by mvandervoord** [comment]
Thanks so much for the solution!
