### ISSUE TITLE
module_generator plugin defaults are inconsistent with new project defaults

### ISSUE THREAD

**Issue by gmbodnar** [ThrowTheSwitch/Ceedling#109]
It appears that the module_generator plugin passes no arguments to the UnityModuleGenerator class, resulting in the default options being used for creation of subsequent files. The default generator prefix used for files in the test directory is `Test`, but the default project.yml file created with a new ceedling project specifies a prefix of `test_`. The end result is that any new test module will not be found when using defaults.

If it's possible to grab `:project:test_file_prefix:` from project.yml and pass that as an option to the module creation, the inconsistency could be avoided. This is my first look at ceedling and first look at ruby code at all, so I may be missing some details. Apologies, if that's the case.

**Comment by mvandervoord** [comment]
Funny. I am fixing this one as you write!  :)

**Comment by gmbodnar** [comment]
Best. Service. Ever.
It keeps me from having to dig into ruby while I'm supposed to be driving embedded peripherals.

**Comment by mvandervoord** [comment]
If you need it soon, you can grab commit fe5c646 of Ceedling and 4e2f038 of Unity. These should fix the issues. Otherwise, we're planning to roll out a few bugfixes into a new Ceedling gem release early next week.

**Comment by mvandervoord** [comment]
Fixed with gem 0.25.0
