### ISSUE TITLE
How can I manually specify source files that Ceedling fails to pick up?

### ISSUE THREAD

**Issue by TAGC** [ThrowTheSwitch/Ceedling#113]
According to the Ceedling documentation:

> Ceedling knows what files to compile and link into each individual test executable by way of the #include list contained in each test file. Any C source files in the configured search directories that correspond to the header files included in a test file will be compiled and linked into the resulting test fixture executable. 

This is great, but what happens if I need to add source files that don't have the same name as header files? For example, I'm trying to write some unit tests that involve embOS and I've added `#include "RTOS.h"` at the top of my unit test file. However, there is no "RTOS.c" file; instead I need to compile and link "RTOSInit.c" and "os7m_tl__dp.a".

If I only include "RTOS.h" in the test file, no embOS source files get linked, because Ceedling will only try looking for "RTOS.c". I've tried doing something very hacky of creating an empty "RTOSInit.h" file which I include as well to get it to link "RTOSInit.c", but that still leaves an issue with "os7m_tl__dp.a".

Manually specifying additional source files to include in the compilation/linking process for creating test executables seems like a very basic and fundamental requirement, but I can't see a way to do this after reading the documentation.

**Comment by mvandervoord** [comment]
As of 6cec067 you can now specify TEST_FILE("filename.c") in your test files to tell Ceedling that you have additional files that should get pulled in. This will require you to update to the latest Unity as well.

**Comment by thomasfinchbr** [comment]
Hi

How would I include files with another extension like, portasm.s?
TEST_FILE("portasm.s") is not working.

Thanks
