### ISSUE TITLE
utils:gcov fails: [errno2] no such file or directory

### ISSUE THREAD

**Issue by wolf99** [ThrowTheSwitch/Ceedling#114]
My setup worked fine until recently. I have not changed my Ceedling setup for the project in question since the last time it worked and that was setup using Ceedling pulled at v0.22.0 (or maybe 178983d4, which is the commit following v.0.22.0) , though gcc, gcov (both v6.2) or gcovr (v3.3) may have had patch updates during a `$sudo apt-get upgrade` (still same major and minor version though). I am using Ruby with rbenv set for Ruby at version 2.3.1.

Running `$rake clobber && rake gcov:all` works as normal, but `$rake utils:gcov` fails with:

~~~sh
$ rake utils:gcov
(in /mnt/c/Users/user-name/git/repo-name)
Creating html report of gcov results...
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 2323, in <module>
    print_html_report(covdata, options.html_details)
  File "/usr/local/bin/gcovr", line 1650, in print_html_report
    OUTPUT = open(options.output, 'w')
IOError: [Errno 2] No such file or directory: '/mnt/c/Users/user-name/git/repo-name/build/artifacts/gcov/GcovCoverageResults.html'
ERROR: Shell command failed.
> Shell executed command:
'gcovr -p -b -e '^vendor.*|^build.*|^test.*|^lib.*' --html -r . -o GcovCoverageResults.html -o build/artifacts/gcov/GcovCoverageResults.html'
> And exited with status: [1].

rake aborted!
ShellExecutionException: ShellExecutionException
/mnt/c/Users/user-name/git/repo-name/vendor/ceedling/lib/ceedling/tool_executor.rb:78:in `exec'
vendor/ceedling/plugins/gcov/gcov.rake:160:in `block (2 levels) in <top (required)>'
Tasks: TOP => utils:gcov
(See full trace by running task with --trace)
~~~
I tried running with `sudo` but root user doesn't have Ruby setup , d'oh!
How can I fix this?

**Comment by dpostorivo** [comment]
This is definitely an issue with gcovr rather than ceedling. The only thing the `utils:gcov` command does as of now is use call the gcovr command and uses the output files of `gcov:all`. 

This line specifically is the issue:
```
> Shell executed command:
'gcovr -p -b -e '^vendor.*|^build.*|^test.*|^lib.*' --html -r . -o GcovCoverageResults.html -o build/artifacts/gcov/GcovCoverageResults.html'
```
The option in that causes the issue specifically is the option `-o build/artifacts/gcov/GcovCoverageResults.html` as it seems  gcov will not write if it can't find the needed directories. This option is currently also not in the the plugin at the moment. I'm currently working on actually making this file appear there along with other improvements, so this is good info for me to account for. 

On my machine I was able to recreate and fix it the following way:

```
dom@dev:~/dev/test_project$ gcovr -p -b -e '^vendor.*|^build.*|^test.*|^lib.*' --html -r . -o GcovCoverageResults.html -o build/artifacts/gcov/GcovCoverageResults.html
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 1970, in <module>
    print_html_report(covdata, options.html_details)
  File "/usr/bin/gcovr", line 1427, in print_html_report
    OUTPUT = open(options.output, 'w')
IOError: [Errno 2] No such file or directory: 'build/artifacts/gcov/GcovCoverageResults.html'
dom@dev:~/dev/test_project$ mkdir build/artifacts/gcov
dom@dev:~/dev/test_project$ gcovr -p -b -e '^vendor.*|^build.*|^test.*|^lib.*' --html -r . -o GcovCoverageResults.html -o build/artifacts/gcov/GcovCoverageResults.html
dom@dev:~/dev/test_project$ ls build/
artifacts/ gcov/      .keepme    logs/      temp/      test/      
dom@dev:~/dev/test_project$ ls build/artifacts/gcov/
GcovCoverageResults.html

```

Hope this helps.

**Comment by wolf99** [comment]
This morning I have figured out for the issue I have had by using the shell command:

~~~sh
gcovr -p -b -e '^vendor.*|^build.*|^test.*|^lib.*' --html -r . -o GcovCoverageResults.html -o build/artifacts/gcov/GcovCoverageResults.html
~~~

That the reason is that I have my build directory renamed to non-standard `test-build`. I though I had accounted for this by changing the `build_root` value in `project.yml`, but either the gcov rake task does not take `build_root` into account or I need to set it somewhere else too.

Using the above line with the `/build/` part of the path adjusted works OK without any prior `mkdir` even after a clobber.

**Comment by wolf99** [comment]
Ah, I see that the `-o` argument is hard-coded separately in the `:tools_gcov_post_report: :arguments:` section... that would probably explain that! LOL

**Comment by mvandervoord** [comment]
Is this resolved at this point? I'm not sure how you guys left this.

**Comment by dpostorivo** [comment]
@mvandervoord  It's resolved. The issue itself is in the limits of gcovr.

**Comment by lafumei** [comment]
Just revisited this thread as found that I'm having the same issue originally reported. I'm running on Win10 and swapping the ticks for quotes hasn't solved it. Also if I run the failing command manually it works fine.

Failing cmd:
`λ ceedling.bat utils:gcov
Creating a detailed html report of gcov results in build/artifacts/gcov/GcovCoverageResults.html...
rake aborted!
Errno::ENOENT: No such file or directory - gcovr.py -p -b -e "^vendor.*|^build.*|^test.*|^lib.*" --html --html-details -r . -o  "build/artifacts/gcov/GcovCoverageResults.html"
c:/dev/Researching/vendor/ceedling/lib/ceedling/system_wrapper.rb:45:in ``'
c:/dev/Researching/vendor/ceedling/lib/ceedling/system_wrapper.rb:45:in `shell_backticks'
c:/dev/Researching/vendor/ceedling/lib/ceedling/tool_executor.rb:68:in `exec'
c:/dev/Researching/vendor/ceedling/plugins/gcov/gcov.rake:168:in `block (2 levels) in <top (required)>'
C:/Ruby21/bin/ceedling:23:in `load'
C:/Ruby21/bin/ceedling:23:in `<main>'
Tasks: TOP => utils:gcov
(See full trace by running task with --trace)
ERROR: Ceedling Failed`

However, running this below is absolutely fine:
`gcovr.py -p -b -e "^vendor.*|^build.*|^test.*|^lib.*" --html --html-details -r . -o  "build/artifacts/gcov/GcovCoverageResults.html"`


Has anybody got any views on this?
