### ISSUE TITLE
How to use GDB with Ceedling ?

### ISSUE THREAD

**Issue by srak2016** [ThrowTheSwitch/Ceedling#115]
Kindly add some notes on how to debug the C source code when use Ceedling. 
One option I tried is to use gdb,
>gdb --args ruby -S rake test:sample
It did not work, then I tried,
>gdb build\test\out\test_sample.out
This worked!

Is this the way to use? Any better way to do it?

**Comment by mvandervoord** [comment]
Yes, you've got it right. gdb can't debug the ruby scripts themselves... so you have to connect to the produced executable directly. Also, since Ceeding can sit on any set of command line tools, gdb will often not be relevant to the end user.
