### ISSUE TITLE
As of 0.25.0, Ceedling returns success even if tests fail

### ISSUE THREAD

**Issue by dpostorivo** [ThrowTheSwitch/Ceedling#117]
I've recently upgraded the Ceedling I have on my Jenkins CI to 0.25.0 and about a day later I noticed that jenkins had been approving of several commits even though there were failing tests. A sample output

```
--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  71
PASSED:  68
FAILED:   3
IGNORED:  0

---------------------
BUILD FAILURE SUMMARY
---------------------
Unit test failures.

Finished: SUCCESS
```

Running `ceedling test:all` locally and then checking `echo $?` produced the same output above and showed a return status of `0` which in previous version would return 1. After reverting to version 0.24.0, ceedling returns error for a failing tests and allows my Jenkins CI to fail like it's suppose to.

```
--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  71
PASSED:  68
FAILED:   3
IGNORED:  0

---------------------
BUILD FAILURE SUMMARY
---------------------
Unit test failures.

Build step 'Invoke Rake' marked build as failure
Finished: FAILURE
```

**Comment by mvandervoord** [comment]
Yes, that has definitely changed. There are a number of people who (rightfully) pointed out that returning an error code was a little strange when there were no errors. The test code ran fine, it just returned failures.

I understanding your use-case as well, though. It's the way I have traditionally like things to work.

What do you think about having a project flag which specifies if it should error out on a failure?

**Comment by Letme** [comment]
I am in favor of a flag for this. It also annoys me when running localy and you have to search which file actually caused the error because gcov and stuff like that ran afterwards (since it returned success).

**Comment by mvandervoord** [comment]
@Letme you are proposing that it fail out immediately then?

**Comment by Letme** [comment]
I run some postprocessing after ceedling, and if ceedling returns 0 then postprocessing runs. That means a huge output from postprocessing blocks the summary (which if it is all success it does not matter for me). If there is a failure then I would not like to run commands from then on (return non 0).  

While developing thou I would love to have tests stop as soon as one file has failed tests (not as soon as 1 test fails). That makes it a lot less time to wait when you have few 100 tests. I do not know what is possible, but flag for this case would be nice to have, while first paragraph for me is a normal usage (but I also agree that we can live with flag since it seems like opinions differ).

**Comment by mvandervoord** [comment]
Your idea of stopping after each failing file is certainly possible too. I agree it would be another option. For that feature, it could even be a command line option... like instead of running test:all you run test:until_fail or something like that.

**Comment by Letme** [comment]
Command line option in my case would be more suitable - since we do not really want this in CI.  Project configuration should have a overall option to return a proper value (or always return 0)

**Comment by mvandervoord** [comment]
Cool. I think we have a plan. If anyone else has thoughts on this, speak up. I'll try to tackle this soon.

**Comment by dpostorivo** [comment]
I'd like a flag if possible, but I'm not sure why this was an issue in the first place. Every testing and linting tool I know returns a failure if something fails. I'd also like to point out the Travis CI for this project is also designed on that being true and if a test fails in this repo, rspec will return fail. If rspec always returned success just for building, then Travis CI would never trigger if tests were failing.

I do agree it would be nice to differentiate between the build/running of the tests failing and tests failing, but that can be done with different return statuses.

**Comment by meyercm** [comment]
Encountered this issue today as a new adopter.  Concur with @dpostorivo; I'm not aware of any unit testing framework that returns 0 in cases where the build is broken- that's how you know the build is broken.

**Comment by dpostorivo** [comment]
Just leaving a note here, `rake test:all` was fixed in #130, however ceedling will still return 0 at all times as shown in #148 .

**Comment by MichaelBMiner** [comment]
It appears as though a flag was added to the output of ceedling? How does one access this from the jenkinsfile?

**Comment by Letme** [comment]
This seems more like your `.sh` script does not propagate the error back.

**Comment by MichaelBMiner** [comment]
> This seems more like your `.sh` script does not propagate the error back.

Interesting. I will explore that! Thank you
