### ISSUE TITLE
How to build multiple release artifacts?

### ISSUE THREAD

**Issue by sorber** [ThrowTheSwitch/Ceedling#127]
I'm new to ceedling and trying to figure out how to build multiple release artifacts from a single project. I could, of course, make a separate project for each release, but they share a lot of code (most modules are shared between builds—often main() is the only place they're different). I don't want to duplicate the shared code (or play file system games). 

I would like to set up my project like this.

- build
- src
    - apps
        - app1main.c
        - app2main.c
        - app3main.c
   - modules
       - everything else
- test

I would like to make one "release" task that goes through the files in apps and compiles each with everything in "modules". So, I would end up with two different release binaries.
 
First, I'm wondering if Ceedling supports this (it doesn't look like it from the docs, but you never know). 

Second, do you have any advice on extending Ceedling? I would like to use as much of Ceedling's existing functionality as I can (I would rather redirect existing mechanisms than reimplement them). 

Thanks.

**Comment by mvandervoord** [comment]
The cleanest way that I can think of is to do the following: set up a project yaml file that does most of what you want and call it project.yml, as is the usual. Then, for the additional releases, add a project yaml file that overrides just the parts that you want to override and name them something logical (like app1.yml, app2.yml, etc in your example).

Now, you can can call the one you want like so:

ceedling project:app1 clobber release

That will pull in the main project file, and then the app1.yml file over the top of it, replacing just the important details.

It might be a little tricky to get just right, but this is actually functionality I use, so I know it at least works in some circumstances. ;)
