### ISSUE TITLE
Globs of the form ab*cd/** do not include ab*cd

### ISSUE THREAD

**Issue by hmijail** [ThrowTheSwitch/Ceedling#135]
A glob of the form `abcd/**` includes
1. the directory `abcd`, 
2. plus all of its subdirectories.

One would expect that a glob of the form `ab*cd/**` would include
1. every directory conforming to `ab*cd`,
2. plus all of their subdirectories.

But in fact this second kind of glob includes only (2), not (1).

Looks like this is a Ruby globbing issue, and the behavior can be selected with flags: https://shane.io/2014/07/13/sobbing-with-ruby-file-globbing.html

**Comment by mvandervoord** [comment]
Fixed in 5d2b3a5
