### ISSUE TITLE
Compile error when add link library by flags attribute 

### ISSUE THREAD

**Issue by kevintruong** [ThrowTheSwitch/Ceedling#136]
I has problems when working with ceedling like below. 
For example I has test case call : test_screen . The implementation dependence X11 library. I takes a look and configures the flags attribute like bellow. 
For example 
```
:flags:
  :test:
    :compile:
      :test_screen:
        - -Wall
    :link:
      :test_screen:
        - -lX11
```

but the GCC return some kinds of linking error like could not found reference of some functions which I am using in my implementation. 
The error build command 
`'gcc -lX11 "build/test/out/test_screen_runner.o" "build/test/out/test_screen.o" "build/test/out/unity.o" "build/test/out/Screen_Unix.o" "build/test/out/cmock.o" -o "build/test/out/test_screen.out"'`
Trying to fix it. Then I found out the issue because of the incorrect order of linking. 
the correct order must be 
`"gcc  "build/test/out/test_screen_runner.o" "build/test/out/test_screen.o" "build/test/out/unity.o" "build/test/out/Screen_Unix.o" "build/test/out/cmock.o" -o "build/test/out/test_screen.out -lX11"`
But the command was generated by Ceendling. And then I stuck on there. 
Really appreciate any suggestions or helps.
Thanks and best regards,

**Comment by kevintruong** [comment]
Sorry, but I would to know that the project still in maintain and some one will look at the issue. It's really a critical issue as my view. 
Any suggestion to work around it ? 
thanks

**Comment by Letme** [comment]
Work around is in referenced issue - update GCC. Otherwise someone will need to dive in and implement suffix (which is going to be useless once people will be using newer GCCs)

**Comment by mvandervoord** [comment]
There is a patch for this in the works, but it's not quite ready yet. Sorry about the delay.

**Comment by kevintruong** [comment]
@mvandervoord 
really thank you for your quick respond. 
Can't wait to try the path. I also done by update GCC. But still really want to find another ways like your path

**Comment by mvandervoord** [comment]
Fixed by adding support for a :libraries: section where you can specify :libraries:system: and then include the system libraries you want to include. This is injected into the end by default (though it can be set to any location by using option ${4}. See the manual for details). commit 336be34
