### ISSUE TITLE
compile fall when change source structure 

### ISSUE THREAD

**Issue by kevintruong** [ThrowTheSwitch/Ceedling#137]
Hi all
Another problem with ceedling. I really want to separate my source code *.c in /src and header files *.h in /inc  likes bellow: 
```
├── inc
│   ├── module_A
│   │   └── module_a1.h
│   ├── module_b.h
│   ├── vfAppCache.h
│   ├── vfMemory.h
│   └── vfRingbuffer.h
├── project.yml
├── rakefile.rb
├── src
│   ├── module_A
│   │   └── module_a1.c
│   ├── module_b.c
│   ├── vfAppCache.c
│   ├── vfMemory.c
│   └── vfRingBuffer.c
├── test
│   ├── module_A
│   │   └── test_module_a1.c
│   ├── support
│   ├── test_module_b.c
│   └── test_vfAppCache.c
├── vendor
```

And configure the the path field ceedling project file as 

```
:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include: 
    - inc/**
    - vfInclude/**
  :support:
    - test/support
```
module_b will call some function from module_a1. The test case works fine. 
In another test case **test_vfAppCache** with the same theory. vfAppCache will call some function in vfRingBuffer 
But when I tried to run the test case. The compile noticed a compile error likes bellow: 
```
Test 'test_vfAppCache.c'
------------------------
ERROR: Found no file 'vfRingbuffer.c' in search paths. However, a filename having different capitalization was found: 'src/vfRingBuffer.c'.
rake aborted!
```

**Comment by Letme** [comment]
And why is this a ceedling problem? It actually gave you a very descriptive error.

Rename your .h file with proper capitalization or check what is capitalization with `#include`

**Comment by mvandervoord** [comment]
Yeah, I must agree with Letme in this case. This is one of the cases where Ceedling actually provides a nice descriptive error (our goal, but one which often falls short). C is a case sensitive language (even if Windows isn't). It's noticed you have an error and is kindly pointing it out for you.
