### ISSUE TITLE
Add support for running only a subset of tests in a test file

### ISSUE THREAD

**Issue by sw17ch** [ThrowTheSwitch/Ceedling#15]
Might require some work with ThrowTheSwitch/Unity as well.

We should add some support for disabling tests (such as 'xit' from rspec) or selecting only a specific subset to run (like rspec's ability to run tests found on a specific line).

Suggested syntax for command line:

``` sh
rake test:test_foo.c[80] # run the test on line 80
rake test:test_foo.c[80,200] # run test found from line 80 to line 200

rake test:test_foo.c[*somePattern*] # run all tests with names matching pattern
```

Suggested syntax for tests:

``` c
// Don't run tests that have a 'disable_' or 'x_' prefix in the name.
// Examples:
//   void disable_[prefix]_testName(void);
//   void x_[prefix]_testName(void);

// This test would run
void test_someName(void)
{
   // ...
}

// This test would not run
void x_test_someOtherName(void)
{
  // ...
}

// Neither would this one
void disable_test_someOtherName(void)
{
  // ...
}
```

**Comment by bdun** [comment]
This feature would be very helpful.  Any update on this?

**Comment by mkarlesky** [comment]
Doing some _**much**_ overdue housekeeping… Closing this issue out as Ceedling and Unity have long supported basic test case filtering with `--test-case` and `--exclude-test-case` command line flags. Ceedling 1.0.0 does all the configuration work necessary so that these options just work.
