### ISSUE TITLE
Ceedling Gem 0.27.0 use_test_preprocessor: TRUE injects '@' Symbols in include statements.

### ISSUE THREAD

**Issue by OUNAVCON** [ThrowTheSwitch/Ceedling#159]
Anytime I try to run "rake test:all" using Ceedling gem 0.27.0 I get the following failure.

../test/build/temp/_test_main.c:2:23: fatal error: @@@@unity.h: No such file or directory
compilation terminated.

Ceedling is generating the _test_main.c file and injecting the @@@@in the include filename.
Reverting to 0.25.0 or setting :use_test_preprocessor: FALSE and the issue goes away.

Here is a dump of the console log.

S C:\Users\isaac.rose\workspace\CeedlingTest\test> rake test > error.log
../test/build/temp/_test_main.c:2:23: fatal error: @@@@unity.h: No such file or directory
compilation terminated.
ERROR: Shell command failed.
> Shell executed command:
'gcc.exe -I"test" -I"test/support" -I"test/support" -I".." -I"../Debug" -I"../Debug/src" -I"../Debug/test" -I"../Debug/test/test" -I"../Debug/test/vendor" -I"../Debug/test/vendor/ceedling" -I"../Debug/test/vendor/c
eedling/plugins" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework/examples" -I"../Debug/test/vendor/ceedling/plugins/fake_function_f
ramework/examples/fff_example" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/su
bfolder" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/test" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework/vendor" -I"../Debug/test/vendor/ceedling/plugins
/fake_function_framework/vendor/fff" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework/vendor/fff/examples" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework/vendor/fff/examples/embedd
ed_ui" -I"../Debug/test/vendor/ceedling/plugins/fake_function_framework/vendor/fff/test" -I"../Debug/test/vendor/ceedling/vendor" -I"../Debug/test/vendor/ceedling/vendor/unity" -I"../Debug/test/vendor/ceedling/vend
or/unity/src" -I"../src" -I"../test" -I"../test/build" -I"../test/build/artifacts" -I"../test/build/artifacts/test" -I"../test/build/logs" -I"../test/build/temp" -I"../test/build/test" -I"../test/build/test/cache"
-I"../test/build/test/dependencies" -I"../test/build/test/mocks" -I"../test/build/test/out" -I"../test/build/test/preprocess" -I"../test/build/test/preprocess/files" -I"../test/build/test/preprocess/includes" -I"..
/test/build/test/results" -I"../test/build/test/runners" -I"../test/src" -I"../test/test" -I"../test/test/support" -I"../test/vendor" -I"../test/vendor/ceedling" -I"../test/vendor/ceedling/docs" -I"../test/vendor/c
eedling/lib" -I"../test/vendor/ceedling/lib/ceedling" -I"../test/vendor/ceedling/plugins" -I"../test/vendor/ceedling/plugins/bullseye" -I"../test/vendor/ceedling/plugins/bullseye/assets" -I"../test/vendor/ceedling/
plugins/bullseye/config" -I"../test/vendor/ceedling/plugins/bullseye/lib" -I"../test/vendor/ceedling/plugins/command_hooks" -I"../test/vendor/ceedling/plugins/command_hooks/lib" -I"../test/vendor/ceedling/plugins/f
ake_function_framework" -I"../test/vendor/ceedling/plugins/fake_function_framework/examples" -I"../test/vendor/ceedling/plugins/fake_function_framework/examples/fff_example" -I"../test/vendor/ceedling/plugins/fake_
function_framework/examples/fff_example/src" -I"../test/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/subfolder" -I"../test/vendor/ceedling/plugins/fake_function_framework/examples/fff_ex
ample/test" -I"../test/vendor/ceedling/plugins/fake_function_framework/lib" -I"../test/vendor/ceedling/plugins/fake_function_framework/spec" -I"../test/vendor/ceedling/plugins/fake_function_framework/src" -I"../tes
t/vendor/ceedling/plugins/fake_function_framework/vendor" -I"../test/vendor/ceedling/plugins/fake_function_framework/vendor/fff" -I"../test/vendor/ceedling/plugins/fake_function_framework/vendor/fff/examples" -I"..
/test/vendor/ceedling/plugins/fake_function_framework/vendor/fff/examples/driver_testing" -I"../test/vendor/ceedling/plugins/fake_function_framework/vendor/fff/examples/embedded_ui" -I"../test/vendor/ceedling/plugi
ns/fake_function_framework/vendor/fff/gtest" -I"../test/vendor/ceedling/plugins/fake_function_framework/vendor/fff/test" -I"../test/vendor/ceedling/plugins/gcov" -I"../test/vendor/ceedling/plugins/gcov/assets" -I".
./test/vendor/ceedling/plugins/gcov/config" -I"../test/vendor/ceedling/plugins/gcov/lib" -I"../test/vendor/ceedling/plugins/junit_tests_report" -I"../test/vendor/ceedling/plugins/junit_tests_report/lib" -I"../test/
vendor/ceedling/plugins/module_generator" -I"../test/vendor/ceedling/plugins/module_generator/config" -I"../test/vendor/ceedling/plugins/module_generator/lib" -I"../test/vendor/ceedling/plugins/stdout_gtestlike_tes
ts_report" -I"../test/vendor/ceedling/plugins/stdout_gtestlike_tests_report/assets" -I"../test/vendor/ceedling/plugins/stdout_gtestlike_tests_report/config" -I"../test/vendor/ceedling/plugins/stdout_gtestlike_tests
_report/lib" -I"../test/vendor/ceedling/plugins/stdout_ide_tests_report" -I"../test/vendor/ceedling/plugins/stdout_ide_tests_report/config" -I"../test/vendor/ceedling/plugins/stdout_ide_tests_report/lib" -I"../test
/vendor/ceedling/plugins/stdout_pretty_tests_report" -I"../test/vendor/ceedling/plugins/stdout_pretty_tests_report/assets" -I"../test/vendor/ceedling/plugins/stdout_pretty_tests_report/config" -I"../test/vendor/cee
dling/plugins/stdout_pretty_tests_report/lib" -I"../test/vendor/ceedling/plugins/subprojects" -I"../test/vendor/ceedling/plugins/subprojects/config" -I"../test/vendor/ceedling/plugins/subprojects/lib" -I"../test/ve
ndor/ceedling/plugins/teamcity_tests_report" -I"../test/vendor/ceedling/plugins/teamcity_tests_report/config" -I"../test/vendor/ceedling/plugins/teamcity_tests_report/lib" -I"../test/vendor/ceedling/plugins/warning
s_report" -I"../test/vendor/ceedling/plugins/warnings_report/lib" -I"../test/vendor/ceedling/plugins/xml_tests_report" -I"../test/vendor/ceedling/plugins/xml_tests_report/lib" -I"../test/vendor/ceedling/vendor" -I"
../test/vendor/ceedling/vendor/cmock" -I"../test/vendor/ceedling/vendor/cmock/config" -I"../test/vendor/ceedling/vendor/cmock/lib" -I"../test/vendor/ceedling/vendor/cmock/release" -I"../test/vendor/ceedling/vendor/
cmock/src" -I"../test/vendor/ceedling/vendor/constructor" -I"../test/vendor/ceedling/vendor/constructor/lib" -I"../test/vendor/ceedling/vendor/c_exception" -I"../test/vendor/ceedling/vendor/c_exception/lib" -I"../t
est/vendor/ceedling/vendor/c_exception/release" -I"../test/vendor/ceedling/vendor/deep_merge" -I"../test/vendor/ceedling/vendor/deep_merge/lib" -I"../test/vendor/ceedling/vendor/diy" -I"../test/vendor/ceedling/vend
or/diy/lib" -I"../test/vendor/ceedling/vendor/diy/lib/diy" -I"../test/vendor/ceedling/vendor/unity" -I"../test/vendor/ceedling/vendor/unity/auto" -I"../test/vendor/ceedling/vendor/unity/release" -I"../test/vendor/c
eedling/vendor/unity/src" -I"C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/vendor/unity/src" -I"C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/vendor/cmock/src" -I"build/test/mock
s" -DTEST -DGNU_COMPILER -g -c "../test/build/temp/_test_main.c" -o "build/test/out/_test_main.o"'
> And exited with status: [1].

rake aborted!
ShellExecutionException: ShellExecutionException
C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/lib/ceedling/tool_executor.rb:78:in `exec'
C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/lib/ceedling/generator.rb:95:in `generate_object_file'
C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/lib/ceedling/rules_tests.rake:17:in `block in <top (required)>'
C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/lib/ceedling/test_invoker.rb:104:in `block in setup_and_invoke'
C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
C:/Users/isaac.rose/workspace/CeedlingTest/test/vendor/ceedling/lib/ceedling/tasks_tests.rake:4:in `block in <top (required)>'
Tasks: TOP => build/test/results/test_main.pass => build/test/out/test_main.out => build/test/out/_test_main.o
(See full trace by running task with --trace)

**Comment by dpostorivo** [comment]
Do you mind posting your project.yml and telling us what version of ruby you are using? I can't reproduced the issue locally on any of my repos. 

If you want to put in a little extra work, you can also try and create a bare minimum example on github and run it through travis to help pinpoint the issue as seen [here](https://travis-ci.org/dpostorivo/ceedling_building_underscore_error) and [here](https://travis-ci.org/dpostorivo/ceedling_fprintf_stderr_error).

**Comment by OUNAVCON** [comment]
In the attached zip file you will find:
/src/ - source...
/test.25/ - project created using "ceedling new test.25" command with only ceedling 0.25.0 installed.. Run "rake test:all" and it builds correctly.
/test.27/ - project created using "ceedling new test.27" command with only ceedling 0.27.0 installed. Run rake test:all" and it fails for the above issue.
[CeedlingTest.zip](https://github.com/ThrowTheSwitch/Ceedling/files/987007/CeedlingTest.zip)

**Comment by OUNAVCON** [comment]
@dpostorivo , I will see about setting it up for GitHub and running it through Travis.

**Comment by OUNAVCON** [comment]
ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu] (Ceedling 0.25.0)
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32] (Ceedling 0.27.0)
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux-gnu] (Ceedling 0.27.0)

**Comment by dpostorivo** [comment]
There's a few things going on.

The first is an issue that I've seen before with this release as shown in #147 where it includes files with an underscore in build time compiling so the temp file called ``_test_main.c` which is an intimidate file to `test_main.c` is compiled. It should not be compiled.

The second is why you were seeing the issue and I wasn't which is the build path is in your source path so ceedling tries to compile every file in your build directory that matches the file pattern which due to the issue above includes the temp file. This can cause a number of issues, this being just an edge case that was introduced by another bug. I was able to get ceedling to work for you zip by changing this line in your project.yml:


`
:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - ../**
  :support:
    - test/support
`

to this:

`
:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - ../src
  :support:
    - test/support
`

If anything else arises or this doesn't fix it let me know. I'm going to look more in depth into the first issue which caused this issue, but changing the project.yml should resolve all your cases.

**Comment by JuPrgn** [comment]
Hi @mvandervoord I have the same issue with `ceedling 0.29.0` when I set `test_preprocessor` to `true` and my source files are located in the project folder instead of a src folder. 

```
Compiling _test_myFile...
./build/temp/_test_myFile.c:2:23: fatal error: @@@@unity.h: No such file or directory
```

Disabling test preprocessor or moving source files in a separate folder fix this.

As explained by @dpostorivo setting project.yml to : 
```
:paths:
  :source:
    - ./**
```
Make ceedling to search for source files in all project subfolders and the error in my case come from `build/temp/_test_myFile.c`.

I don't know if this should be considered as a bug or if users should not place any source directly in project folder but in both cases we should fix or document it to help new users to not make the same mistakes.

In the first case we could not check for subfolders when source path equals project path (but I think this is my requirement and does not apply to everyone) or we could search in subfolders that are not used for build / test... ? I don't know if there is a way to ignore subfolders, this may also solve this if user can choose which folders to ignore ?
