### ISSUE TITLE
List tests functions and run tests one by one

### ISSUE THREAD

**Issue by Arrowana** [ThrowTheSwitch/Ceedling#162]
It seems like there is no way to compile the tests only to get a test list.

For distributed testing we need to be able to get a test lists for a Ceedling project then be able to run test functions one by one.

**Comment by mvandervoord** [comment]
Sorry, this isn't a feature that it supported. Unity itself doesn't support running a single individual test, so Ceedling can't ask it to. Ceedling CAN run a particular module's tests, but that's as close as we can get at the moment.
