### ISSUE TITLE
Rake modul creation aborts after completing 

### ISSUE THREAD

**Issue by sgessler** [ThrowTheSwitch/Ceedling#166]
Anybody else experiencing this issue?

Consol Log:
`mac:FirstOwnProject sge$ rake module:create[modulfunction]
File src/modulfunction.c created
File src/modulfunction.h created
File test/test_modulfunction.c created
Generate Complete
rake aborted!
ERROR: File modulfunction already exists. Exiting.
/Users/sge/Documents/workspace/ceedlingTest/FirstOwnProject/vendor/ceedling/vendor/unity/auto/generate_module.rb:197:in `generate'
/Users/sge/Documents/workspace/ceedlingTest/FirstOwnProject/vendor/ceedling/plugins/module_generator/lib/module_generator.rb:17:in `create'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `block (3 levels) in <top (required)>'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `each'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => module:create
(See full trace by running task with --trace)
mac:FirstOwnProject sge$ rake test:all`

**Comment by dpostorivo** [comment]
I've seen that although I the file is still created and it's like it's trying to create the file twice so while a bug, it's just annoying. I've been working on better internal testing so things like this get caught faster and before a release. I'll look into this more soon.

**Comment by StefanD986** [comment]
I am also seeing this problem. For completeness: here is a minimal example to reproduce the problem:

```
mkdir empty
ceedling new empty
cd empty/
ceedling module:create[totallynew]
```

The last command produces the files `src/totallynew.c`, `src/totallynew.h` and `src/test_totallynew.c`, but then throws an error. Full output:
```
File src/totallynew.c created
File src/totallynew.h created
File test/test_totallynew.c created
Generate Complete
rake aborted!
ERROR: File totallynew already exists. Exiting.
/Users/stefan/tdd/empty/vendor/ceedling/vendor/unity/auto/generate_module.rb:197:in `generate'
/Users/stefan/tdd/empty/vendor/ceedling/plugins/module_generator/lib/module_generator.rb:17:in `create'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `block (3 levels) in <top (required)>'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `each'
vendor/ceedling/plugins/module_generator/module_generator.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => module:create
(See full trace by running task with --trace)
```
