### ISSUE TITLE
Incorrect mocks when a function takes a two dimensional array as a parameter.

### ISSUE THREAD

**Issue by Ouss4** [ThrowTheSwitch/Ceedling#169]
I run into a problem when I tried to generate mocks for a function that has a 2D array as a parameter.

If the function for example has a signature of `int foo(int a[][4])` the mocking generates a function that takes an `int *a`: 
```
#define foo_ExpectAndReturn(a, cmock_retval) foo_CMockExpectAndReturn(__LINE__, a, cmock_retval)
void foo_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* a, int cmock_to_return);
```
In the other hand if one uses `int foo(int (*a)[4])` there seems to be an error in the generated mock macro, and gives :
```
#define foo_ExpectAndReturn(a)[4], cmock_retval) foo_CMockExpectAndReturn(__LINE__, a)[2], cmock_retval)
```
An * and a parentheses are missing before the variable name not only in the .h file but also in several places in the .c file.

**Comment by mvandervoord** [comment]
This is really a problem with CMock and is already on the issue list there. Sorry about the inconvenience. Multi-dimensional arrays are something we want to support, but so far haven't been added.
