### ISSUE TITLE
source  and header files  in sub-directories , cause "undefined reference"

### ISSUE THREAD

**Issue by redliu312** [ThrowTheSwitch/Ceedling#181]
## issue
I start a C project which depending  existing source  and head files which I put in a subdirectory . I found ceedling have the "undefined reference" when test the module which will the existing source codes in the subdirectory.  I make a small demo to duplicate this behaviour. The code is on this [repository](https://github.com/redliu312/ceedling_test)

## ceedling version
I am not sure the version number of the ceedling I use.
If I type ```ceedling --version ```   ,it shows ```rake, version 12.0.0```

## the output of the  demo  
**input:** :   ```rake test:old```
```output:```
```
Test 'test_old.c'
-----------------
Linking test_old.out...
build/test/out/old.o: In function `printfOld':
/home/redsimon/Dropbox/ceedlingTest/src/old.c:12: undefined reference to `printfNew'
collect2: error: ld returned 1 exit status
ERROR: Shell command failed.
> Shell executed command:
'gcc "build/test/out/test_old_runner.o" "build/test/out/test_old.o" "build/test/out/unity.o" "build/test/out/old.o" "build/test/out/cmock.o" -o "build/test/out/test_old.out"'

```

## show the heads and sources

```
redsimon@redsimon-desktop:~/Dropbox/ceedlingTest$ rake files:source
source files:
 - src/main.c
 - src/old.c
 - src/subdir/new.c
file count: 3
redsimon@redsimon-desktop:~/Dropbox/ceedlingTest$ rake files:header
header files:
 - src/main.h
 - src/old.h
 - src/subdir/new.h
 - src/subdir/new.h
file count: 4

```

# Did I miss something  or I just need to put all sources and headers in the same /src folder?

**Comment by mvandervoord** [comment]
The problem you're running into has nothing to do with subdirectories.

First, an aside: (this is not your problem, but we can improve your config here) you are specifying both /src/** and /scr/subdir/** which is redundant. You can think of the "/**" operator as meaning "and all the subdirectories you can find inside it". So /src/** already includes your subdir.

Back to your problem: Ceedling uses the #includes in the top of your TEST file to determine what to link together for your test. Your test_old.c file includes "old" and "unity", both of which it needs. But that's not sufficient. When it goes to link, old.c wants printfNew to be defined somewhere... but you've not defined it in any of the files you are linking in your test. So when it attempts to link, the linker complains about it not being defined.

You have two choices. This choice is going to greatly affect how you write your tests. The good news is that you can choose differently for every test file you write. 

Choice 1: You can directly include "new.h" too, and you're effectively testing the pair of the units together. This is technically an interaction test, not a unit test, but it works the same.

Choice 2: You can include a fake version of the functions in new.h. This can be automatically generated by including "mock_new.h" if you want CMock to do it for you... or you can include your own hand-made stubs / mocks / fakes / whatever.

I hope this helps.

Happy Testing!

(Please close this if you feel I've answered your questions sufficiently. Don't be afraid to ask for more details on anything. We'll do our best to help)

**Comment by redliu312** [comment]
Thanks a lot.
I will try the mock way to implement the unit test.
