### ISSUE TITLE
How to use unity fixture with ceedling?

### ISSUE THREAD

**Issue by dariosb** [ThrowTheSwitch/Ceedling#186]
This is the link to test file 
[https://github.com/dariosb/testsm/blob/master/test/test_InyectorControl.c](url)

Is able to use fixture with ceedling?

First throuble is that the unity_fixture.h include file is not found, then I add the fixture path to my .yml like this:
```
  :paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include:
    - inc/**
    - vendor/ceedling/vendor/unity/extras/fixture/src/
  :support:
    - test/support
```
After that, get this warning message when compiling test file:

_**_In file included from test/test_InyectorControl.c:17:0:
vendor/ceedling/vendor/unity/extras/fixture/src/unity_fixture.h:29:0: warning: "TEST" redefined
 #define TEST(group, name) \
 ^
<command-line>:0:0: note: this is the location of the previous definition_

That was solved adding this before unity_fixture.h be included in test file**_

```
#ifdef TEST
#undef TEST
#endif
```

Then all compilation and linking process, mocks and runners generation are well done, but fixture macros are not parsed by ceedling. Then, no test is executed.

Test 'test_InyectorControl.c'
-----------------------------
Generating runner for test_InyectorControl.c...
Compiling test_InyectorControl_runner.c...
Compiling test_InyectorControl.c...
Linking test_InyectorControl.out...
Running test_InyectorControl.out...

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.

**Comment by mvandervoord** [comment]
Ceedling was not really made to run the unity_fixtures wrapper. It's a tool designed to manage, build, and run Unity tests. The Fixtures addon is there to make Unity act like cpputest, which removes a lot of functionality. It might be possible, but I suspect there will be a few snags along the way.

**Comment by dariosb** [comment]
Mark,
Thanks for your answer.
Best regards
