### ISSUE TITLE
Case Sensitive Module Names

### ISSUE THREAD

**Issue by kebrahimpour** [ThrowTheSwitch/Ceedling#189]
Hi,

I have a project where I have to use case sensitive file names.  How can I configure
ceedling to work case sensitive (for example when I generate new Modules)

any hints are appretiated
Keyvan

**Comment by kebrahimpour** [comment]
I am using
Ceedling:: 0.27.0
CException:: 1.3.1.18
     CMock:: 2.4.4.215
     Unity:: 2.4.1.120

**Comment by kebrahimpour** [comment]
I have now updated to ceedling 0.28.1
same problem

**Comment by alexjaw** [comment]
Have this issue as well

```
~/aProject$ ceedling version
  Ceedling:: 0.28.1
CException:: 1.3.1.18
     CMock:: 2.4.4.215
     Unity:: 2.4.1.120
~/aProject$ ceedling module:create[CamelCase]
File src/camelcase.c created
File src/camelcase.h created
File test/test_camelcase.c created
Generate Complete
```

**Comment by kebrahimpour** [comment]
@alexjaw : I added the following setting to my project.yml to use CamelCase module names
...
_**:module_generator:
  :naming: "camel"**_

I am using same ceedling version as you mentioned, so it should work for you as well
for more options and details you should look at module_generator.

hih
