### ISSUE TITLE
Mocking .h file(a dependency) throws Argument Error

### ISSUE THREAD

**Issue by gauravbrd** [ThrowTheSwitch/Ceedling#207]
Hi, I have started ceedling for Unit testing of my huge code base. I am trying to mock a file and it throws Argument Error with Invalid byte sequence in UTF-8 complain. 
![image](https://user-images.githubusercontent.com/16008024/30829091-d1c493ba-a20d-11e7-8e8d-4acaef41d29b.png)

I hope this screenshot helps figuring out the problem.
Thanks in Advance.

**Comment by mvandervoord** [comment]
It's saying that your file hasn't been stored as a UTF-8 file nor an ascii
file. Do you know what character type your source file is? Do you know
which version of Ruby you are running? We've been trying to make these
things load seamlessly, but the support varies greatly by Ruby version.

Mark

**Comment by gauravbrd** [comment]
Some files are getting mocked. So source files are not getting mocked. I think we are using default character types. We have not changed anything which Keil compiler does not support. I am ceedling on  Ruby 1.9.3p484 on bash (ubuntu) on windows.

**Comment by gauravbrd** [comment]
I figured that one copyright symbol was causing trouble in source file store types. I removed that symbol and being able to mock it. Thanks @mvandervoord 
Closing this issue.

**Comment by mvandervoord** [comment]
@gauravbrd Thanks for sharing what the problem was!

Also, for your information (and anyone coming to this later): Version 1.9.3 of Ruby had partial support for unicode... but they really cleaned it up later in 2.0.0. So, I *believe* this is a non-issue if you're using the newer versions of Ruby.
