### ISSUE TITLE
undefined reference to SetUp and Teardown functions, OS inconsistency.

### ISSUE THREAD

**Issue by lesavonfou** [ThrowTheSwitch/Ceedling#212]
I found a difference between a Linux and Windows machine while compiling tests.
On my Linux machine, I am able to run a test file without `tearDown()` and `setUp()` functions included. Nevertheless, on my windows machine, gcc complains about undefined references to these functions.

I guess it's something related to weak attributes but forcing them through `UNITY_WEAK_ATTRIBUTE` or `UNITY_WEAK_PRAGMA` does not solve the situation.

Any tips to fix it?
Thank you!
Few information about my setup:
- ceedling v0.28.1
- gcc 6.3 on my Windows machine
- gcc 7.2 on my Linux machine

**Comment by mvandervoord** [comment]
A few questions: Are you using MinGW or Cygwin? What's the target? (Is it building a native application or cross compiling for a simulator?)

For some reason weak symbols are disabled in many of the MinGW distributions (they may have a good reason for this, but I'm not familiar with it), so I suspect that's the cause of not being able to force the weak symbols on your own.

Can you capture the actual error that it gives you?

**Comment by lesavonfou** [comment]
My project uses the MinGW's toolchain and my tests are compiled for a x86_64 target.
Apparently, I am not the only one having this problem with MinGW:
- [MinGW-s-GCC-and-attribute-weak](http://mingw.5.n7.nabble.com/MinGW-s-GCC-and-attribute-weak-td29339.html)
- [[Mingw-users] weak functions](https://groups.google.com/forum/#!topic/mingwusers/44B4QMPo8lQ)

So far, the problem seems to be laying around for while without a clear resolution. Users suggested to force the definition of the weak function during the linking sequence by using `--defsym _myfunc=.weak._myfunc` (See the second link).

From my side, I simply decided to not use weak symbols at all in ceedling and to implement dummy setUp and tearDown functions.

**Comment by mvandervoord** [comment]
Yeah, that matches what I've heard. Like I said, I don't know why MinGW disables weak symbol support. Hopefully they solve this. Sorry about that!

I hadn't seen the second option. I might try that. It seems like something that could be baked into Ceedling and done as a workaround.

**Comment by lesavonfou** [comment]
Shall we make this issue a feature request (with low priority)?
