### ISSUE TITLE
Modified test files not retested

### ISSUE THREAD

**Issue by lesavonfou** [ThrowTheSwitch/Ceedling#213]
I don't know if it's related to ceedling or unity but I've found an annoying behaviour while I was editing my unit test files.
To be specific "ceedling" did not take in account the renaming of a header file used in the unit test file. 
Before:
**test_my_unit_test.c**:
```
#include <xxx_yyy.h>
```
After:
**test_my_unit_test.c**:
```
#include <xxx.h>
```
During the compilation of the tests, only`xxx_yyy.h` is called, not `xxx.h`.

Any hint about how to solve this ?

**Comment by mvandervoord** [comment]
I suspect it would be fixed by calling "ceedling clobber test:all" to make sure that it deletes the temporary files, but it is definitely annoying that the dependency change wasn't recognized automatically. 

Out of curiosity, do you have :use_deep_dependencies enabled?

**Comment by lesavonfou** [comment]
No, would it change anything?

**Comment by mvandervoord** [comment]
That's the theory. It's significantly slower, though, so I think most people don't run it.

**Comment by lesavonfou** [comment]
Sadly, it doesn't solve the problem.
For now, i am going to insert a `clobber` task call before `test:all`
Thanks for your answers!
