### ISSUE TITLE
Example Project Doesn't Work

### ISSUE THREAD

**Issue by tslator** [ThrowTheSwitch/Ceedling#221]
I'm working on windows 10.  I cloned the Ceedling github and followed the instructions and I get the following output.  I tried using cmd.exe and git bash.  Same result either way.  I don't know what I'm doing wrong.

$ ceedling examples temp_sensor
ERROR: "ceedling examples" was called with arguments ["temp_sensor"]
Usage: "ceedling examples"
Welcome to Ceedling!

**Comment by m-chichikalov** [comment]
You shoud use "ceedling **example** temp_sensor"

**Comment by tslator** [comment]
yes, that works.  Where does example come from?  There is a examples folder.  Is this a ceedling feature?

Was able to build both blinky and temp_sensor, but I'm unable to run the tests.  I get this output:

> ceedling test:all
Welcome to Ceedling!
Could not find command "test:all".

I saw in a different article the command, rake test:all, but that fails miserably.  Any advice is appreciated.

> rake test:all --trace
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Z:/projects/ArloBot/Ceedling/Rakefile:3:in `<top (required)>'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
C:/Ruby24-x64/bin/rake:23:in `load'
C:/Ruby24-x64/bin/rake:23:in `<main>'

**Comment by mvandervoord** [comment]
Hi @tslator !

I strongly suspect that you haven't moved yourself into the directory of the example project you just created. You should call the ceedling command from the same folder as your project.yml file. It should be able to handle everything from there.

If at that point it doesn't know what you are talking about when you say "ceedling", then you are going to need to add ceedling to your path. This would be because you manually installed ceedling instead of installing it as a gem.

I hope this helps. Let us know if you still have troubles.

**Comment by tslator** [comment]
ok, that solve it.  thanks.  does ceedling support the ability to run tests for multiple projects from a top level directory?  For instance, there are two example projects: blinky and temp_sensor.  Can ceedling run tests for both with a single call or do I need to enter each project and run the tests?  Thanks.

**Comment by mvandervoord** [comment]
Ceedling is project-centric, so you would need to enter each one individually and run them. :)

Best of luck!

**Comment by tslator** [comment]
oops, one last error.  All tests run except TestMain.c.  The error suggests that TEST is not defined.  Its in the yaml file though.  I'm not making any changes, just running the clone repo:

Test 'TestMain.c'
-----------------
Linking TestMain.out...
build/test/out/Main.o: In function `main':
Z:\projects\ArloBot\Ceedling\temp_sensor/src/Main.c:43: multiple definition of `main'
build/test/out/TestMain_runner.o:Z:\projects\ArloBot\Ceedling\temp_sensor/build/test/runners/TestMain_runner.c:73: first defined here
collect2.exe: error: ld returned 1 exit status
ERROR: Shell command failed.
> Shell executed command:
'gcc.exe "build/test/out/TestMain_runner.o" "build/test/out/TestMain.o" "build/test/out/MockExecutor.o" "build/test/out/unity.o" "build/test/out/Main.o" "build/test/out/cmock.o" -o "build/test/out/TestMain.out" -lm'
> And exited with status: [1].

**Comment by mvandervoord** [comment]
Can you call "ceedling verbosity[4] test:all" and capture the part where it compiles the main function? It'd be good to know which options are getting passed in.

**Comment by mvandervoord** [comment]
Strange. It's interesting that it's double-defined as well. It almost sounds like your copy of gcc isn't working properly. This isn't a bug I've heard of for gcc, though.

**Comment by tslator** [comment]
I'm using mingw -- maybe that's a contributing factor.

**Comment by mvandervoord** [comment]
Could be. I use MinGW quite regularly, but it's possible that a specific version has an issue. The fact that you can SEE the -DTEST define being added makes it seem like it can't be Ceedling... or at least I sure hope not. ;)

**Comment by tslator** [comment]
I did a fresh install the 64-bit version.
