### ISSUE TITLE
Unable to test project module dispatch.c

### ISSUE THREAD

**Issue by tslator** [ThrowTheSwitch/Ceedling#229]
I have a module named dispatch.c when I attempt write tests for it, test_dispatch.c, I get output suggesting there is a memory problem.  I slowly widdled the test down to nothing but an empty setup/teardown and still I got the same error.  I cleaned and clobbered but still had the same error.  Finally, I renamed the test to be test_disp.c and no more problem.  I don't have a clue as to the problem:

> ceedling test:dispatch
Test 'test_dispatch.c'
----------------------
Generating runner for test_dispatch.c...
Compiling test_dispatch_runner.c...
Compiling test_dispatch.c...
Linking test_dispatch.out...
Running test_dispatch.out...

ERROR: Test executable "test_dispatch.out" failed.
> Produced no output to $stdout.
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test code.

rake aborted!

Z:/projects/ArloBot/arlobot_freesoc/vendor/ceedling/lib/ceedling/generator_helper.rb:36:in `test_results_error_handler'
Z:/projects/ArloBot/arlobot_freesoc/vendor/ceedling/lib/ceedling/generator.rb:162:in `generate_test_results'
Z:/projects/ArloBot/arlobot_freesoc/vendor/ceedling/lib/ceedling/rules_tests.rake:47:in `block in <top (required)>'
Z:/projects/ArloBot/arlobot_freesoc/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
Z:/projects/ArloBot/arlobot_freesoc/vendor/ceedling/lib/ceedling/test_invoker.rb:104:in `block in setup_and_invoke'
Z:/projects/ArloBot/arlobot_freesoc/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `each'
Z:/projects/ArloBot/arlobot_freesoc/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
Z:/projects/ArloBot/arlobot_freesoc/vendor/ceedling/lib/ceedling/rules_tests.rake:62:in `block (2 levels) in <top (required)>'
C:/Ruby23/bin/ceedling:23:in `load'
C:/Ruby23/bin/ceedling:23:in `<main>'
Tasks: TOP => build/test/results/test_dispatch.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.

**Comment by dpostorivo** [comment]
This is the same issue as in #116 and #146 . Windows does not like things being executed with "patch" or "setup" in the name.

**Comment by tslator** [comment]
Yes, agreed.  Thanks.

**Comment by wolf99** [comment]
This could be documented in the [Directory Structure, Filenames & Extensions](https://github.com/ThrowTheSwitch/Ceedling/blob/master/docs/CeedlingPacket.md#directory-structure-filenames--extensions) section of the Ceedling packet document maybe?

**Comment by dpostorivo** [comment]
Since this is documented, do we want to leave this open (and #116 and #146)  or do we want to close this as known and documented incompatibilities?

**Comment by mkarlesky** [comment]
This is officially documented now (and has been for quite a while). I've made a note to try adding special logging if Ceedling detects these scenarios.
