### ISSUE TITLE
ceedling, git and docker problems 

### ISSUE THREAD

**Issue by nscooling** [ThrowTheSwitch/Ceedling#238]
I am using ceedling with Bitbucket pipelines as a git project.

The problem I am encountering is that, by default, git does not track empty directories. When I come to use ceedling under docker on the pipeline, seedling is failing due to missing directories (e.g.``` test/support```,``` build```, etc.)

Is it possible to get empty files (I am using ```README.md``` file) as placeholders so that the appropriate directories will get tracked and pushed using git.

I am doing this manually, but it would be helpful to have this as a standard part of a new ceedling project.

**Comment by dpostorivo** [comment]
It should only give a warning for the build and you can remove the test/support from the project.yml and you don't have to worry about it.

The only directory Ceedling knows it needs is the build directory so Ceedling creates it. Everything else is up to the user. The default paths config comes like this:

```
:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
```

If you don't need test/support, you can simply remove it like this:
```
:paths:
  :test:
    - +:test/**
  :source:
    - src/**
```

**Comment by nscooling** [comment]
Thanks will try this out
