### ISSUE TITLE
Errno::ENOENT: No such file or directory - gcovr... [Windows/MSYS2]

### ISSUE THREAD

**Issue by carlolars** [ThrowTheSwitch/Ceedling#246]
running 'ceedling utils:gcov' on Windows10 with MSYS2 results in the error
`Errno::ENOENT: No such file or directory - gcovr -p -b -e "'^vendor.*|^build.*|^test.*|^lib.*'" --html -r . -o  "build/artifacts/gcov/GcovCoverageResults.html"`

**Solution**
The executable for _[:tools][:gcov_post_report...]_ must be _python3_ and the first argument must be the absolute path to the _gcovr_ script.

My project.yml has this in it:
```
:tools:
  :gcov_post_report:
    :executable: python3
    :optional: TRUE
    :arguments:
        - C:\msys64\mingw64\bin\gcovr
        - -p
        - -b
        - -e "\||^vendor.*|^build.*|^test.*|^lib.*"
        - --html
        - -r .
        - -o GcovCoverageResults.html
  :gcov_post_report_basic:
    :executable: python3
    :optional: TRUE
    :arguments:
        - C:\msys64\mingw64\bin\gcovr
        - -p
        - -b
        - -e "\||^vendor.*|^build.*|^test.*|^lib.*"
        - --html
        - -r .
        - -o  "$": GCOV_ARTIFACTS_FILE
  :gcov_post_report_advanced:
    :executable: python3
    :optional: TRUE
    :arguments:
        - C:\msys64\mingw64\bin\gcovr
        - -p
        - -b
        - -e "\||^vendor.*|^build.*|^test.*|^lib.*"
        - --html
        - --html-details
        - -r .
        - -o  "$": GCOV_ARTIFACTS_FILE
```

**Root cause**
I believe the root cause is something like this. The Windows default shell, which probably is what is used when _shell_backticks_ in _system_wrapper.rb_ is calling the _gcovr_ command, does not recognize _gcovr_ as an executable since it does not understand the shebang, as seen when trying to execute from a windows command prompt:
```
R:\>where gcovr
C:\msys64\mingw64\bin\gcovr

R:\>gcovr
'gcovr' is not recognized as an internal or external command,
operable program or batch file.
```

This problem was mentioned in #224.

**Comment by carlolars** [comment]
Oh I just realized that my example also included a fix for the _-e_ argument to _gcovr_.

On Windows the expression before the first OR (|) is ignored (why?), so my solution to this was to add an expression first that will never match a filename, so I added the character '|' (`\|`) which I belive is not valid in a filename on any system.
`-e '\||^vendor.*|^build.*|^test.*|^lib.*'`

**Comment by afacotti** [comment]
Hi, 
I just tested on Win7 pro (localization italian) but the solution above fails with a parsing error.
Trying more seems that this line can solve the problem:
`-e "vendor.*|^build.*|^test.*|^lib.*"`

Btw same topic addressed by #240

**Comment by carlolars** [comment]
Double-quotes works well, changed my example.

**Comment by IrksomeZeus** [comment]
Are you still having this issue?
I had the same error message and simply making sure python was on my path fixed the problem. I didn't have to change the configuration.
