### ISSUE TITLE
html report not generating 

### ISSUE THREAD

**Issue by Isuresh** [ThrowTheSwitch/Ceedling#250]
Hi , 

below is my project file 

:gcov:
  :html_report_type: detailed
  
:gcov_linker:                                                               
        :executable: gcc-5                                                      
        :arguments:                                                             
            - -ftest-coverage                                                   
            - -fprofile-arcs                                                    
            - -O0  # never optimize for this                                    
            - ${1}                                                              
            - -lm                                                               
            - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR                           
            - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR        
            - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE                    
            - -o ${2}                                                           
:gcov_fixture:                                                              
        :executable: ${1}                                                       
:gcov_report:                                                               
        :executable: gcov                                                       
        :arguments:                                                             
            - -n                                                                
            - -p                                                                
            - -b                                                                
            - -o "$": GCOV_BUILD_OUTPUT_PATH                                    
            - "\"${1}\""                                                        
:gcov_post_report:                                                          
        :executable: gcovr                                                      
        :optional: FALSE                                                        
        :arguments:                                                             
            - -p                                                                
            - -b                                                                
            - -e '.*tools.*|.*build.*|.*vendor/ceedling.*|.*test/test.*'        
            - --object-directory= "$": GCOV_BUILD_OUTPUT_PATH                   
            - --html                                                            
            - --html-details                                                  
            - -o build/artifacts/gcov/index.html       

with above configuration i am able build test cases with out any error by using ceedling gcov:all but it is not generating html coverage report can any one help please .

**Comment by dpostorivo** [comment]
you have to run `ceedling utils:gcov` afterwards. The gcov plugin does not do it on its own, it needs help from an external program called `gcovr` to actually generate the report.
