### ISSUE TITLE
 "Called more times than expected" appears. 

### ISSUE THREAD

**Issue by m-chichikalov** [ThrowTheSwitch/Ceedling#251]
Hi. Looks like a bug, not sure is it a problem with Ceedling or Cmock.
![](https://s8.hostingkartinok.com/uploads/images/2018/03/65d067605bb9d42822680dbf955de850.png)
![](https://s8.hostingkartinok.com/uploads/images/2018/03/e900cc9e592ed00a15348a6ae726079e.png)
![](https://s8.hostingkartinok.com/uploads/images/2018/03/93bd37b3e74f99736a46a0f37c72e7da.png)

Not sure what I can provide more ...

**Comment by mvandervoord** [comment]
You've closed the issue. Do you mind telling us what the problem was? It'd be good for anyone who runs into the same thing.

Mark

**Comment by m-chichikalov** [comment]
Sorry, this is just my missunderstanding of process. I mocked, and was surprised that ceedling started to report about fails : )

**Comment by sanj0905** [comment]
Hi, i'm facing the same issue, my error is "Function called more than expected".  What did you do inorder to rectify it ?

**Comment by Letme** [comment]
`s25f1064_page_data_read_Expect()` needs to be placed before the function call, if `s25f164_page_data_read` is a void function. I would also advise to put mocked_module_Init() and `_Verify()` calls in `setUp` and `tearDown`...

**Comment by baqianliu** [comment]
I also encountered the same problem. After checking my code logic and making modifications, the related problems disappeared

**Comment by itwondersteam** [comment]
copied from [stackoverflow](https://stackoverflow.com/a/51803024/12001850)


> A mock is generated code that has the same function signature as the function you’re mocking. A consequence is that you cannot have the mocked function and the original real function compiled and linked together in the same test executable. C only knows how to compile and link entire source files. It can’t pick and choose functions inside modules to mix together.
> 
> Put simply, this means you can’t make mocked calls to a function that’s inside the same source file you’re trying to test. This is a fundamental rule of interaction-based testing in C. On the whole this leads to better design (especially in large projects), but it does have the side effect of more files (go with longer descriptive file names) and sometimes arbitrary divisions of code among files to enable mocking.
> 
> Hence the best advice it to carve out foo_init() to be in a separate file from test_using_foo_init().
> 
> Generally speaking, any one test executable will consist of a single source module and one or more mocked modules whose function signatures are all outside the source you’re testing. In the simplest case you need at least two distinct modules (one source and one mocked) to test with mocks.
> ~ by liadd

**Comment by hong-dou-7** [comment]
I solved this problem.eg. if u have a function like this:
`void function(void)
{
    read_reg();
    write_reg();
    write_reg();
    write_reg();
}
`
and you haved mocked read_reg() with void func_[AddCallback,Stub](CMOCK_func_CALLBACK callback), then when you run testcase, it will report "Called more times than expected ", you need to call func_ExpectAnyArgsAndReturn the same times as the function write_reg() was called. if you called less, you will get "Called more times than expected". if you called more, you will get "Called less times than expected".But if write_reg() is called too many times, it seems to be a trouble to call func_ExpectAnyArgsAndReturn , maybe you can use func_IgnoreAndReturn, and you just call it once.
