### ISSUE TITLE
New Plugin: Raw Output Log

### ISSUE THREAD

**Issue by mvandervoord** [ThrowTheSwitch/Ceedling#252]
The new plugin would capture the raw output from running the tests and put it into an artifact file for the test, so that it could be perused at the user's leisure. This would not include ANY extra formatting (like the dashes and quotes being output while running, for example)

**Comment by dpostorivo** [comment]
Can this be closed or are there still desired improvements/features? I'll have some time before the end of the year to tackle some of this.
