### ISSUE TITLE
Ceedling launches .out file in Windows rather than executing the file in shell

### ISSUE THREAD

**Issue by dyang08** [ThrowTheSwitch/Ceedling#256]
After Ceedling outputs the "Running [output file].out" text, it launches the file in Windows using the default application. For instance, Wireshark opens and attempts to open the .out file.

This issue does not occur with examples, so I'm seeing the output from the example .out file via Ceedling. I'm confident there's an issue with the setup I have, but I am unsure where. The SUT is an IAR project targeting the MSP430, if that's relevant.

Here's the project.yml:
~~~~
---

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: FALSE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: FALSE
  :test_file_prefix: test_

#You'll have to specify these
:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/app/**
  :support:
    - test/support

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:tools:
  :test_compiler:
    :executable: icc430.exe
    :arguments:
      - ${1}
      ...
  :test_linker:
    :executable: xlink.exe
    :arguments:
      ...
      - -o C:\projects\ceedlingtest\build\test\out\test_Uart.out
      - -Fraw-binary
      
:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
    
:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
...
~~~~

**Comment by mvandervoord** [comment]
Under tools, I'm seeing that you defined a custom test_compiler and test_linker... which is making an executable meant to be run on an MSP430... but then you are attempting to run it on your Windows box as a native executable.

You'll need to override the default by also creating a test_fixture definition. This will look much like your test_compiler section, except you want to specify the command line arguments for calling IAR simulator for the MSP430. Your tests will then run on the simulator. This can get a little complicated, but that's the best option if you want to stick with the same compiler your release code uses.

If you don't care which compiler is used for your tests, you can instead make sure you have gcc, etc in your path somewhere and remove your tool definitions to run with defaults.

**Comment by dyang08** [comment]
Running CSpy as the test fixture did the trick. I gathered the command and arguments via the script generated by IAR in the settings folder. Thank you!

**Comment by mvandervoord** [comment]
:) glad to hear it!

**Comment by khyatisanghvi** [comment]
How did u fix this ? @dyang08
