### ISSUE TITLE
Next release date ?

### ISSUE THREAD

**Issue by FMorsbach** [ThrowTheSwitch/Ceedling#268]
The last release was in september last year. I am wondering, is there a new release version in sight?

**Comment by mvandervoord** [comment]
Hi. I don't have an official schedule put together, unfortunately. I tend to make a release when there have been significant updates. We will likely do another one soon. I was hoping to make a couple changes myself before that point, but haven't had the time. We'll keep at it. Feel free to remind me again. ;)

**Comment by dpostorivo** [comment]
I'm kind of curious about this as well. There's been 83 commits since the last release which shows a lot has been updated. 

Are there currently any blockers that need to be addressed before the release?
