### ISSUE TITLE
unity project configuration (unity_config.h vs. YAML)

### ISSUE THREAD

**Issue by lmapii** [ThrowTheSwitch/Ceedling#284]
Hello,

I'm trying to configure my ceedling project to "run as" 32-bit on host, which is a 64-bit machine. 

### Approach A

I'm not using <stdint.h> so I'm trying to use the configuration as proposed by the docs (https://github.com/ThrowTheSwitch/Ceedling/blob/master/docs/CeedlingPacket.md) but can't get it to run with unity/cmock. In my project.yaml I'm setting up the LONG/POINTER widths according to the docs:

```
:unity:
  :defines:
    - UNITY_EXCLUDE_LIMITS_H
    - UNITY_EXCLUDE_STDINT_H
    - UNITY_INT_WIDTH=32
    - UNITY_POINTER_WIDTH=32
    - UNITY_LONG_WIDTH=32
```

But using this doesn't seem to work since the test runners now generate a `#define` statement with the equal sign:

```
# build/test/runners/test_restlike_simple_00_runner.c:29:25: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
# #define UNITY_LONG_WIDTH=32
```

Also the size definitions do not seem to be matched by the system, meaning pointers will still always be 64 bit, see the following output. Also `cmock` doesn't seem to be to happy about it since it complains about size mismatch between 32 bit values and pointers:

```
  - "[   75 : test_request_response ] - sizeof uint8 1"
  - "[   76 : test_request_response ] - sizeof uint16 2"
  - "[   77 : test_request_response ] - sizeof uint32 4"
  - "[   78 : test_request_response ] - sizeof uint32 * 8"
  - "[   80 : test_request_response ] - bytes for UNITY_INT_WIDTH: 32"
  - "[   81 : test_request_response ] - bytes for UNITY_LONG_WIDTH: 32"
  - "[   82 : test_request_response ] - bytes for UNITY_POINTER_WIDTH: 32"
```

```
/Library/Ruby/Gems/2.3.0/gems/ceedling-0.28.2/vendor/cmock/src/cmock.c:126:12: warning: cast to 'unsigned int *' from smaller integer type 'unsigned int'
      [-Wint-to-pointer-cast]
  index = *(CMOCK_MEM_INDEX_TYPE*)((CMOCK_MEM_PTR_AS_INT)previous_item - CMOCK_MEM_INDEX_SIZE);
```

Is there any actual way to have the host to behave like a 32 bit system also for pointers? 

## Approach B

I've also tried just defining `UNITY_INCLUDE_CONFIG_H` instead and creating a proper `unity_config.h` - which gets rid of the C99 warning missing whitespace (since the `define` uses a `=`) but creates another warning: The test-runners now all define `UNITY_INCLUDE_CONFIG_H` which is already passed as a command-line argument if I'm using the following config:

```
:unity:
  :defines:
    - UNITY_INCLUDE_CONFIG_H
```

I got rid of that by placing the definition in the common-definition section

```
:defines:
  :commmon: &common_defines
  :test:
    - *common_defines
    - UNITY_INCLUDE_CONFIG_H
    - TEST
```

... but the `cmock` error still persists. I'm really starting to doubt that it is actually possible to run the tests as if it was a 32 bit machine - am I wrong?

**Comment by mvandervoord** [comment]
Interesting. 

Approach A works well when your compiler accepts that style of command line arguments, but clearly yours does not, so it's out.

Approach B seems to be working further... but I'm not clear on the details.

If you specify UNITY_INCLUDE_CONFIG_H as you do in the first example, is the compiler complaining when handling the test runners, saying that UNITY_INCLUDE_CONFIG_H is being redefined?

For the second case, what is the error that CMock is returning?

**Comment by joel-felcana** [comment]
@lmapii did you find a workaround? I'm interested in getting 32 bit code on my 64 bit computer. 

Cheers

**Comment by lmapii** [comment]
god - sorry i didn't update this issue ... used unity_config.h plus some compiler definitions, but since i'm running macos it didn't help for long: they removed 32-bit support completely. i'm now running my unittests from a docker-container.

*unity_config.h*
```
#define UNITY_EXCLUDE_LIMITS_H
#define UNITY_EXCLUDE_STDINT_H
#define UNITY_EXCLUDE_MATH_H
#define UNITY_LONG_WIDTH 32
#define UNITY_POINTER_WIDTH 32
#ifdef UNITY_INCLUDE_64
#undef UNITY_INCLUDE_64
#endif
```

*project.yml*
```

:defines:
  :commmon: &common_defines # A nice typo, next to invisible :)
  :test:
    - *common_defines
    - UNITY_INCLUDE_CONFIG_H
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:flags:
  :test:
    :compile:
      :*:
        - -g
        - -Wall
        - -O0
        - -m32
    :link:
      :*:
        - -g
        - -m32
  :gcov:
    :compile:
      :*:
        - -Wall
        - -m32
    :link:
      :*:
        - -m32
```
the `m32` flag was very important here. as mentioned i cannot execute this config on macos anymore since `m32` is not supported

**Comment by joel-felcana** [comment]
Worked as a charm. Sadly I found I'm in a similar situation. I'm on Windows using MSYS2, and they don't provide cross-compile tools for 64 and 32 bits. I can compile things in a 32 bit environment, but that defeats the purpose of all this, as it works as expected by default.

Thanks for sharing in any case!

**Comment by lmapii** [comment]
docker works for me, though volume-mounting is extremely slow on anything that is not plain linux. that 'docker is not a VM' thing is really not cutting it, file I/O on docker mounts is very slow and thus so is executing unit-tests within docker.

just add all the tools within the docker image (arm-gcc, ruby, etc.) and install ceedling within the image, works really well.

**Comment by joel-felcana** [comment]
That's a really good idea. We have an "issue", where the CI server was failing a test because it was pulling the wrong libraries (it's what happened to #92 and #136), and because we are testing across both Windows, Linux and Mac OS, with each running different versions of GCC, sticking to the same testing environment seems like the way to go (obviously, this is unrelated to Ceedling, it's not Ceedling's fault that I can't compile for a 32bit target 😆).
I know that doesn't solve your problems in Mac OS, but Looking forward for the new Linux Subsystem for Windows, it boots in a couple of seconds and will probably make all these things much easier.
