### ISSUE TITLE
impossible to do more than 13 tests

### ISSUE THREAD

**Issue by PhilippeBoulais1** [ThrowTheSwitch/Ceedling#285]
Hi,
I don't understand why, but when I get 13 tests or less on my source test file, everything is ok.
![13testspassed](https://user-images.githubusercontent.com/42073449/43725967-ec75a02c-996b-11e8-958f-11c336cb960b.PNG)

But, over this number, I have memory leaks, like «Trying to read outside linked memory at address...».
![ceedlingconsolepicture](https://user-images.githubusercontent.com/42073449/43725779-7320c878-996b-11e8-8e6e-3e38c0328d8e.PNG)

Also, to understand if it's my code or not, I just made tests with dummy ASSERT(variable == x
![exampletest](https://user-images.githubusercontent.com/42073449/43725723-4b2edde6-996b-11e8-911b-c7af89281adc.PNG)
)
Is anyone already have this kind of problem?

**Comment by mvandervoord** [comment]
My first guess would be that it's a limitation with the simulator or memory space for the application. Are you targeting something small like an AVR or PIC?

**Comment by PhilippeBoulais1** [comment]
found that «:use_exceptions: TRUE» in the XML configuration file was the fault. 
It was creating memory leaks...
I just replace by «:use_exceptions: FALSE».

**Comment by PhilippeBoulais1** [comment]
Thank's for your help mvandervoord!
my best regards
