### ISSUE TITLE
suiteSetUp and suiteTearDown undefined in Ceedling 0.28.3

### ISSUE THREAD

**Issue by dpostorivo** [ThrowTheSwitch/Ceedling#287]
Testing out the latest release of Ceedling while upgrading, the first thing I noticed is every test generate a warning for suiteSetUp and suiteTearDown like so:

```
build/test/runners/test_FileInterceptor_runner.c: In function ‘suite_setup’:
build/test/runners/test_FileInterceptor_runner.c:89:3: warning: implicit declaration of function ‘suiteSetUp’; did you mean ‘suite_setup’? [-Wimplicit-function-declaration]
   suiteSetUp();
   ^~~~~~~~~~
   suite_setup
build/test/runners/test_FileInterceptor_runner.c: In function ‘suite_teardown’:
build/test/runners/test_FileInterceptor_runner.c:97:10: warning: implicit declaration of function ‘suiteTearDown’; did you mean ‘suite_teardown’? [-Wimplicit-function-declaration]
   return suiteTearDown(num_failures);
          ^~~~~~~~~~~~~
          suite_teardown
```

Is there an update to the project.yml I need to add to fix this or something that needs to be fixed in the runner generators?

**Comment by mvandervoord** [comment]
Do you have :suite_setup and :suite_teardown defined in your yaml file?

**Comment by mvandervoord** [comment]
The warning shouldn't be there if you don't have that feature enabled... I was just trying to narrow down where the bug is. Clearly it's attempting to call something it should not in this case. :)

**Comment by dpostorivo** [comment]
I was able to suppress it by putting UNITY_NO_WEAK in the ceedling common defines, but I don't think that's intended. I first focused on the test generator in unitiy, but the logic seemed intentional.

```
   if @options[:suite_teardown].nil?
      # New style, call suiteTearDown() if we can use weak symbols
      output.puts('#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)')
      output.puts('  return suiteTearDown(num_failures);')
      output.puts('#else')
      output.puts('  return num_failures;')
      output.puts('#endif')
    else
      # Old style, C code embedded in the :suite_teardown option
      output.puts(@options[:suite_teardown])
    end
```

It seems that if suite_teardown is defined (or setup) it let's you put a custom suite setup.  The UNITY_WEAK_ATTRIBUTE is automatically set in unity_internal.h. Should that be the default behavior?

**Comment by lyager** [comment]
I'm running the above version, and getting the same warning. Before hacking too much around I was wondering if there is a .yaml configuration file workaround, to avoid the warning (which in my case, halts further execution).

**Comment by dpostorivo** [comment]
@lyager  add `UNITY_NO_WEAK` to your project.yml defines section and the warnings will go away.

**Comment by dpostorivo** [comment]
I'm curious on an update to this. Using UNITY_NO_WEAK is an ok workaround, but in projects where typedefs are used to control tests the lack of setup and teardown causes compiler issues.

**Comment by art-of-dom** [comment]
This is no longer an issue as of 0.29.0.
