### ISSUE TITLE
Multiple Object File Extensions

### ISSUE THREAD

**Issue by pete-restall** [ThrowTheSwitch/Ceedling#294]
Hello,

I am trying to use Ceedling with Microchip's XC8 and it's proving to be a bit harder than I'd hoped.  One issue is that XC8 generates object files with a '.o' extension if they've been assembled, and a '.p1' extension if they're the compiler's intermediate files.  XC8 unfortunately does not respect file extensions if you try and force them.

There are workarounds such as writing scripts to compile and assemble with a step to rename the output files.  Or to use string interpolation on the arguments passed into the linker in the project.yml file, which is what I'm currently doing.

What's really required is some sort of :assembly_object: key underneath :extension: - or just allowing :object: to be an array.

Thanks.

**Comment by LanceBeasley** [comment]
I'm having the same problem. The test runner file is being compiled to a test_runner.p1 file, but the Ceedling linker command refers to the [non-existent] test_runner.o file. How do I fix this?

**Comment by LanceBeasley** [comment]
I'm also running XC8, Ceedling 0.31.1, Ruby 3.0. Kept getting the following error:
`::: error: (141) can't open intput file "./build/test/out/c/runner.o": No such file or directory`

The fix was to add the following line to the extension section:
:extension:
  :executable: .out
  :object: .p1 <<<<<<<<<<<

**Comment by mkarlesky** [comment]
Closing this issue but only to cull the open issue list a bit. I'm also rolling this issue up into a single issue that deals with multiple file extensions for a single file type.
