### ISSUE TITLE
How to avoid Cmock after changing the directory of project created by ceedling?

### ISSUE THREAD

**Issue by mentalibor** [ThrowTheSwitch/Ceedling#299]
Can we find a way to avoid generating of CMock files after we change project directory location?

**Comment by mvandervoord** [comment]
Can you elaborate? If you've changed folders and the mocks no longer exist, it's going to need to generate mocks, right? I don't think I'm understanding your situation.

**Comment by mentalibor** [comment]
I succeeded to create a project with ceedling and successfully tested it with 'ceedling test:all'. After I copied the complete project generated by 'ceedling new Project' and paste it on somewhere in the system, then I opened this copy of projects in terminal and run command 'ceedling test:all' and it returns me some errors such as "error: conflicting types". I had these errors for the first time when I created new ceedling project and I fixed them manually, but it bothers me that it didn't copy the fixed files... I checked the permissions and everything is fine.

**Comment by mentalibor** [comment]
I mean I had to change some parameters in the functions in mocked library so that there are no more conflicts. However, it is still weird... 

Could you tell me where I can find this header?

**Comment by mvandervoord** [comment]
The header is your main source header. For example, if you are generating a mock named "MockHedgehogs.h", it's looking for your header file named "Hedgehogs.h" and it's generating all the function prototypes off of that. So there shouldn't be any conflicts in types unless:

(a) you have a function declaration defined in multiple places which don't match.
(b) you have multiple instances of Hedgehogs.h in different folders and they are both in your search path. 
(c) you have a function prototypes which pass arrays (cmock converts them to pointers at this point)
