### ISSUE TITLE
Ceedling uses src header instead of test/support header

### ISSUE THREAD

**Issue by rwerthman** [ThrowTheSwitch/Ceedling#320]
When running `ceedling`, the compiler uses a header file from the actual src instead of the header file in test/support.  The header file in test/support was created to remove the `#pragma` lines in the original file. I would expect ceedling to use the header file from test/support instead of the header file in src because ceedling checks the test/support path before the src path.  Also I excluded the header file from src in my .yml configuration.

```
$ ceedling


Test 'test_file.c'
-------------------------
Generating dependencies for test_file.c...
Generating runner for test_file.c...
Compiling test_file_runner.c...
In file included from ../Calibrations/src/ReaderWriter.h:8,
                 from build/test/mocks/mock_ReaderWriter.h:6,
                 from build/test/runners/test_file_runner.c:37:
../Calibrations/src/CalibrationTypes.h:4:9: warning: missing '(' after '#pragma pack' - ignored [-Wpragmas]
 #pragma pack
         ^~~~
Compiling test_file.c...
In file included from ../Calibrations/src/ReaderWriter.h:8,
                 from src/file.c:26,
                 from test/test_file.c:2:
../Calibrations/src/CalibrationTypes.h:4:9: warning: missing '(' after '#pragma pack' - ignored [-Wpragmas]
 #pragma pack
         ^~~~
Linking test_file.out...
Running test_file.out...

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  2
PASSED:  2
FAILED:  0
IGNORED: 0
```

```
$ ceedling files:header | grep -i 'CalibrationTypes.h'
 - test/support/CalibrationTypes.h
```

```
:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - -:../test_project/build/**
    - -:../test_project/test/**
    - +:src/**
    - +:../**
  :support:
    - test/support

:files:
  :include:
    - -:../Calibrations/src/CalibrationTypes.h
```

Any idea why this is happening or a way to diagnose this?  I have other header files in test/support that are correctly used before the src header files.

```
$ ceedling version
  Ceedling:: 0.28.3
CException:: 1.3.1.18
     CMock:: 2.4.6.217
     Unity:: 2.4.3.122
```

I'm running ceedling in git bash for windows 7.  I have mingw installed.

**Comment by rwerthman** [comment]
Looking into it further, it looks like the .d (dependency) files found in build/test/depedencies/ generated by make include the header from support/test and the header from src.  That doesn't seem right.  I think it should include one or the other but not both as dependencies.  It looks like the function `generate_dependencies_file` in `generator.rb` executes the `gcc` command that does this.  If you use `puts` to print out the `tool` you get the following output:
```
{:executable=>"gcc.exe", :name=>"default_test_dependencies_generator", :stderr_redirect=>:none, 
:background_exec=>:none, :optional=>false, :arguments=>["-E", 
{"-I\"$\""=>"COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR"}, 
{"-I\"$\""=>"COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE"}, {"-D$"=>"COLLECTION_DEFINES_TEST_AND_VENDOR"}, 
{"-D$"=>"DEFINES_TEST_PREPROCESS"}, "-DGNU_COMPILER", 
"-MT \"${3}\"", "-MM", "-MD", "-MG", "-MF \"${2}\"", "-c \"${1}\""]}
```

I'm not sure how to keep the duplicate headers from being included in the .d file or how to ensure the test/support header is include over the src header.

**Comment by rwerthman** [comment]
Well I think the issue comes down to ggc.  It sounds like it is affect by item 1 at https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#Directory-Options.  

> For the quote form of the include directive, the directory of the current file is searched first.
then

> Directories specified with -I options are scanned in left-to-right order.

Because the header file source I created for test/support is actually in the same directory as the file being  built, it will use the src header file instead of the test/support header file.  Even though gcc usually scans the includes from left-to-right.

**Comment by campbell-brown** [comment]
This isn't ideal for header files that we can't modify (e.g. from submodules). It would be good if the included search directories were predictable so we could override header files for specific library files.
