### ISSUE TITLE
Run individual test cases

### ISSUE THREAD

**Issue by danebou** [ThrowTheSwitch/Ceedling#330]
Create the ability to run a single test individually. 

Something similar to:
`ceedling test:test_module:test_name`.

(Related: #162)

**Comment by RuntimeException** [comment]
@mvandervoord You wrote that in #162 that it is not possible to make unity to run single testcases but if I add the following config parameter to the _project.yml_ then unity is able to process command line arguments where this could be specified:

```
:test_runner:
  :cmdline_args: true
```
test_executable.out -n test_name

What is your opinion about this idea?

**Comment by lukzeg** [comment]
Hi @danebou , @Quentis , @bsd5 , 

Can you look at https://github.com/ThrowTheSwitch/Ceedling/pull/736, which was merged to master branch and confirm, if proposed solution fit to your needs?

If no, please let me know, I will try to fix it.
If yes, do you think that we can close this topic, as the feature was delivered to master?

**Comment by Quentis** [comment]
Yes, that seems to be what we need.
Thanks a lot for the implementation.
