### ISSUE TITLE
[Feature Request] Add gcov_post_report_xml option

### ISSUE THREAD

**Issue by psheph** [ThrowTheSwitch/Ceedling#331]
I would like to see ceedling's gcov plugin be able to generate xml reports suitable for inclusion on a Jenkins build-status page. I am not proficient in Ruby development, so my implementation was a hack of the gcov_post_report_advanced settings in the YAML file. I believe it could be implemented by adding a new entry in the plugin YAML file which is executed by a new setting in the gcov plugin section of the project's default.yml file.

Changes I made which produced a valid xml report:

* in ($PROJECT_DIR)/vendor/ceedling/plugins/gcov/lib/gcov_constants.rb, I changed GCOV_ARTIFACTS_FILE to a .xml file extension.
* in ($PROJECT_DIR)/vendor/ceedling/plugins/gcov/config/defaults.yml, I changed the :gcov_post_report_advanced::arguments: to remove --html and --html-details, and add --xml.

**Comment by dpostorivo** [comment]
This feature should now be on master.
