### ISSUE TITLE
throwtheswitch.org information not up to date?

### ISSUE THREAD

**Issue by herrmanthegerman** [ThrowTheSwitch/Ceedling#333]
[www.throwtheswitch.org](http://www.throwtheswitch.org/ceedling) (while it has a beautiful design) asserts that:

> To see what you can do with the gem, just call the executable with no arguments:
> `ceedling`
> Which will show you the available goodness:
> 
> `Tasks:`
> `ceedling example PROJ_NAME [DEST]# create specified example project (in DEST, if specified)`
> `ceedling examples# list available example projects`
> `ceedling help [TASK] # Describe available tasks or one specific task`
> `ceedling new PROJECT_NAME# create a new ceedling project`
> `ceedling update DIRECTORY# update the vendor/ceedling directory under the given project root`
> `ceedling version # print all ceedling gem and library versions`

My version of ceedling (0.28.3) behaves differently:

- Issuing `ceedling` runs tests. To see the "available goodness", I have to issue `ceedling help`. 
- Also `ceedling update` is not supported. Instead, I used `gem update` to update ceedling.

Thanks.

**Comment by mvandervoord** [comment]
Thanks so much! I've tackled the documentation changes to get the website up to date. The `update` function is an upcoming feature that already has an issue open of its own.

**Comment by herrmanthegerman** [comment]
I just figured that I have to change to a parent directory of my ceedling project to make ceedling provide the output as described on the web page. Sorry, my bad. As soon as I'm in the project directory, the behaviour changes. I didn't know that.
