### ISSUE TITLE
How do I add multiple paths to source?

### ISSUE THREAD

**Issue by brennanjleahey** [ThrowTheSwitch/Ceedling#338]
Hello, noob here. I am having trouble adding more than one path/folder to source in the .yml file. I can only get the first entry to be compatible. 
Ex: (excuse the poor formatting, github is doing this automatically)

  :source:
	 - +:C:\Main_2019\Work\[REDACTED]\Project\[REDACTED_SIMULATING_LENGTH_OF_PATH]\trunk\Main\[REDACTED1]

	 - +:C:\Main_2019\Work\[REDACTED]\Project\[REDACTED_SIMULATING_LENGTH_OF_PATH]\trunk\Main\[REDACTED2]

         - +:C:\Main_2019\Work\[REDACTED]\Project\[REDACTED_SIMULATING_LENGTH_OF_PATH]\trunk\Main\[REDACTED3]

when I enter ceedling files:source, only the files in the first entry ([REDACTED1]) will be displayed. I've tried different forms of syntax (no plus only -, less spacing, etc..). The files need to stay in their respected paths because I cannot move them to the src folder in ceedling project. The paths are located outside of the ceedling project folder.

Error I get after listing the first path's files:  

found character that cannot start any token while scanning for the next token at line 33 co
lumn 1 (Psych::SyntaxError)

Any help is appreciated!

**Comment by mvandervoord** [comment]
From the error, it sounds like it may be a problem with the indenting or another character in the way. If you can in your editor, show whitespace and/or have it replace tabs with spaces automatically. Make sure that both of the source lines are indented the same amount.

```
:source: 
    - +:C:\Main_2019\Work\[REDACTED]\Project\[REDACTED]\trunk\Main\[REDACTED2]
    - +:C:\Main_2019\Work\[REDACTED]\Project\[REDACTED]\trunk\Main\[REDACTED3]
```

**Comment by mvandervoord** [comment]
Since you aren't using wildcards, it appears, you can make it even simpler:

```
:source: 
    - "C:\Main_2019\Work\[REDACTED]\Project\[REDACTED]\trunk\Main\[REDACTED2]"
    - "C:\Main_2019\Work\[REDACTED]\Project\[REDACTED]\trunk\Main\[REDACTED3]"
```

**Comment by brennanjleahey** [comment]
Parsing error goes away using the +: syntax, or just the normal - syntax, but I get the same parsing error when using the "" method. I still cannot read all files in, some of the folders do have more than .c .h files. I still only see the first entry when I run the source command.

**Comment by brennanjleahey** [comment]
What is the most compatible solution, making a copy of all the source files and placing in the ceedling project src folder?

**Comment by mvandervoord** [comment]
There's no need to do that. Ceedling can handle any combination of paths. it's definitely something to do with your syntax.

**Comment by brennanjleahey** [comment]
I see, it's curious that only the first path is being read and putting - src/** (default entry) after the first path produces no errors.

**Comment by Letme** [comment]
It would be really helpful if you could paste the tree so that we see from where you want to run it.

Never copy the files. It will just create a mess what is the source of truth.

**Comment by mvandervoord** [comment]
Are you working with subdirectories under those folders as well?

```
:paths:
  :source: 
    - C:\Main_2019\Work\[REDACTED]\Project\[REDACTED]\trunk\Main\[REDACTED2]\*
    - C:\Main_2019\Work\[REDACTED]\Project\[REDACTED]\trunk\Main\[REDACTED3]\**
```

The first one says that you want all the files in `redacted2`. The second says you want all the files in subfolders in `redacted3`.

**Comment by mvandervoord** [comment]
Just to verify: Your indenting looks something like that in the examples above... and there are no extra lines between the paths, correct?

**Comment by brennanjleahey** [comment]
Apologies, I had an oversight, I was copy/pasting the paths here, but I am using three distinct paths. Only thing in common is that they are all in trunk folder. Give me one moment to make a crude text diagram to explain the paths clearly.

**Comment by Letme** [comment]
And to me it sounds like you want to use the wildcards, based on the multiple .c and .h files comment. You are also using absolute paths, i will assume with spaces, but if you are using on cygwin then slashes change, etc.

**Comment by brennanjleahey** [comment]
Trunk:
- mock <- ceedling project
- Main <- holds 2 distinct folders that are pathed separately (Main/src)&(Main/inc)
- [REDACTED_LIBRARY] <- holds files that need to be pathed to

**Comment by brennanjleahey** [comment]
It's getting even weirder. When I take the main\src path out, leaving 2 paths main\inc and trunk\[RED_LIBRARY], I get zero source files

**Comment by mvandervoord** [comment]
Have you tried doing relative paths instead of absolutes?
Are there spaces in your paths?
Are you using Cygwin?

**Comment by brennanjleahey** [comment]
figured it out, just stupid. Didn't realize that the listed source files are only .c and no .h files are listed
