### ISSUE TITLE
Undefined Reference when using Expect and Ignore 

### ISSUE THREAD

**Issue by brennanjleahey** [ThrowTheSwitch/Ceedling#339]
I am trying to test if a function calls another function using the Expect function in ceedling. Ex:

I have 3 files: test_config.c config.h config.c

I have 2 functions, both void, both defined in config.c and declared in config.h: fun1 and fun2

Here are the three files:

--------------------------
**//config.h**
#ifndef _CONFIG_H
#define _CONFIG_H

void fun1(void);
void fun2(void);

#endif // _CONFIG_H

--------------------------
**//config.c**
#include "config.h"
int flag = 0;
void fun1(void)
{
	flag = 1;
}
void fun2(void)
{
	fun1();
}

--------------------------
**//test_config.c**
#include "unity.h"
#include "config.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_config_fun2CallsFun1(void)
{
	fun1_Expect();
	fun2();
}

--------------------------
Error: `test/test_config.c: In function 'test_config_fun2CallsFun1':
test/test_config.c:14:2: warning: implicit declaration of function 'fun1_Expect'
 [-Wimplicit-function-declaration]
  fun1_Expect();`

`...../ceedTest/test/test_config.c:14: undefined reference to fun1_Expect`

**Comment by mvandervoord** [comment]
I suspect you're not including the mock version of the module containing slave_init. For example, if slave_init is in a file named "slaves.h", then you would want to have this at the top of your test file:

```
#include "mock_slaves.h"
```

**Comment by brennanjleahey** [comment]
slave_Init is in Slave.c, this function is called in Master.c
call_slave_Init is the function in Master.c that calls slave_Init. 
Getting zero errors when commenting out slave_Init_Expect function in test file.

The test file I am writing in is test_Master.c, I included Master.h at the top. Master.c includes Master.h, Slave.h and Slave.c. I get multiple definition error when I #include "mock_Slave.h" in test_Master.c

**Comment by brennanjleahey** [comment]
What are the requirements to use the Expect and Ignore tests? Disregarding the issue, please correct my syntax if wrong:

`void test_call_slave_Init(void)
{
	slave_Init_Expect();
	call_slave_init();
}
`

**Comment by brennanjleahey** [comment]
Ok, so here is a simple example of the error, disregard the project above:

I have 3 files: test_config.c config.h config.c

I have 2 functions, both void, both defined in config.c and declared in config.h: fun1 and fun2

Here are the three files:

--------------------------
**//config.h**
#ifndef _CONFIG_H
#define _CONFIG_H

void fun1(void);
void fun2(void);

#endif // _CONFIG_H

--------------------------
**//config.c**
#include "config.h"
int flag = 0;
void fun1(void)
{
	flag = 1;
}
void fun2(void)
{
	fun1();
}

--------------------------
**//test_config.c**
#include "unity.h"
#include "config.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_config_fun2CallsFun1(void)
{
	fun1_Expect();
	fun2();
}

--------------------------
Error: `test/test_config.c: In function 'test_config_fun2CallsFun1':
test/test_config.c:14:2: warning: implicit declaration of function 'fun1_Expect'
 [-Wimplicit-function-declaration]
  fun1_Expect();`

`...../ceedTest/test/test_config.c:14: undefined reference to fun1_Expect`

**Comment by mvandervoord** [comment]
Ah yes. The problem is that you can either use a real implementation of a C module, OR you can use the mock version of that module. C's linker won't let you have both in the same executable. 

Therefore, you can only mock things that are in separate files from the unit you are testing.

**Comment by brennanjleahey** [comment]
Ok, what you said along with following examples has helped me. I understand the issue. Thank you very much!
