### ISSUE TITLE
test function calls passed as a structure argument

### ISSUE THREAD

**Issue by krish2487** [ThrowTheSwitch/Ceedling#341]
Hello,

I have a peculiar problem testing a hd44780 library I wrote. I am still trying to wrap my head around modular code and dependancy injections and such.
Please bear with me :-).

The overview is this - I wanted to write a more or less modular and adaptable library for a HD44780 library for practice. This is where I went about the process wrong I think.
I did write the library first and it works, but I want to force myself to write unit tests for it and practice TDD as a mindset. 

The library consists of three files - lcd.c, lcd.h, lcd_defs.h. The lcd_defs.h are generic lcd definitions and the remaining files form the core library. The idea of he library is this, a user creates a device structure and populates it with the configuration for the lcd, including populating function pointers for writing data/commands to the lcd and delay functions. The library then invokes the passed in pointers in the sequence as specified. I feel, this makes the library mostly portable and platform independant. All the user needs to do is define functions for writing data/commands to lcd and delay functions and pass them in..

Please correct me if I am going about it the wrong way, I would like to test the functions in lcd.c. Say the init function. I would like to verify that the functions that are populated in the structure are in fact being called in the same sequence.
ex
command()
delay()
command()
delay()

so on....

 I would also like to verify that the configuration being passed in is within an acceptable limit.

for ex, the ENTRY_MODE configuration cannot be greater than ENTRY_MODE_BASE define. 

I am trying to rewrite the files attached above to practice TDD by implementing
1. checks for wrong inputs.
2. improper exit conditions
3. correct invocation of functions.

I would be extremely grateful if someone can help me identify my lack of understanding and guide how do I get about unit testing such a code.

I have attached the entire folder compressed as a zip file in case someone needs to replicate the code. 
Under the src, the hd44780.c and hd44780.h are the rewrites of the existing library. I am trying to do TDD with them. the lcd.c, lcd.h, lcd_defs.h are the existing legacy files.

Thanks in advance! :-)
[hd44780.zip](https://github.com/ThrowTheSwitch/Ceedling/files/3038337/hd44780.zip)

**Comment by krish2487** [comment]
Ok. I think I got it figured out. The key was to create a bsp.h file which contained the function signatures to be passed into the device structure and then mock the bsp.h file.
Now I am able to use the cmock library to check for function calls.

lcd.c ( part of it.. its too long)

`#include "lcd.h"


struct char_lcd_dev *init_lcd_struct(uint8_t entry_mode, uint8_t display_control, uint8_t function_set, uint8_t display_shift, data_ptr send_data, command_ptr send_command, delay_ptr milliseconds, delay_ptr microseconds)
{


    struct char_lcd_dev *structure = malloc(sizeof(struct char_lcd_dev));

    structure->entry_mode = ENTRY_MODE_BASE | entry_mode;
    structure->display_control = DISPLAY_CONTROL_BASE | display_control;
    structure->function_set = FUNCTION_SET_BASE | function_set;
    structure->display_shift = DISPLAY_SHIFT_BASE | display_shift;
    structure->lcd_send_commandbyte = send_command;
    structure->lcd_send_databyte = send_data;
    structure->delay_useconds = microseconds;
    structure->delay_mseconds = milliseconds;
    return structure;
}

void lcd_send_data(char *data, uint8_t length, struct char_lcd_dev *lcd_device_struct)
{
    for (uint8_t i = 0; i <= length - 1 ; i++)
        {
            lcd_device_struct->lcd_send_databyte(*data++);
        }
}


int lcd_init(struct char_lcd_dev *lcd_device_struct)
{

    lcd_device_struct->lcd_send_commandbyte(lcd_device_struct->function_set);
    lcd_device_struct->delay_mseconds(5);
    lcd_device_struct->lcd_send_commandbyte(lcd_device_struct->function_set);
    lcd_device_struct->delay_useconds(100);
    lcd_device_struct->lcd_send_commandbyte(lcd_device_struct->function_set);
    lcd_device_struct->delay_useconds(100);
    lcd_device_struct->lcd_send_commandbyte(lcd_device_struct->function_set);
    lcd_device_struct->delay_useconds(100);

    // lcd_device_struct->lcd_send_commandbyte(DISPLAY_CONTROL_BASE | DISPLAY_CONTROL_OFF);
    // lcd_device_struct->delay_mseconds(100);

    // lcd_device_struct->lcd_send_commandbyte(lcd_device_struct->entry_mode);
    // lcd_device_struct->delay_useconds(100);

    // lcd_device_struct->lcd_send_commandbyte(lcd_device_struct->display_shift);
    // lcd_device_struct->delay_useconds(100);

    // lcd_device_struct->lcd_send_commandbyte(lcd_device_struct->display_control);
    // lcd_device_struct->delay_mseconds(100);

    // lcd_device_struct->lcd_send_commandbyte(RETURN_HOME);
    // lcd_device_struct->delay_mseconds(100);
    // lcd_device_struct->lcd_send_commandbyte(CLEAR_DISPLAY);
    // lcd_device_struct->delay_mseconds(100);

    return 0;

}`

lcd.h

`#ifndef LCD_H
#define LCD_H


#include "lcd_defs.h"
#include "delay.h"
#include <stdint.h>

//Different types of lcd displays
#define LCD_16x2
// #define LCD_20x4
// #define LCD_8x2
// #define LCD_20x2

int lcd_init(struct char_lcd_dev *lcd_device_struct);
void lcd_clear_display(struct char_lcd_dev *lcd_device_struct);
void lcd_goto_home(struct char_lcd_dev *lcd_device_struct);
void lcd_goto(uint8_t row, uint8_t column, struct char_lcd_dev *lcd_device_struct);
void lcd_send_data(char *data, uint8_t length, struct char_lcd_dev *lcd_device_struct);
struct char_lcd_dev *init_lcd_struct(uint8_t entry_mode, uint8_t display_control, uint8_t function_set, uint8_t display_shift, data_ptr send_data, command_ptr send_command, delay_ptr milliseconds, delay_ptr microseconds);

#endif`

lcd_defs.h

`#ifndef __LCD_DEFS
#define __LCD_DEFS

#include <stdint.h>

#define CLEAR_DISPLAY 0x01

#define RETURN_HOME 0x02

#define ENTRY_MODE_BASE 0x04
#define ENTRY_MODE_INCREMENT (1 << 1)
#define ENTRY_MODE_DECREMENT (0 << 1)
#define ENTRY_MODE_DISPLAYSHIFT (1)
#define ENTRY_MODE_NODISPLAYSHIFT (0)

#define DISPLAY_CONTROL_BASE 0x08
#define DISPLAY_CONTROL_ON (1 << 2)
#define DISPLAY_CONTROL_OFF (1 << 2)
#define DISPLAY_CONTROL_CURSORON (1 << 1)
#define DISPLAY_CONTROL_CURSOROFF (0 << 1)
#define DISPLAY_CONTROL_BLINK (1)
#define DISPLAY_CONTROL_NOBLINK (0)

#define DISPLAY_SHIFT_BASE 0x10
#define DISPLAY_SHIFT_CURSOR (0 << 3)
#define DISPLAY_SHIFT_DISPLAY (1 << 3)
#define DISPLAY_SHIFT_RIGHT (1 << 2 )
#define DISPLAY_SHIFT_LEFT (0 << 2 )

#define FUNCTION_SET_BASE 0x20
#define FUNCTION_SET_DL_8BIT (1 << 4)
#define FUNCTION_SET_DL_4BIT (0 << 4)
#define FUNCTION_SET_1_LINE (0 << 3)
#define FUNCTION_SET_2_LINE (1 << 3)
#define FUNCTION_SET_5x11 (1 << 2)
#define FUNCTION_SET_5x8 (0 << 2)

#define SET_CURSOR_BASE 0x80

typedef void (*command_ptr)(uint8_t byte);
typedef void (*data_ptr)(char byte);
typedef void (*delay_ptr)(uint16_t delay);

struct char_lcd_dev
{

    uint8_t entry_mode;
    uint8_t display_control;
    uint8_t display_shift;
    uint8_t function_set;

    data_ptr lcd_send_databyte;
    command_ptr lcd_send_commandbyte;
    delay_ptr delay_useconds;
    delay_ptr delay_mseconds;

};


#endif
`

bsp.h

`#ifndef __BSP__H
#define __BSP__H
#include <stdint.h>

void lcd_command(uint8_t byte);
void lcd_data(char byte);
void delay(uint16_t delay);


#endif`


test_lcd.c

`#include "unity.h"
#include "lcd.h"
#include "lcd_defs.h"
#include "stdlib.h"
#include "stdbool.h"
#include "mock_bsp.h"

struct char_lcd_dev *dut_struct;

void setUp(void)
{
    dut_struct = malloc(sizeof(struct char_lcd_dev));
    dut_struct->function_set = (FUNCTION_SET_BASE | FUNCTION_SET_DL_4BIT | FUNCTION_SET_5x8 | FUNCTION_SET_2_LINE );
    dut_struct->entry_mode = ENTRY_MODE_BASE | ENTRY_MODE_INCREMENT | ENTRY_MODE_DISPLAYSHIFT;
    dut_struct->display_control = DISPLAY_CONTROL_BASE | DISPLAY_CONTROL_ON | DISPLAY_CONTROL_CURSORON | DISPLAY_CONTROL_BLINK;
    dut_struct->display_shift = DISPLAY_SHIFT_BASE | DISPLAY_SHIFT_CURSOR | DISPLAY_SHIFT_RIGHT;
    dut_struct->lcd_send_commandbyte = lcd_command;
    dut_struct->lcd_send_databyte = lcd_data;
    dut_struct->delay_mseconds = delay;
    dut_struct->delay_useconds = delay;
}

void tearDown(void)
{
    free(dut_struct);
}

void test_lcdinitcallsfunctionsinorder(void)
{

    lcd_command_Expect(0x28);
    delay_Expect(5);
    lcd_command_Expect(0x28);
    delay_Expect(100);
    lcd_command_Expect(0x28);
    delay_Expect(100);
    lcd_command_Expect(0x28);
    delay_Expect(100);
    printf("Function_set: %#03x\n", dut_struct->function_set);


    lcd_init(dut_struct);
    // TEST_IGNORE_MESSAGE("Ignore me");
}
`
@mvandervoord  and @mkarlesky Is this the correct way to testing the sequence of function calls 
:-)
I would like to know if I am on the correct track or if I am getting the fundamentals entirely wrong.

Thanks in advance!!

**Comment by mvandervoord** [comment]
yes, this is the right track. When there is a module "A" that makes calls to other modules "B" and "C", it is useful to mock the header files for B and C in order to test A. In your case, the bsp.h contains your "external" functions that you want to mock. :)

**Comment by krish2487** [comment]
Thank you :-). A regular dependancy is farly straightforward. I did have my doubts about mocking functions passed as structure members.. turns out, its the same.. :-)

If I can trouble you for a little insight and suggestions.. Is this a good way of dependancy injection??
abstracting away most of the hardware specific details and making a generic library that does not depend on the hardware but only on whats passed to it..

**Comment by mvandervoord** [comment]
yes, **YES** (I can't make that seconds YES big enough!).

Creating a header to abstract away dependencies is an excellent way to go. It's good for mocking away hardware and large complex API's (like for an RTOS or a file system), instead of needing to following the giant trail of ALL the headers that might get included!

**Comment by krish2487** [comment]
Thank you!! :-) Thats so much more reassuring.. 

(PS: Eagerly waiting for the next installment of the udemy course..)
