### ISSUE TITLE
fatal error: @@@@unity.h: No such file or directory

### ISSUE THREAD

**Issue by dwviel** [ThrowTheSwitch/Ceedling#342]
When I run a test it works the first time.  Then if I run it again it fails with the error:
../UnitTest/build/temp/_test_simple_nmea.c:2:10: fatal error: @@@@unity.h: No such file or directory
#include "@@@@uinity.h"

If I first delete the build/temp dir then it works fine.

The UnitTest directory is under the source directory that holds the files with code to be tested.
The only change that I made to the project.yml to make this work is the source path.

From:
:paths:
  :source:
    - src/**  

To:
:paths:
  :source:
    - ../**

The tests worked repeatedly when I keep the original src/** dir structure with the source files in that dir.

I tried adding
:clobber: TRUE in several places to try to force ceedling to remove the /test dir but this had no effect.

**Comment by mvandervoord** [comment]
This bug is already on our list of things to fix. To work around it for now, disable the preprocessing by setting:

```
:project:
  :use_test_preprocessor: FALSE
```

We are hoping to have this issue fixed very soon.
