### ISSUE TITLE
[Question] Order of evaluation of function arguments

### ISSUE THREAD

**Issue by joel-felcana** [ThrowTheSwitch/Ceedling#347]
Hi!

We were using ceedling to unit test a piece of code that looked something like this:

```c

void function_under_test(void) {
   foo(calculate_param_1(), calculate_param_2);
}
```

Our test was
```c
calculater_param_1_ExpectAndReturn(1);
calculater_param_2_ExpectAndReturn(2);
function_under_test();
```

The test failed, as it was saying that `calculater_param_2()` was called earlier than expected. After some head scratching, we tried to get the results of both calculate_param_X() functions in temp variables and use those in the call to foo() and the test worked. We asked around and a colleague suggested that it might be an undefined behaviour of C, and it seems that it's indeed the case ([link](https://stackoverflow.com/questions/376278/parameter-evaluation-order-before-a-function-calling-in-c))

Now, being an undefined behaviour of the language, I wouldn't expect a definitive answer from your side other than "make sure they are called in the right order, then", but I was wondering how to act in this type of scenarios.

**Comment by mvandervoord** [comment]
Unfortunately you only have two options, both of which aren't great:

(1) You can do as you did: break them into separate calls so you are in control.
(2) Turn off `:enforce_strict_ordering` in cmock, so that the order of the calls no longer matters. Unfortunately this is a universal setting and effects more than this one test.

**Comment by joel-felcana** [comment]
Thanks for replying. Yeah, 2) might be too extreme, we'll have to settle with 1)

Thanks!
