### ISSUE TITLE
Errors when testing using esp32

### ISSUE THREAD

**Issue by coolcodehere** [ThrowTheSwitch/Ceedling#349]
Error Dump: https://pastebin.com/7rgBtkDX

I'm currently trying to enable testing using ceedling with my ESP32 project but when I use the `ceedling` command I get the bulk of errors shown above. I read somewhere I may need to specify my toolchain in `project.yml` since the esp framework uses a separate toolchain. 

Any advice on this is appreciated.

**Comment by Letme** [comment]
Your project.yml would be useful. If you want to run on target then you need to add a tool chain, otherwise you will run on your comouter which just requires gcc or clang. Efm has a library which you will need to include and you will need to add a efm32mock.h file where you will redefine absolute memory addresses as global variables. Then you add a define protected include and add a define to compilation to select that header file when you compile for computer.

**Comment by coolcodehere** [comment]
I've updated the toolchain but have a new error: 

```
1 warning generated.
Compiling test_gps_runner.c...
rake aborted!
Errno::ENOENT: No such file or directory - args.exe
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/system_wrapper.rb:17:in `module_eval'
(eval):1:in `module_eval'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/system_wrapper.rb:17:in `module_eval'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/system_wrapper.rb:17:in `module_eval'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/tool_executor.rb:160:in `expandify_element'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/tool_executor.rb:107:in `block in build_arguments'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/tool_executor.rb:101:in `each'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/tool_executor.rb:101:in `build_arguments'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/tool_executor.rb:36:in `build_command_line'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/generator.rb:88:in `generate_object_file'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/rules_tests.rake:17:in `block in <top (required)>'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/task_invoker.rb:80:in `block in invoke_test_objects'
/Users/william/projects/ceedling/hub/vendor/ceedling/lib/ceedling/par_map.rb:10:in `block (2 levels) in par_map'
Tasks: TOP => build/test/out/c/test_gps_runner.o
(See full trace by running task with --trace)
```
Here's my project.yml: https://pastebin.com/d0mPmSxa

**Comment by Letme** [comment]
Like I said.do you intend to run this on target? Because unless your linux is running on efm32 you are compiling apples but running peaches.

**Comment by coolcodehere** [comment]
Yes, I do want to run on target but I'm not sure how to go about doing that.
