### ISSUE TITLE
[Feature Request] Mocks for internal functions

### ISSUE THREAD

**Issue by e153rd** [ThrowTheSwitch/Ceedling#354]
I would like to mock functions that are not defined in a header file, and are (thus) only implemented in the C file. 

Example of private functions defined in file event_dispatcher.c:

static void CreateEventDispatcherMutex(void);
static void CreateEventDispatcherQueue(void);
static void CreateEventDispatcherTask(void);
static void EventDispatcher_TaskFunction(void * pvParameters);

Even though the functions above would only be testable through a behaviour-driven test style, they´re still relevant to (unit) test.
Example of public functions defined in file event_dispatcher.h:

void InitEventDispatcher(void);
void AddNewEventListener(enum EventType eventType, EventListener listener);
//static void CreateEventDispatcherTask(void);
void FireEvent(enum EventType eventType, struct EventDataType* pNewEventData, PostEventCallback postEventCallback);

current extremely ugly unsafe and unrecommended workaround we employ in our test environment:

#ifdef TEST
static void CreateEventDispatcherMutex(void);
static void CreateEventDispatcherQueue(void);
static void CreateEventDispatcherTask(void);
static void EventDispatcher_TaskFunction(void * pvParameters);
#endif

I´ve managed to find a thread on this topic in your forums [here](https://groups.google.com/forum/embed/?place=forum/throwtheswitch&showsearch=true&showpopout=true&showtabs=true&hideforumtitle=true&parenturl=http%3A%2F%2Fwww.throwtheswitch.org%2Fforums#!searchin/throwtheswitch/internal$20functions/throwtheswitch/N9OZaFS9C6Q/lGnsXTyCBQAJ).

But have you by any chance gotten to work on it?
(Or the alternative, [plugin creation](https://groups.google.com/forum/embed/?place=forum/throwtheswitch&showsearch=true&showpopout=true&showtabs=true&hideforumtitle=true&parenturl=http%3A%2F%2Fwww.throwtheswitch.org%2Fforums#!searchin/throwtheswitch/internal$20functions/throwtheswitch/srp8mFWVJXA/ELSNEUkwG1cJ)?

Love Ceedling/Unity/CMock by the way, thanks for the great work and keep it up!

**Comment by Letme** [comment]
Did you check: https://github.com/ThrowTheSwitch/CMock/issues/161 ?
Sounds like you should have a `STATIC` in front and then you can guard it with TEST variable or put them in separate header like `libname_private.h`

**Comment by e153rd** [comment]
> Did you check: [ThrowTheSwitch/CMock#161](https://github.com/ThrowTheSwitch/CMock/issues/161) ?
> Sounds like you should have a `STATIC` in front and then you can guard it with TEST variable or put them in separate header like `libname_private.h`

Hi Letme,

Yes, I will try it out and I suspect it´ll amount to the same thing functionally.

If it doesn´t I´ll scribble a comment in this issue and/or reopen it.
