### ISSUE TITLE
Multiple definitions of variable in file.o and test_file.o

### ISSUE THREAD

**Issue by larshei** [ThrowTheSwitch/Ceedling#355]
Hello,

I am currently running into failed linking on trying to run a test on a module.

The module is meant to store logs on an embedded system in very limited amount of external memory, therefore just an error ID, a value (to make sure we can store variable content) with a type and a timestamp shall be stored. The error messages themselves will be part of the firmware, a structure holding the error code and the error message is used to make sure the error message and error id are assigned correctly.

The module is pretty basic so far, as I cannot get the tests to run. Here are the test output, the modules header and c files, a user config file (the user=programmer configures error codes and error messages) and the test file.

Test Output
---
    Test 'test_logging.c'
    ---------------------
    Generating runner for test_logging.c...
    Compiling test_logging_runner.c...
    Compiling test_logging.c...
    Compiling unity.c...
    Compiling logging.c...
    Compiling cmock.c...
    Linking test_logging.out...
    build/test/out/c/logging.o:logging.c:(.data+0x0): multiple definition of `log_entry_array'
    build/test/out/c/test_logging.o:test_logging.c:(.data+0x0): first defined here

C file
---
Veyr simple file, just one function.

    #include "logging.h"
    LogBuffer_typDef logBuffer;
    
    LogBuffer_typDef * log_get_buffer ( void ) {
        return &logBuffer;
    } 

H file
---
This file includes a user config header file and defines some structs.
A define for the user creates a type for log entries and an array holding these entries.

    #ifndef _LOGGING_H
    #define _LOGGING_H

    /*******************************************************************************
    * Includes
    *******************************************************************************/
    // logging_messages.h is included at the end
    #include "stdint.h"
    /*******************************************************************************
    * Defines
    *******************************************************************************/
    #define LOG_BUFFER_SIZE 5

    /*******************************************************************************
    * Types and Typedefs
    *******************************************************************************/
    typedef struct LogBuffer {
        unsigned            read;
        unsigned            write;
        LogStore_TypDef     entries[LOG_BUFFER_SIZE];
    } LogBuffer_typDef;

    /*******************************************************************************
    * Function Prototypes
    *******************************************************************************/
    LogBuffer_typDef * log_get_buffer ( void );

    /*******************************************************************************
    * Main definition for user
    *******************************************************************************/
    #define LOG_MESSAGES(...)                   \
    typedef struct LogMessage_TypDef {          \
        int         iErrorCode;                 \
        uint8_t     uiType;                     \
        char*       pcMessage;                  \
    } LogMessage_TypDef;                        \
                                                \
                                                \
    LogMessage_TypDef log_entry_array[] = {     \
        __VA_ARGS__                             \
    };

    #include "logging_messages.h"
    #endif // _LOGGING_H

H user file
---
    #ifndef _LOGGING_MESSAGES_H
    #define _LOGGING_MESSAGES_H
    
    typedef enum LogErrorCode {
        ER_TEST1,
        ER_TEST2
    } error_codes_t;
    
    LOG_MESSAGES (
        { ER_TEST1, INT32, "Test Error Message 1" },
        { ER_TEST2, FLOAT, "Test Error Message 2" }
    );
    #endif

Test File
---

    #include "unity.h"
    #include "logging.h"
    
    LogBuffer_typDef * logBuffer;
    
    void setUp(void)
    {
        logBuffer = log_get_buffer ();
    }
    
    void tearDown(void)
    {
    }
    
    void test_logging_Read_Write_Zero_after_Setup(void)
    {
        TEST_ASSERT_EQUAL (0        , logBuffer->read);
        TEST_ASSERT_EQUAL (0        , logBuffer->write);
    }

**Comment by mvandervoord** [comment]
Both your test and your source module include `logging.h` which means they both include `logging_messages.h` by proxy. Both times `logging_messages.h` is included, it runs into your `LOG_MESSAGES` macro which declares an instance of `log_entry_array`. Therefore, when you go to link, you have two copies of this structure.

This isn't a problem specific to testing. You will run into the exact same problem if you have two release modules like `logging.c` and `main.c` that both include `logging.h`. 

The fix is to make sure that `LOG_MESSAGES` gets called only once. One possible solution would be to include `logging_messages.h` only from `logging.c` and instead have `extern LogMessage_TypDef log_entry_array[]` in `logging.h`.

Most any other option for making sure a variable is declared only once will also work.

**Comment by larshei** [comment]
Thanks for the quick response! 

You are right, I overlooked this. Thank you very much. If you like, you may just remove the issue, as it is not ceedling specific at all.

**Comment by mvandervoord** [comment]
No problem at all. While we wish Ceedling could automatically detect all possible C problems, it's still dependent on the basic C language. :)
