### ISSUE TITLE
Issue linking libraries

### ISSUE THREAD

**Issue by IvanRibakov** [ThrowTheSwitch/Ceedling#356]
I'm attempting to integrate Ceedling into an existing project with the following folder structure:

```
/path/to/project-wrapper
`-- src
    `-- path/to/project  // required due to the fact that actual project is a "plugin" for another software so need to maintain specific "wrapper" folder structure.
        |                // actual source code being tested by Ceedling resides in /path/to/project-wrapper/src/path/to/project.
        |-- reqs         
        |   |-- include
        |   `-- libs
        |-- src
        |    `-- ...  
        |-- test
        |   |-- suites  // current unit tests (Unity + CMake)
        |   |-- ceedling  // folder for new Ceedling tests
        |   `-- support  
        `-- project.yml
```

To validate the Ceedling setup I created a dummy test `test/ceedling/test_tables_dummy.c` with following includes:

```
#include "unity.h"
#include "../reqs/include/collectc/hashtable.h"
#include "storage/collection/map.h"
#include "storage/collection/map_sk.h"
#include "storage/models/my_model.h"
#include "storage/table/tables.h"

void setUp(void) {...}
void tearDown(void) {...}
void test_dummy(void) {...}
```

Here, code under test is `storage/table/tables.h` with the rest of includes being dependencies.

However, when I attempt to execute this test, I get the following linker-related error:

```
Test 'test_table_dummy.c'
-------------------------
Generating runner for test_table_dummy.c...
Compiling test_table_dummy_runner.c...
Compiling test_table_dummy.c...
Compiling unity.c...
Compiling map.c...
Compiling map_sk.c...
Compiling my_model.c...
Compiling tables.c...
Compiling cmock.c...
Linking test_table_dummy.out...
build_test/test/out/c/map.o: In function `initConfig':
/path/to/project-wrapper/src/path/to/project/src/storage/collection/map.c:42: undefined reference to `hashtable_conf_init'
...
<many more "undefined reference" errors>
...
collect2: error: ld returned 1 exit status
ERROR: Shell command failed.
> Shell executed command:
'gcc "build_test/test/out/c/test_table_dummy_runner.o" "build_test/test/out/c/test_table_dummy.o" "build_test/test/out/c/unity.o" "build_test/test/out/c/map.o" "build_test/test/out/c/map_sk.o" "build_test/test/out/c/subscription_model.o" "build_test/test/out/c/tables.o" "build_test/test/out/c/cmock.o" -o "build_test/test/out/test_table_dummy.out"'
> And exited with status: [1].
```

Above mentioned function `hashtable_conf_init` is defined in `../reqs/include/collectc/hashtable.h` (that is included by `map.h`) and provided by the library `../reqs/lib/libcollectc.so`

In the project.yml I have specified path to the library headers and to the library itself:

```
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build_test
#  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :default_tasks:
    - test:all

#:release_build:
#  :output: MyApp.out
#  :use_assembly: FALSE

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:reqs/include/**
    - +:test/ceedling/**
    - -:test/support
  :source:
    - +:reqs/include/**
    - +:../../../core/**
    - src/**
  :support:
    - test/support

:libraries:
  :placement: :end
  :flag: "${1}"  # or "-L ${1}" for example
  :common: &common_libraries []
  :test:
    - *common_libraries
    - reqs/lib/**
  :release:
    - *common_libraries
```

Any ideas what might be causing linking issues in this scenario? I wonder if non-standard project folder (with wrapper folder structure) might be at play here.

**Comment by IvanRibakov** [comment]
I attempted to run tests with verbose output: `ceedling verbosity[4] test:all` but I still can't see libraries from `reqs/lib` folder being referenced at any point.

I've also tried changing `:flag: "${1}"` to `:flag: "-L ${1}"` in the library configuration block inside project.yml but to no success.

**Comment by mvandervoord** [comment]
I don't believe there is any wildcard support for libraries.

**Comment by IvanRibakov** [comment]
@mvandervoord thanks for the tip! I wish there was some way to tell which sections of project.yml support wildcards or at least an error message from Ceedling along the lines of it not being able to find the specified library...

I updated the library configuration section to point to the specific .so file, but still can't see it being linked nor any message about Ceedling not being able to find the .so. 

```
:libraries:
  :placement: :end
  :flag: "-L ${1}"  # or "-L ${1}" for example
  :common: &common_libraries []
  :test:
    - *common_libraries
    - reqs/lib/libcollectc.so
  :release:
    - *common_libraries
```

Any thoughts?

**Comment by IvanRibakov** [comment]
For anyone else facing the same problem - check which Ceedling version are you on. `0.28.3` does not include PR https://github.com/ThrowTheSwitch/Ceedling/pull/306 which fixes issue with `:libraries:` configuration section not being used at all when linking tests. If at the time of reading this `0.28.3` is still the latest version available, then I believe your best bet is to build Ceedling from sources.

@mvandervoord Do you know if there are any plans to release new version of Ceedling any time soon?
