### ISSUE TITLE
Q: How does Ceedling select the actual sources for building a unit test executable?

### ISSUE THREAD

**Issue by petermbauer** [ThrowTheSwitch/Ceedling#357]
I am trying to accomplish what Ceedling does but with CMake to avoid having to deal with another "build system". Basically its about preventing the "multiple definitions" linker error.
Here is the scenario: In my test function `test_fun_A` i am calling `fun_A` which in turn calls `fun_B`, each function has their own `.h` and `.c` file.
`test_fun_A -> fun_A -> fun_B`
Whereas `fun_B` shall be mocked so i generate the `mock_B.h, .c` with CMock, include `mock_B.h` in the `test_fun_A.c` and add `mock_B.c` to the sources for building `test_fun_A.exe`.
What i did not get so far is how Ceedling treats the `fun_B.c` file in this scenario. If it would be included in the build this would result in a "multiple definition" linker error as `fun_B` is also defined in the mocked .c file. Or does it use some compiler/linker trick?
If Ceedling excludes the original .c file from the build, how does it identify the files to exclude? Does it simply expect that there is a `B.c` to exclude due to the `#include `mock_B.h`?

My approach so far was to create a library from all the "code under test" so the `A.c` and `B.c` files in this example and then link the actual test executable against this library. This worked for all tests written so far which are similar to the example but now there is a new one which is also similar but i am running into the linker error now and would like to understand why it worked for the other tests but not for the new one.

**Comment by mvandervoord** [comment]
Ceedling builds an executable for each unit test. It can then link to just the things in needs. In your example above, that means linking mock_B.c but not B.c when testing A.

**Comment by petermbauer** [comment]
Thank you for the quick response!
So Ceedling just expects the file to be named `B.c`, otherwise it would not work?

**Comment by mvandervoord** [comment]
Ceedling knows that if your test includes "A.h", it will look for a file name "A.c" and add it to the link list if it exists. If it doesn't exist... no biggie. It moves on. If it comes across something like "mock_B.h", then it knows it needs to find "B.h" and generate a mock for it... it will then include that mock ("mock_B.c") into the final link list for that test.

So long as you don't include both the header AND the mock header directly (which is never necessary, as the mock header already includes the header for you), Ceedling won't generate a combination that will result in a multiple definition error.
