### ISSUE TITLE
optional .yml can replace project:build_root

### ISSUE THREAD

**Issue by glenntws** [ThrowTheSwitch/Ceedling#362]
Hello,

It's not possible to use a different build_root for each variant we are testing. This is very unfortunate, since we're using mutliple output paths for different variants.

right now, we have no other option than to manuall ycopy the results or (automatically) modify the project.yml. Both solutions are very bad.

Please add a fix for this, since this is a key feature when simultaneously testing multiple variations.

Thanks in advance,
Glenn

**Comment by mvandervoord** [comment]
Hi Glenn

Unless I am misunderstanding the problem you've encountered, it seems you want to run multiple project files? Each project file can specify its own build directory and you can run each as if it were a completely separate ceedling project (different paths, tools, defines, etc). You then specify which you are using like so:

```
ceedling project:version1 test:all
```

(where version1 matches one of your yaml files names version1.yml)

**Comment by glenntws** [comment]
Hey Mark :)

This indeed is a potential fix, but it's still a compromise. We have huge amounts of the project specification which stays equal and always copying the files is a lot of redundancy. It weould be enough, if build_root respects the build_root inside the options file.

Another problem: With up to 20 variants and more, we have a lot of project definitions in our root folder...

**Comment by mvandervoord** [comment]
Should work in the next release. :)
