### ISSUE TITLE
Force recompilation for tests with specific definitions

### ISSUE THREAD

**Issue by CezaryGapinski** [ThrowTheSwitch/Ceedling#369]
Hi,

I have legacy code with #ifdefs preprocessor inside the functions. I have found that ceedling has an option to set defines for specific test which looks really nice and can help me, but not when I use test:all option.

Here is a simple example.
Structure with my code looks like below:
```
| - src/driver.c
| - src/driver.h
| - test/test_driver_with_spec_feature.c
| - test/test_driver_without_spec_feature.c
|...
| - project.yml
```
driver.c file contains:
```
#include "driver.h"

unsigned int driver_foo(void)
{
  #ifdef SPEC_FEATURE
  return 1;
  #endif

  return 0;
}
```
driver.h:
```
#ifndef _DRIVER_H
#define _DRIVER_H

unsigned int driver_foo(void);

#endif // _DRIVER_H
```
test_driver_with_spec_feature.c:
```
#include "unity.h"
#include "driver.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_driver_NeedToImplement(void)
{
  TEST_ASSERT_EQUAL_UINT(1, driver_foo());
}
```
```
#include "unity.h"
#include "driver.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_driver_NeedToImplement(void)
{
  TEST_ASSERT_EQUAL_UINT(0, driver_foo());
}
```

project.yml is a default file generated by ceedling with added specific defines for the test_driver_with_spec_feature.c
```

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST
  :test_driver_with_spec_feature:
    - *common_defines
    - TEST
    - SPEC_FEATURE

```
When I was trying to run all tests, one of them always failed, because for the first test ceedling compiles driver.c file for some preprocessor definitions, and for the next test this file is not compiled again, therefore my function in driver.c doesn't behave what I'm expecting in second test.
```
Test 'test_driver_with_spec_feature.c'
--------------------------------------
 ************** Specific test definitions for test_driver_with_spec_feature !!! 
Generating runner for test_driver_with_spec_feature.c...
Compiling test_driver_with_spec_feature_runner.c...
Compiling test_driver_with_spec_feature.c...
Compiling unity.c...
Compiling driver.c...
Compiling cmock.c...
Linking test_driver_with_spec_feature.out...
Running test_driver_with_spec_feature.out...
 ************** Restored defines and build path


Test 'test_driver_without_spec_feature.c'
-----------------------------------------
Generating runner for test_driver_without_spec_feature.c...
Compiling test_driver_without_spec_feature_runner.c...
Compiling test_driver_without_spec_feature.c...
Linking test_driver_without_spec_feature.out...
Running test_driver_without_spec_feature.out...

-------------------
FAILED TEST SUMMARY
-------------------
[test_driver_without_spec_feature.c]
  Test: test_driver_NeedToImplement
  At line (14): "Expected 0 Was 1"

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  2
PASSED:  1
FAILED:  1
IGNORED: 0

---------------------
BUILD FAILURE SUMMARY
---------------------
Unit test failures.

```
I know I can use
`ceedling clobber test:driver_with_spec_feature`
and next
`ceedling clobber test:driver_without_spec_feature`
when I work on some specific parts in my function `driver_foo()`

But is it possible to force recompilation when I do the same with ceedling test:all?

**Comment by CezaryGapinski** [comment]
Hi again!

Based on my previous post I made some more investigation about what was causing the problem.

On my [branch](https://github.com/CezaryGapinski/Ceedling/commits/specific_preprocessor_defines_for_tests) I have added two commits. Preprocessor definitions for last compilation are stored in `cache/last_defines.txt` file and are compared with current definitions. When are different `force_build` file is added to rake tasks prerequisites.

But it is not sufficient to regenerate all files. When I have added second [commit](https://github.com/CezaryGapinski/Ceedling/commit/37496dc8d8600aa55c943159114253aac4413b64) where rake tasks are also reenabled before invoking then I obtain correct results of my tests.

If anybody wants to check how tests looks like, the example repository is here:

`git clone --recursive https://github.com/CezaryGapinski/multidefines_example.git`

Maybe it is be good to make something familiar in the master branch. I can make a PR if anybody interested or there is no better idea or explanation about current implementation?

There are still two more thinks which I cannot understand:
- why output files for specific test definitions are in separate subdirectories?
- what does the [line 80](https://github.com/CezaryGapinski/Ceedling/blob/486df116bac1d17ef7e94a82d461ef6cc2fa5ba4/lib/ceedling/test_invoker.rb#L88) when is just for the reading of the `test_config_changed` variable?

Nice to have some explanation from @methril about this changes for specific definitions in PR #198 ?

**Comment by pez3** [comment]
Hello...

it seems that i have exactly the same problem. from the output, it seems that ceedling does not rebuild the source file which contains my FUT with the new test specific define (the file heater.c)

is this problem still fixed or can i somehow force ceedling to rebuild?


greets peter

**Comment by Letme** [comment]
I always run `clobber` command for smaller builds when there are strange issues. That extra few seconds can really save some time in the longer term trying to figure out the problem.

**Comment by pez3** [comment]
Thank you @Letme and @CezaryGapinski  for your help!

Seems, that a `ceedling clobber` did the trick somehow for me...
lets see for how long :)

best regards!
peter
