### ISSUE TITLE
strlcpy is not defined

### ISSUE THREAD

**Issue by MikhailNatalenko** [ThrowTheSwitch/Ceedling#373]
Hello! I've got a stupid question. I want to use `strlcpy` but, CUnit says, it's not defined (I tried to include <string.h> with no effect). What should I do to use the same `strlcpy` as on platform I made code for.

**Comment by JuPrgn** [comment]
Hello ! 
It seems strlcpy is not standard I found this : https://stackoverflow.com/questions/18547251/when-i-use-strlcpy-function-in-c-the-compilor-give-me-an-error/18547336#18547336

Maybe you can configure your project to use the same compiler as the compiler you are using on your platform ? 

I am a newbie using Ceedling but I succeeded building a project to use microchip xc compilers. I can share some details if you need some help. 

Julien

**Comment by MikhailNatalenko** [comment]
No, I don't think it's possible. I compile the project for stm32 under Windows. The answer is how to add `strlcpy` requirements to the path that Ceedling uses.

**Comment by Letme** [comment]
I think that stackoverflow explains you nicely.  `-L<path to library>` , but if that has some stm32 assembly inside (or includes some assembly) then you will have a problem running it without simualtor (you did not mention where you want to run it).

You have few options. You can add it directly to your `:test_compiler:`/`:test_linker:` `:arguments:` in `:tools:` (the `-L` flag and `-l` ... i think there is example for math by adding `-lm` somewhere here), or you can abuse `:flags:` `:test:` :compile:`/`:link:` for that.

**Comment by MikhailNatalenko** [comment]
@Letme Thank you.
