### ISSUE TITLE
gcov cannot find source files

### ISSUE THREAD

**Issue by congtmbg** [ThrowTheSwitch/Ceedling#376]
Dear every body,
I want ask you about error "gcov cannot find source files" (urgent).
Can you feedback me soon, please?
I have unit_test folder is created by ceedling.

/src: include .so library, not include .h, .c files. These .so files were compiled by gcc for app/src.
/test: include test files.
In the project.yml file, I configured below:
 :include: 
     - ../../app/inc/**
//inc folder is not in unit test, inc folder include .h files.
//src folder is not in unit test, src folder include .c files.

I can type 'ceedling clobber', 'ceedling' to build unit test well.
But when i use gcovr -r . (in app/src/*.gcno; app/src/*.gcda; app/src/*.o; app/src/*.c), result report is 0%.
But when i use gcov -b -l -p -c *.gcno, i have error "gcov cannot find source files".
Can you tell me about solutions to fix that bug, please?
Thank you so much!

**Comment by congtmbg** [comment]
Add more information,
If I use lcov to generate html report from .gnco, .gcda files, i have problem which is  "WARNING: cannot find an entry for...(file .c)".

**Comment by gsmithufl** [comment]
Do you have `- gcov` in plugins -> enabled?

**Comment by congtmbg** [comment]
> Do you have `- gcov` added to project.yml under plugins enabled?

Yes, I do.
Below is config for - gcov:

:gcov_post_report:
  :executable: gcovr                                                      
  :optional: FALSE
  :arguments:
      # Exclude directories from search path that match this regular expression.
      - --exclude-directories='^\.launches.*|^\.settings.*|^asm.*|^debug.*|^doc.*|^inc.*|^src.*|^targetConfigs.*|^test.*|^test-build.*|^tools.*|^vendor.*'
      # Generate HTML output for source file coverage
      - --html-details
      # Print output to this filename. Used with --html-details results in <output-name>.<source-filename>.html
      - -r .
      - -o test-build/artifacts/gcov/coverage.html
:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - stdout_gtestlike_tests_report
    - module_generator
    - raw_output_report
    **- gcov**

**Comment by CezaryGapinski** [comment]
Hi,
I do not know exactly, but do you run gcc and gcov from the same directory, like it is mentioned in gcov [documentation](https://gcc.gnu.org/onlinedocs/gcc/Invoking-Gcov.html#Invoking-Gcov)?

> gcov should be run with the current directory the same as that when you invoked the compiler. Otherwise it will not be able to locate the source files. gcov produces files called mangledname.gcov in the current directory.

**Comment by congtmbg** [comment]
Dear every body,
I think root cause  of "gcov cannot find source files" issue is duplicate header file in paths.
So, Ceedling can't understand what is true path.
You can remove paths which are duplicated.
You can check duplicate header file via command:
ceedling files:header | grep "your_header_name.h"
