### ISSUE TITLE
command_hooks plugin executable array example invalid

### ISSUE THREAD

**Issue by EmanuelW** [ThrowTheSwitch/Ceedling#382]
The documentation suggests that the command_hooks plugin can take an array of executables for any given hook, as so:
```
:tools:
  :post_test:
    -  :executable: echo
       :arguments: "${1} was glorious!"
    -  :executable: echo
       :arguments:
         - it kinda made me cry a little.
         - you?

```

This seems useful (in my case I want to run objcopy twice) but when running the test command with this structure i get the following message:
```
Traceback (most recent call last):
	9: from /home/emanuel/.ruby/bin/ceedling:23:in `<main>'
	8: from /home/emanuel/.ruby/bin/ceedling:23:in `load'
	7: from /home/emanuel/.ruby/gems/ceedling-0.28.3/bin/ceedling:295:in `<top (required)>'
	6: from vendor/ceedling/lib/ceedling.rb:66:in `load_project'
	5: from vendor/ceedling/lib/ceedling.rb:66:in `load'
	4: from vendor/ceedling/lib/../lib/ceedling/rakefile.rb:48:in `<top (required)>'
	3: from /home/emanuel/workspace/ceedlingTest/brokenHook/vendor/ceedling/lib/ceedling/setupinator.rb:28:in `do_setup'
	2: from /home/emanuel/workspace/ceedlingTest/brokenHook/vendor/ceedling/lib/ceedling/configurator.rb:129:in `tools_setup'
	1: from /home/emanuel/workspace/ceedlingTest/brokenHook/vendor/ceedling/lib/ceedling/configurator.rb:129:in `each_key'
/home/emanuel/workspace/ceedlingTest/brokenHook/vendor/ceedling/lib/ceedling/configurator.rb:133:in `block in tools_setup': no implicit conversion of Symbol into Integer (TypeError)
```

I attach the project.yml file, it was created by:
- creating a clean "blinky" example
- adding command_hooks to the enabled plugins list
- pasting the example config from the command_hooks readme

This was done with the Ceedling version 0.28.3 but doing the same with the tip of the master branch creates the same result (but with the error on configurator.rb:135...)

[project_yaml.zip](https://github.com/ThrowTheSwitch/Ceedling/files/3515924/project_yaml.zip)

**Comment by mvandervoord** [comment]
Unfortunately you're just a victim of not being on the cutting edge. This feature is soon to be released.
