### ISSUE TITLE
[gcov plugin] Branch exclusion markers not working?

### ISSUE THREAD

**Issue by joel-felcana** [ThrowTheSwitch/Ceedling#384]
I'm using the gcov plugin to generate reports of test coverage.
I managed to mark areas of my code that won't be tested with the LCOV_EXCL_START and LCOV_EXCL_STOP succesfully (although the output of the command line doesn't show them as covered, the html report reports the correct number

![image](https://user-images.githubusercontent.com/46561171/63353219-54e0c380-c35a-11e9-8700-7ff1844117ee.png)

I'm trying to add the exclude branch markers to mark some "we won't get here" areas of the code (like the default case on a switch) but for the life of me I can't get it working. Is there something in gcov / lcov, or the gcov plugin that makes it ignore the branch exclusion markers?Could it be a versioning issue? Or am I using them wrong?

![image](https://user-images.githubusercontent.com/46561171/63353540-cfa9de80-c35a-11e9-9c8a-3729fc947c34.png)

Thanks!

**Comment by mvandervoord** [comment]
I'm afraid I haven't used any of these features in gcov yet and don't know the answer. @dpostorivo or @tobyjwebb -- do you know the answer?

**Comment by joel-felcana** [comment]
haha, thanks for the honesty 😆 
It's my first for me too, so not a 100% sure that I'm using them correctly, that's why I am asking

**Comment by dpostorivo** [comment]
I'd need to do more investigation on this. I've never done exclude branches like this before. It should be noted that gcovr is external coverage report generation you can find here:

https://github.com/gcovr/gcovr

Ceedling's gcov plugin should just run gcov or lcov so if those comments work if your coverage executable, it should be fine.

What coverage executable are you using and what version? If possible I'd also analyse the raw .gcda  or .gcno  or whatever is generated in build/gcov/out.

**Comment by tobyjwebb** [comment]
Sorry, I haven't used these features yet, either...

TW

**Comment by joel-felcana** [comment]
```
$ gcov --version
gcov (Rev2, Built by MSYS2 project) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or 
FITNESS FOR A PARTICULAR PURPOSE.

$ gcovr --version
gcovr 4.1

Copyright 2013-2018 the gcovr authors
Copyright 2013 Sandia Corporation
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
```

It appears that gcovr added the basic markers (LINE, START and STOP) in v3.8, but there's a ticket open for the _BR_ set of markers.

https://github.com/gcovr/gcovr/issues/121

So I might be wrong, but it seems that is a gcovr issue.

Regarding my first screenshot, which piece of code is responsible for showing the console output? Any ideas on why the coverage % is different than the one in the HTML report (which is the "correct" one)

**Comment by mundodisco8** [comment]
Hi!
Just a heads up. Gcovr has closed the ticket for the BR* markers (https://github.com/gcovr/gcovr/issues/121#event-7116069817) so I assume a new version with support for them will be released soon.

**Comment by Spacetown** [comment]
The branch exclusion markers are introduced into `gcovr` with https://github.com/gcovr/gcovr/pull/644. You can close this issue.
