### ISSUE TITLE
ceedling coverage report html could not show code

### ISSUE THREAD

**Issue by Cherish-Gww** [ThrowTheSwitch/Ceedling#387]
Hi
I found that if you don`t put your source code in ceedling project src directory,  the build/artifacts/gcov/GcovCoverageResults.html, could not show the code coverage.
My question is:
how can I show code coverage without copy my source code to ceedling project src directory?

**Comment by Letme** [comment]
How do you then generate coverage if the source code is not in src? Or you are claiming that src is hardcoded and that plugin does not respect `:source:` directive in yaml?

**Comment by Cherish-Gww** [comment]
@Letme 
I use path command for search test source code
:paths:
  :test:
    - +:/home/xxx//work/xxx/src/mm/tests/**
  :source:
    - +:/home/xxx//work/xxx/install_isolated/include/**
    - +:/home/xxx//work/xxx/src/mm/src/**

**Comment by Cherish-Gww** [comment]
Hi @Letme 
I use this command to generate my coverage test.
$ ceedling gcov:all utils:gcov
and I set:
```
:paths:
  :test:
    - +:/home/weig/work/work/SyriusGems/src/mm/tests/**
  :source:
    - +:/home/weig/work/xxx/xxx/install_isolated/include/**
    - +:/home/weig/work/xxx/xxx/src/mm/src/**

:gcov:
    :html_report_type: detailed
:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - gcov
    - xml_tests_report
    - stdout_gtestlike_tests_report
    - module_generator
    - raw_output_report
```

each project can generate a project.yml, this file include source directories, include directories, and test directories.

**Comment by Letme** [comment]
Based on above you are saying that there is somewhere src hardcoded in the generate html.

As a side note: I would not use the absolute paths anywhere as that is highly unportable and bad practice (will not work on CI or anywhere else).

**Comment by Cherish-Gww** [comment]
@Letme
Thank you very much, I will consider use soft link to link my source file to ceedling new project src directory.

**Comment by Letme** [comment]
That was far from my suggestion. Just switch to relative paths.

**Comment by Letme** [comment]
But based on what you write there might be a bug in the plugin, but my ruby is non-existent to do a decent debug of it

**Comment by Cherish-Gww** [comment]
@Letme 
Thank you very much.
I will learn ruby, find out what happend, 
and I think use soft link of directory maybe a better way.

**Comment by Cherish-Gww** [comment]
Hi @Letme 
I have found solution, gcovr.rake use default.yml, this file need deliver parameter to gcovr. here is my suggest:
https://github.com/ThrowTheSwitch/Ceedling/issues/392
