### ISSUE TITLE
local variable in unit test

### ISSUE THREAD

**Issue by congtmbg** [ThrowTheSwitch/Ceedling#390]
Dear every body,
I have issue about local variable which is below:
I have function check_task_1, check_task_2.
**int check_task_1(int *value){//in file1.h, file1.c.**
	//to do something about value, will change value of 'value' variable.
	return 0;
}
**int check_task_2(void){//in file2.h, file2.c, include "file1.h". Can mock file1.h**
	int ret = -1;
	int count = 0;//local variable
	ret = check_task_1(&count);//how to mock to change value of 'count' variable?
	if(ret == 0){
	    if(count > 0){
			if(count == 1){
				return 10;
			}
			if(count == 2){
				return 20;
			}
			if(count == 3){
				return 30;
			}
			if(count == 4){
				//to do something
			}
		}
    }else{
    	return -1;
    }
	return 0;
}
Can you make example unit test for check_task_2() function, change value of 'count' variable to  1 or 2 or 3 or 4, please?
Thank you so much!

**Comment by congtmbg** [comment]
I hope I can get feedback from every body as soon as.
Thank you.

**Comment by Letme** [comment]
Can you use proper styling? This is a bit hard to comprehend how `int value` can change the variable of value (i assume its `int *value` since you call it as pointer below).

Check_task_1 will be mocked if you include `mock_file1.h` and then you can return thru Ptr and stuff like that (refer to cmock documentation).

**Comment by congtmbg** [comment]
Dear Letme,
I have just check line of code above.
`check_task_1(int *value){// input is int poiter, not int value.
//in file1.h, file1.c.
//to do something about value, will change value of 'value' variable.
*value = *value + 2;//example.
return 0;
}
int check_task_2(void){//in file2.h, file2.c, include "file1.h". Can mock file1.h
int ret = -1;
int count = 0;//local variable
ret = check_task_1(&count);//how to mock to change value of 'count' variable?
if(ret == 0){
if(count > 0){
if(count == 1){
return 10;
}
if(count == 2){
return 20;
}
if(count == 3){
return 30;
}
if(count == 4){
//to do something
}
}
}else{
return -1;
}
return 0;
}
`

Can you make example unit test for check_task_2() function, change value of 'count' variable, please?
I will refer.
I think it is the fast way which i can understand.
Step 1:?
Step 2:?
...
After that, I make unit test for many functions in my source code.
Thank you.

**Comment by mvandervoord** [comment]
Hi. 

As @Letme mentioned, it's very hard to read your example, @congtmbg . In the future, if you put a line with three backticks only, then your code example, and then another line with three backticks, it will preserve all your spacing when pasting code examples onto this forum. 

ANYWAY

I think I have figured out what you are asking. You have a local variable 'count' which is supposed to get updated by the function that is currently being mocked. How do you test it and how do you control what's getting updated?

Simplified, it looks like this:

```
int check_task_2(void) {
    int ret = -1;
    int count = 0; //local variable

    ret = check_task_1(&count); //how to mock to change value of 'count' variable?

    // and so on... the rest of the code uses both count and ret to determine what to do.
}
```

To test this, we might do something like this:

```
#include "unity.h"
#include "file2.h"
#include "mock_file1.h"

void test_check_task_2_SHOULD_return_10_if_count_1_and_return_okay(void)
{
    check_task_1_ExpectAndReturn(0, 0); // See note 1
    check_task_1_ReturnThruPtr_value(1); // See note 2

    TEST_ASSERT_EQUAL_INT(10, check_task_2());
}
```

Some notes:

note 1: This line says that we expect that `check_task_1` will get called once. When it is called, it should be called with a 0 for `value`. When finished, it should return 0 as it's return value.

If we DO NOT care about what `value` is at the time `check_task_1` is called, we could instead call `check_task_1_ExpectAnyArgsAndReturn(0);` which doesn't check any arguments... it just sets the return value.

note 2: When this is added after an expectation, it modifies the previous call to say that WHEN `check_task_1` is called, it should FILL IN `value` to be whatever we specify here (in this case 1). 

By the time we call the real function under test, it should do these calculations and return a 10.

Final note: to use either of these features, you need to enable the plugin for them in your project file:

``` 
:cmock:
    :plugins:
        - expect_any_args
        - return_thru_ptr
```

I hope this helps! Best of luck!
