### ISSUE TITLE
include object files during custom Compile/Linking 

### ISSUE THREAD

**Issue by krishnaharik** [ThrowTheSwitch/Ceedling#393]
Hello Everyone,

how to include object files of the other source files. in project.yml file.
i have tried in different methods but not useful.

Path of the Obj files
C:/EET_ASCU2/EET_ASCU_Gen_II/SW/Basisentwicklung/branches/FuncParaToFlash_0.0.0/Program/Appl/obj/
Have 200+ object files need to add.

Targer RH850 Renesas controller.

Any suggestions please.

---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: FALSE
  :test_file_prefix: test_
  :which_ceedling: vendor/ceedling
  :default_tasks:
    - test:all

#:release_build:
#  :output: ProtoA.elf
#  :use_assembly: FALSE
#  :artifacts:
#    - build/release/out/c/ProtoA.hex

:environment:

:extension:
  :executable: .out
  #:executable: .elf

:paths:
  :test:
    - +:test/**
    - -:test/support
  :support:
    - test/support
  :source:
    #- src/**
    - C:\Project\UnitTest\EET_Modules\ADC_Mng\Module
  :include:
    - include/**
    - C:\EET_ASCU2\EET_ASCU_Gen_II\SW\Basisentwicklung\branches\FuncParaToFlash_0.0.0\Tools\SIP_Package\BSW\Os
    - C:\EET_ASCU2\EET_ASCU_Gen_II\SW\Basisentwicklung\branches\FuncParaToFlash_0.0.0\Tools\SIP_Package\BSW\Com
    - C:\EET_ASCU2\EET_ASCU_Gen_II\SW\Basisentwicklung\branches\FuncParaToFlash_0.0.0\Tools\SIP_Package\BSW\Det
    - C:\EET_ASCU2\EET_ASCU_Gen_II\SW\Basisentwicklung\branches\FuncParaToFlash_0.0.0\Tools\SIP_Package\BSW\Vstdlib
    - C:\EET_ASCU2\EET_ASCU_Gen_II\SW\Basisentwicklung\branches\FuncParaToFlash_0.0.0\Tools\SIP_Package\BSW\_Common
    - C:\EET_ASCU2\EET_ASCU_Gen_II\SW\Basisentwicklung\branches\FuncParaToFlash_0.0.0\Tools\SIP_Package\ThirdParty\Mcal_Rh850F1x\Supply\ASR_RH850_F1KM_42.02.00\X1X\common_platform\generic\compiler\common\ghs\include
    - C:\EET_ASCU2\EET_ASCU_Gen_II\SW\Basisentwicklung\branches\FuncParaToFlash_0.0.0\Program\Appl\GenData
    - C:\EET_ASCU2\EET_ASCU_Gen_II\SW\Basisentwicklung\branches\FuncParaToFlash_0.0.0\Program\Appl\Include
    - C:\Project\UnitTest\EET_Modules\ASCU2_Mng\Module
    - C:\Project\UnitTest\EET_Modules\ADC_Mng\Module
    - C:\Project\UnitTest\EET_Modules\Common_Files
    - C:\Project\UnitTest\EET_Modules\DataFlash_Mng\Module
    - C:\Project\UnitTest\EET_Modules\ECU_Info_Mng\Module
    - C:\Project\UnitTest\EET_Modules\EetInit_Mng\Module
    - C:\Project\UnitTest\EET_Modules\RDC_Estimation\Module
    - C:\Project\UnitTest\EET_Modules\ANC_Core\Module\AncHeader
    - C:\Project\UnitTest\EET_Modules\RdeM_Mng\Module
    - C:\Project\UnitTest\EET_Modules\CanParameterInterface_Mng\Module

  :custom:
    - C:/EET_ASCU2/EET_ASCU_Gen_II/SW/Basisentwicklung/branches/FuncParaToFlash_0.0.0/Program/Appl/obj/  # external paths

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines #[]
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:gcov:
    :html_report_type: detailed

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "${1}"  # or "-L ${1}" for example
  :common: &common_libraries []
  :test:
    - *common_libraries
  :release:
    - *common_libraries

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
  :verbosity: 4

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    #- stdout_pretty_tests_report
    - stdout_gtestlike_tests_report
    - module_generator
    - raw_output_report
    - xml_tests_report
    - gcov

PROJECT_OBJ_ROOT:  "C:/EET_ASCU2/EET_ASCU_Gen_II/SW/Basisentwicklung/branches/FuncParaToFlash_0.0.0/Program/Appl/obj/"
    
:tools:
  :test_compiler:
     :executable: C:\ghs\comp_201517\ccrh850.exe              #exists in system search path
     :name: 'ghs test compiler'
     :arguments:
        - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE               #expands to -I search paths
        - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR   #expands to -I search paths
        - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR  #expands to all -D defined symbols
        #- --network-license             #simple command line argument
        #- -optimize-level 4             #simple command line argument
        #- "#{`args.exe -m acme.prj`}"   #in-line ruby sub to shell out & build string of arguments
        - -c ${1}                       #source code input file (Ruby method call param list sub)
        - -o ${2}                       #object file output (Ruby method call param list sub)
        - -c                                    
        - -Osize                                
        - -g                                    
        - -cpu=rh850g3kh                        
        - -gsize                                
        - -prepare_dispose                      
        - -inline_prologue                      
        - -sda=all                              
        - -Wundef                               
        - -no_callt                             
        - -reserve_r2                           
        - --short_enum                          
        - --prototype_errors                    
        - --diag_error 193                      
        - -dual_debug                           
        - -large_sda                            
        - --no_commons                          
        - -shorten_loads                        
        - -shorten_moves                        
        - -Wshadow                              
        - -nofloatio                            
        - -ignore_callt_state_in_interrupts     
        - -delete
        
  :test_linker:
     :executable: C:\ghs\comp_201517\ccrh850.exe    #absolute file path
     :name: 'ghs test linker'
     :arguments:
        #- C:\Project\UnitTest\test\AscuTaskM.o
        #- -I PROJECT_OBJ_ROOT               #expands to -I search paths
        - ${1}             #list of object files to link (Ruby method call param list sub)
        - -o ${2}            #executable file output (Ruby method call param list sub)
        - -Osize                                
        - -g                                    
        - -cpu=rh850g3kh                        
        - -gsize                                
        - -prepare_dispose                      
        - -inline_prologue                      
        - -sda=all                              
        - -Wundef                               
        - -no_callt                             
        - -reserve_r2                           
        - --short_enum                          
        - --prototype_errors                    
        - --diag_error 193                      
        - -dual_debug                           
        - -large_sda                            
        - --no_commons                          
        - -shorten_loads                        
        - -shorten_moves                        
        - -Wshadow                              
        - -nofloatio                            
        - -ignore_callt_state_in_interrupts     
        - -delete
  :test_fixture:
     :executable: C:\ghs\multi_616\850eserv2.exe #C:\ghs\comp_201517\sim850.exe  #relative file path to command line simulator
     :name: 'ghs test fixture'
     #:stderr_redirect: :auto                     #inform Ceedling what model of $stderr capture to use
     :arguments:
        - -fastflashload 
        - -rh850 
        - -e1lpd4=11000 
        - -dclock=16000,0,swoff 
        - -df=C:\ghs\comp_201517\rh850\DR7F701684.dvf 
        - -id ffffffffffffffffffffffffffffffff 
        - -noiop     

Kind regards
Hari.

**Comment by mvandervoord** [comment]
Hi

I'm not sure exactly what the issue is that you've run into. It sounds like maybe you're thinking you need to build everything at once? This isn't the case. In unit testing C, we build a single test module at a time (often with mocks to stub out the rest of the system). That module is tested, and then it moves on to the next module.

Because of the nature of separating each of the modules from one another, Ceedling doesn't build all the objects together except for in the release (in which case, pointing it at the source files will be sufficient).

If this isn't your actual question, feel free to reopen this issue and ask again.
