### ISSUE TITLE
Add Boilerplate template files as an option to Module Generator

### ISSUE THREAD

**Issue by serjche** [ThrowTheSwitch/Ceedling#395]
Hi,

This is my first time contributing to the project, I've been using Ceedling extensively for a month or so, and I'm just gonna say it is the best unit test framework for C out there.

So anyway, working through it I've been thinking of a couple of new features to add to the project, the first being the ability to specify the boilerplate code or header comments in the module_generator.

The idea comes from: https://spin.atomicobject.com/2013/10/02/ceedling-module-generator/
which sort of explains how to define custom templates for module genertation by manually adding a custom plugin locally.

But I say, why not add it as part of the options in the configuration?

I've been digging through the code and seeing that the **:boilerplates:** option in **:module_geneator:** is not documented at all. I tried adding in the main **config.yml** an option as follows:
```yml
:module_generator:
  :boilerplates:
    :src: '/* This is Boilerplate code. */'
```

And using the command **ceedling module:create[foo]** it creates the source module as follows:

```c
/* This is Boilerplate code. */
#include "foo.h"
```

It would be the same for **:tst:** and **:inc:** adding its respective options.

I've made a small change in module_generator.rb to include a new option called :boilerplate_files: which can be defined in the **:module_generator:** options in **config.yml** following the same structure as **:boilerplates:**.

```ruby
def divine_options(optz={})
```
...
```ruby
    if (defined? MODULE_GENERATOR_BOILERPLATE_FILES)

      bf = MODULE_GENERATOR_BOILERPLATE_FILES

      if !bf[:src].nil? && File.exists?(bf[:src]) 
        unity_generator_options[:boilerplates][:src] = File.read(bf[:src])
      end

      if !bf[:inc].nil? && File.exists?(bf[:inc]) 
        unity_generator_options[:boilerplates][:inc] = File.read(bf[:inc])
      end

      if !bf[:tst].nil? && File.exists?(bf[:tst]) 
        unity_generator_options[:boilerplates][:tst] = File.read(bf[:tst])
      end
    end
```
...
```ruby
end
```

You can see the commit here: https://github.com/serjche/Ceedling/commit/40d3aec952e4efcd77786b52134c2a30b0d113dc

It looks for the existance of the boilerplate filess and it just passes the same arguments to the UnityModuleGenerator class in genertate_module.rb, which already has the functionality for boilerplate, but I haven't seen any examples on how to use it, neither been utilized that much, if at all.

Then you should be able to add the following lines in **config.yml**:

```yml
:module_generator:
  :boilerplate_files:
    :src: '<template_folder>\src_boilerplate.txt'
    :inc: '<template_folder>\inc_boilerplate.txt'
    :tst: '<template_folder>\tst_boilerplate.txt'
```
For whatever file names in whichever folder you desire.

Also, the mentioned article touches on ERB template syntax, which would be very powerful in creating custom code, but my approach here is a lot simpler just for adding the header boilerplate comment in a file.

I'm making it simple for now, but it'd be actually very cool to leverage the ERB template to create custom modules, but that is a much bigger effort, at least for me that I'm just starting to learn Ruby (as a result of wanting to contribute to this project :) )

**Comment by mvandervoord** [comment]
I love this concept a lot. I agree that it would be awesome to improve it over time, but even in its current state, it's awesome. Thanks for the contribution and welcome to the team!

**Comment by serjche** [comment]
Wow that was a quick response, thanks for the support!

**Comment by mvandervoord** [comment]
I wish my responses were always that fast... but sadly we just got lucky this time. ;)

**Comment by serjche** [comment]
Probably because it's Sunday hehehe.
