### ISSUE TITLE
Unit tests do not compile if release build is enabled and release compiler not installed

### ISSUE THREAD

**Issue by 6arms1leg** [ThrowTheSwitch/Ceedling#397]
If release builds are enabled in Ceedling's `project.yml` (`:release_build:`) and a release compiler is defined

```yaml
:tools:
  :release_compiler:
    :executable: mycompiler
```

and that compiler is not installed (here "mycompiler") Ceedling fails to execute the unit tests with the following error (MS Windows):

```
C:/workspace/project> Ceedling test:all
ERROR: Config filepath [:tools][:release_assembler][:executable]['mycompiler'] does not exist in system search paths.
ERROR: Config filepath [:tools][:release_compiler][:executable]['mycompiler'] does not exist in system search paths.
ERROR: Config filepath [:tools][:release_linker][:executable]['mycompiler'] does not exist in system search paths.
Traceback (most recent call last):
        5: from vendor/ceedling/bin/ceedling:295:in `<main>'
        4: from vendor/ceedling/lib/ceedling.rb:66:in `load_project'
        3: from vendor/ceedling/lib/ceedling.rb:66:in `load'
        2: from vendor/ceedling/lib/../lib/ceedling/rakefile.rb:48:in `<top (required)>'
        1: from C:/workspace/project/vendor/ceedling/lib/ceedling/setupinator.rb:32:in `do_setup'
C:/workspace/project/vendor/ceedling/lib/ceedling/configurator.rb:287:in `validate': unhandled exception
```

**Note:**
The compilation options for unit tests are left at their default values and unit tests compile when the release compiler option is not set (or set to an existing compiler in `PATH`).
Also, Ceedling's release build itself works just fine (when the correct compiler is set).

Tried with Ceedling v0.28.3 (under GNU/Linux and MS Windows).

---

IMO, when running unit tests, Ceedling should ignore the release compiler settings completely and continue even if the release compiler does not exist in `PATH`.

Consider the following use case:
Unit tests and release builds are done with Ceedling on a local PC (which has both GCC for unit tests and a custom compiler for release builds installed) but unit tests are also run on a CI server that only has GCC for unit tests installed.
While everything works fine on the local PC, unit tests will not run on the CI server (unless the `project.yml` is modified beforehand).

**Comment by Letme** [comment]
I solved similar issue with targets.yml which have different tools defined. My CI is arm (rpi's), my pc is x86_64 and my target could be cortex or something even more exotic. 

But here I understand you have problem that if you do not specifiy test_compiler the release_compiler is used?

**Comment by 6arms1leg** [comment]
@Letme, thanks for your answer.

> But here I understand you have problem that if you do not specifiy test_compiler the release_compiler is used?

Not exactly. My project (including Ceedling and its `project.yml` file) is versioned with Git, which I push to my CI server. So both, my local PC and my CI server, use the same `project.yml`.
I didn't change any of the unit testing settings, I just added a `:release_compiler:` for my target.
With that setup I want to do unit tests *and* release builds on my local PC and *only* unit tests on the CI server.
On my local PC everything works fine but on the CI server Ceedling complains about the missing release compiler, although I only want to do unit tests.

It seems like Ceedling is always checking if all compilers are available, although for unit tests having only the unit test compiler installed would be sufficient.

To reproduce, just add the following to your `project.yml` (`mycompiler` can be anything that is not in your `PATH`):

```yml
:tools:
  :release_compiler:
    :executable: mycompiler
```

and run `Ceedling test:all`.

Thanks for your help!

**Comment by Letme** [comment]
It does indeed sound like a valid enhancement and I think my workaroubd for targets just bypassed this. I suspect this is a quickfix for mark or dom to obly check for compiler that is used. If yiu declare non existing unit-test compiler and try to build release- does it work? (I suspect it does)

**Comment by 6arms1leg** [comment]
@Letme,

> If yiu declare non existing unit-test compiler and try to build release- does it work? (I suspect it does)

It does not. The behavior is analogous: Setting

```yml
:tools:
  :test_compiler:
    :executable: mycompiler
```

and running `ceedling release` results in the same error (see initial post):

```
`ERROR: Config filepath [:tools][:test_compiler][:executable]['mycompiler'] does not exist in system search paths.
```

Tested under MS Windows with Ceedling v0.28.3.

**Comment by mvandervoord** [comment]
I'm going to fix this... but also you can specify any tool as `:optional: TRUE` to avoid this error. :)

**Comment by mvandervoord** [comment]
Hmmm. Not a simple thing. The command line tools are all validated long before Ceedling has decided what you've asked it to work on (and what the dependencies are, etc etc). Sticking with making the release tools optional might be the best way to go for now.

**Comment by 6arms1leg** [comment]
@mvandervoord,

thanks for your investigation!
That workaround solves the problem for me, although it might be preferable to fix this at some point.
I couldn't find `:optional: TRUE` in the docs, though. The documentation for Ceedling (and Unity, CMock, etc.) is quite good, but it would be really nice if it was complete.

Many thanks for your great work!

**Comment by mvandervoord** [comment]
I've added it to the documentation. Unless Ceedling goes through a major rewrite, this isn't an issue that is going to be fixed. So I'm closing this for now. People may continue to comment on it. If there is enough interest, we may consider reopening.
