### ISSUE TITLE
There should be a --help command for Ceedling:

### ISSUE THREAD

**Issue by michaelbadcrumble** [ThrowTheSwitch/Ceedling#399]
From my perspective, Ceedling should have a --help command to show the commands that can be used followed by options.  If possible a sub help for each command like `ceedling new --help` or `ceedling clear --help` should print the flags that can be passed for a new project.

**Comment by mvandervoord** [comment]
There is. It's called `ceedling help` (note there are no dashes) ;)

**Comment by mvandervoord** [comment]
Interesting! Could I ask what method you used to install ceedling? It appears you're missing at least one dependency (thor).

**Comment by michaelbadcrumble** [comment]
I used a git clone command to study Ceedling for Ceedling-ui.

**Comment by michaelbadcrumble** [comment]
I did that gem install command and I got OpenSSL errors.  You can assume stack trace messages.   
```
/usr/local/lib/ruby/2.6.0/rubygems/request.rb:84:in `rescue in configure_connection_for_https': Unable to require openssl, install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources (Gem::Exception)
```
Then at the end of the errors:
```
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- openssl (LoadError)
```

**Comment by mvandervoord** [comment]
This seems to be a common problem with a few versions of Ruby: https://github.com/rvm/rvm/issues/4357

**Comment by dpostorivo** [comment]
If you are using it from cloning the repo, there's a lot that can go wrong. There's not really a good path to installing it locally without extra rake hooks and if you don't make sure the submoudles are pulled down even if you install it, you may be missing things. 

On a forked version, I've provided extra setup and install instructions to have rake install the locally built gem. https://github.com/BuLogics/Ceedling/tree/tmp-release-0.28.3.1. If people are interested, I can clean up the instructions and create a pull request for these improvements.

**Comment by michaelbadcrumble** [comment]
I am going to give it a look.  But i'm wondering if there is a Docker image for Ceedling.

**Comment by mvandervoord** [comment]
You can find a docker image with a working snapshot here:

https://hub.docker.com/r/throwtheswitch/madsciencelab

**Comment by mvandervoord** [comment]
yes. I've made a couple of attempts to do a release in the last couple months. I'll be trying again soon. It seems every time I prepare to do so, there are arguments about a few of the features. ;)

**Comment by JuPrgn** [comment]
Great thank you ! Yes I saw many new features I would like to try 😉 
I don't know how you make release and the work required for it but please let me know if I can help or test !

**Comment by mvandervoord** [comment]
:) Thanks, I appreciate that. I'm honestly trying to aim towards a more regular release schedule and a formal process for releasing. It's definitely a work in progress though.
