### ISSUE TITLE
Mock good practices

### ISSUE THREAD

**Issue by JuPrgn** [ThrowTheSwitch/Ceedling#405]
Hi @mvandervoord I would like to test some modules and I cannot figure out how to do. 

Please consider I have the following modules : 
- Item module :  `Item.c` / `Item.h` / `test_Item.c`
- ListItem module : `ListItem.c` / `ListItem.h` / `test_ListItem.c`

Item module define the following functions : 
- `void InitItem(ITEM_t *Item)` : function that initialise every field of `ITEM_t` typedef structure
- `int getItemData(ITEM_t *Item)` : return the content of internal `int Data` variable
- `void setItemData(ITEM_t *Item, int Data)` : `int Data` setter

ListItem module defines the following functions : 
```
typedef struct{
   ITEM_t Items[3];
}LISTITEM_t;

void InitListItem(LISTITEM_t *ListItem)
{
   for(int i=0; i<3; i++)
      InitItem(ListItem->Items[i]);
}

ITEM_t GetItemFromList(LISTITEM_t *ListItem, int Index)
{
      return ListItem->Items[Index];
}
```
Then I want to test ListItem : 

First, I mock `Item.h` in order to check `InitListItem()` calls `InitItem()` 3 times (with correct arguments in my real code).

Then I want to check GetItemFromList returns the Item corresponding to Index.

```
#include "unity.h"
#include "listitem.h"

#include "mock_item.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_InitListItem(void)
{
    LISTITEM_t ListItem;
    for(int Index = 0; Index < 3; Index++)
        InitListItem_Expect(&ListItem.Items[Index]);
}

void test_GetItemFromList(void)
{
    LISTITEM_t ListItem;
    InitListItem(&ListItem);

    setItemData(&ListItem.Items[0], 0);
    setItemData(&ListItem.Items[1], 1);

    ITEM_t TestItem;
    TestItem = GetItemFromList(&ListItem, 1);
    TEST_ASSERT_EQUAL_UINT16(1, getItemData(&TestItem));
}
```

I have some issues with `GetItemFromList()` I would like to call Item module functions to initialise and access variables but I cannot use the real and mocked versions at the same time. 

In this case : `InitListItem(&ListItem);` calls `InitItem()` and I can use `InitItem_Ignore()` but I cannot Ignore Getter and Setter and continue using them.

How do you usually figure it out ?

**Comment by mvandervoord** [comment]
Using `mock_Item.h` is definitely the option you want. You don't want to include `item.h` also.

If you focus on what you are attempting to prove with each test, you learn what corners can be cut. With your test `test_InitListItem`, you are proving that the init function gets called three times, as expected. You also want to make sure that the items are getting stuffed in the correct order. That's it. That's the test. 

To do that, mine might look something like this:

```
void test_InitListItem(void)
{
    LISTITEM_t test_items[3] = { { 11 }, { 22 }, { 33 } }; // It doesn't need to make sense, it just needs to be unique

    // If it's a reasonable number, I unwind loops in tests. We're not looking to duplicate the original code.
    // we're verifying it does what it should. we can be explicit
    InitListItem_Expect(&test_items[0]);
    InitListItem_Expect(&test_items[1]);
    InitListItem_Expect(&test_items[2]);

    // finally it calls the function being tested
    InitListItem(test_items);
}
```

Notice I didn't do anything that deals with the actual fields. I didn't require any knowledge about the internal workings of the type even... I just proved what I needed to. If I WANTED to initialize the type in a way that made sense, I COULD... but it's more maintenance and it's not actually validating anything further (thought it might reduce warnings from the compiler for the test itself).

In any case, the test for getting items is the same. I don't need to retest the get and set functions. Those are tested in `test_Item.c`. Here I just need to make sure it grabbed the correct item.

```
void test_GetItemFromList_SHOULD_ReturnCorrectItem(void)
{
    LISTITEM_t test_items[3] = { { 11 }, { 22 }, { 33 } };

    InitListItem_Expect(&test_items[0]);
    InitListItem_Expect(&test_items[1]);
    InitListItem_Expect(&test_items[2]);

    InitListItem(test_items);

    // In this case, we're testing ALL the possible getter indices... but I usually test 3-5 gets
    // one is the lowest index, one the highest, and then one or more in the middle.
    // I also like to put them in a random order to make sure it's not something order dependent
    TEST_ASSERT_EQUAL_MEMORY(test_items[1], GetItemFromList(test_items, 1), sizeof(LISTITEM_t));
    TEST_ASSERT_EQUAL_MEMORY(test_items[0], GetItemFromList(test_items, 0), sizeof(LISTITEM_t));
    TEST_ASSERT_EQUAL_MEMORY(test_items[2], GetItemFromList(test_items, 2), sizeof(LISTITEM_t));
}
```

I'd also write another test which verifies your desired behavior when you attempt to grab an out of range value. I don't know what your desired behavior IS. There doesn't seem to be an error code being returned and it's not a pointer, so it can't be null... so I went with it returning a default item:


```
void test_GetItemFromList_SHOULD_ReturnDefaultForInvalidRequests(void)
{
    // The default item might require you to be more correct with the structure
    LISTITEM_t test_default = { 5, 777, 22, "sandwhich" };
    LISTITEM_t test_items[3] = { { 11 }, { 22 }, { 33 } };

    InitListItem_Expect(&test_items[0]);
    InitListItem_Expect(&test_items[1]);
    InitListItem_Expect(&test_items[2]);

    InitListItem(test_items);

    TEST_ASSERT_EQUAL_MEMORY(test_default, GetItemFromList(test_items, -1), sizeof(LISTITEM_t));
    TEST_ASSERT_EQUAL_MEMORY(test_default, GetItemFromList(test_items, 3), sizeof(LISTITEM_t));
}
```

Does that make sense?

**Comment by JuPrgn** [comment]
Thank you very much for your valuable help ! 
I thought that the easier way to make sure it grabbed the correct item was a field comparaison but that does make sense now : I have to test modules without depanding on others already tested.
This will require some workout =)

**Comment by mvandervoord** [comment]
Yes, it's definitely a mental workout! :)

Best of luck!
