### ISSUE TITLE
Ceedling 0.29.0 recompiles everything

### ISSUE THREAD

**Issue by ojohnny** [ThrowTheSwitch/Ceedling#417]
After updating to 0.29.0, our test suite is recompiling everything even if nothing changed between the runs.

It also regenerates mocks and compiles them for each test, which it did not do before.

This adds a considerable time for unit testing, which ideally should be very fast (so they can be run often).

This is on Windows with on both `cmd` and `msys2` environments.

**Comment by CezaryGapinski** [comment]
Do you use specific preprocessor definitions for tests in your project.yml file? Maybe it is related to my issue #369.
Can you reproduce this issue on exemplary project?

**Comment by mvandervoord** [comment]
Hm. I see. I'm not sure why it's doing that. I'll poke around for a bit and see if I can figure it out.

**Comment by ojohnny** [comment]
> Do you use specific preprocessor definitions for tests in your project.yml file? Maybe it is related to my issue #369.
> Can you reproduce this issue on exemplary project?

I have managed to narrow it down a bit now. It also happens in the example `temp_sensor` if I add the following to `project.yml` (which is added automatically when the project is created from `ceedling new ...`):

```yaml
# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "${1}"  # or "-L ${1}" for example
  :common: &common_libraries []
  :test:
    - *common_libraries
  :release:
    - *common_libraries
```

Without it, it works as it did in 0.28.3.  Did the merging of the libraries break somehow in 0.29.0? Or is this (default) configuration outdated?

**Comment by ojohnny** [comment]
It seems I spoke too soon.

While the above configuration is true for the example project, removing that section from my project does not solve the problem, so something else seems to be wrong here...

**Comment by mvandervoord** [comment]
I've narrowed it down to directory handling. I haven't figured out how to fix it yet, but I'm working on it. At the moment, there is a task in charge of making sure the build directories get built. When triggered, it goes through the build dirs and makes sure each exists. It's an all-or-nothing thing... for some reason, it's getting triggered on every build at the moment, which means every build directory is touched. On Windows, it appears that a touched directory counts as a touched file within it. So all the temporary files (runners, mocks, etc) are getting rebuilt. 

I'm not certain about the details yet.

**Comment by mvandervoord** [comment]
I believe I have most of this happy again. I'll be releasing it this week.
