### ISSUE TITLE
Export "FAILED TEST SUMMARY" to html file?

### ISSUE THREAD

**Issue by congtmbg** [ThrowTheSwitch/Ceedling#422]
Dear everyone,
After running Ceedling, I will have "FAILED TEST SUMMARY" result on console terminal.
I want export "FAILED TEST SUMMARY" to html file or other file.
Can you tell me about the solutions, please?
Thank you.

**Comment by mvandervoord** [comment]
There isn't an html output option at this time, unless you're running test coverage (in which case it's outputting your coverage, not your results).

In your project yaml file, you can scroll down to the `:plugins:` section. If you remove (or comment out) stdout_pretty_tests_report, you can replace it with one of these other options:

- colour_report
- junit_tests_report
- raw_output_report
- stdout_gtestlike_tests_report
- stdout_ide_tests_report
- stdout_pretty_tests_report
- teamcity_tests_report
- warnings_report
- xml_tests_report

If you're feeling like you really need html and want to try your hand at a little ruby, cloning the `xml_tests_report` will get you very close to what you need. We'd gladly accept an html report contribution.

**Comment by congtmbg** [comment]
Thanks @mvandervoord .
