### ISSUE TITLE
Can't update ceedling/cmake/unity

### ISSUE THREAD

**Issue by bigbrett** [ThrowTheSwitch/Ceedling#423]
I have an existing project using ceedling/cmake/unity that I would like to update to use the latest versions of all three. 

Current versions: 
```
$ ceedling version 
       Ceedling:: 0.28.3
       CException:: 1.3.1.18
       CMock:: 2.4.6.217
       Unity:: 2.4.3.122
```

I ran `gem update ceedling` and it claims there are no new updates available. However when I try to run ceedling upgrade, I get the following error: 
```
$ ceedling upgrade --local my-project-name
rake aborted!
Don't know how to build task 'update' (see --tasks)
/var/lib/gems/2.5.0/gems/ceedling-0.29.0/bin/ceedling:332:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/ceedling-0.29.0/bin/ceedling:319:in `<top (required)>'
/usr/local/bin/ceedling:23:in `load'
/usr/local/bin/ceedling:23:in `<main>'
(See full trace by running task with --trace)
ERROR: Ceedling Failed
```

Then when I run `ceedling --tasks` it just starts to try and build my unit tests. When I run ceedling help, it doesn't look like I even have a ceedling upgrade tasks. 

What am I doing wrong? Why can't I update my project? Any help appreciated. 

Running on Ubuntu 18.04 LTS

**Comment by mvandervoord** [comment]
The latter error is because ceedling 0.28.x didn't know how to do the update method for a project. it wasn't a feature yet.

I can't explain why you can't `gem update ceedling`. That SHOULD work, using ruby's gem system to automatically upgrade from 0.28.3 to 0.29.0. Once that's successful, you can upgrade the project itself.

**Comment by bigbrett** [comment]
What would you propose as a path forward then? Is there a way to "start from scratch" without having to remove all my tests and project configuration?

**Comment by bigbrett** [comment]
I should note that I do have a ceedling 0.29.0 on my computer. When I type "gem uninstall ceedling" it asks me which version I wish to uninstall. I just can't upgrade my project, which has everything installed locally

**Comment by bigbrett** [comment]
figured out how to update, but still a few quirks.  To update I did the following:

1. Uninstall old version of ceedling `gem uninstall ceedling`
2. Install new version `gem install ceedling` or just choose the old version if you already have both installed
3. go into your project and remove ceedling artifacts that aren't the yaml file vendor directory `rm -rf vendor && rm ceedling`
4. go up one directory, and recreate the ceedling project `cd ../; ceedling new --local myProject`. Make sure you chose NOT to overwrite the project.yml when prompted 
5. cd back into the project and run a `ceedling clean`. You should now be able to build your tests. 

I am now able to build all my tests, however when I run `ceedling version` I get an odd output: 

```
Ceedling:: 0.29.0
CException:: UNKNOWN.UNKNOWN
     CMock:: UNKNOWN.UNKNOWN
     Unity:: UNKNOWN.UNKNOWN
```

As I said, tests build fine. Any ideas?

**Comment by mvandervoord** [comment]
The new version tracking in 0.29.0 has a bug. We've already fixed it and will be releasing a fix this week.

**Comment by mvandervoord** [comment]
As far as ceedling upgrade goes, I'll have to look into that one. It works well on my system, but definitely haven't tested the variations.

Is your project installed as gem or installed with a vendor directory or something else?

**Comment by mvandervoord** [comment]
ok. I have the upgrade process running smoother. We'll get 0.29.1 out this week.

**Comment by bigbrett** [comment]
You beat me to it, I was calling it from within the project. I would say that as long as this is in the docs somewhere, then all is good. Looking forward to the update and thanks for the help!
