### ISSUE TITLE
test:all behaving like test:delta

### ISSUE THREAD

**Issue by GardenTools** [ThrowTheSwitch/Ceedling#424]
Running "ceedling test:all" on a project project only produces results the first time it is run. On subsequent runs it produces no results. I use the sample temp_sensor project as an example - second run output:

```
$ ceedling test:all

Test 'TestAdcConductor.c'
-------------------------

Test 'TestAdcHardware.c'
------------------------

<snip list of tests>

Test 'TestUsartModel.c'
-----------------------

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.

```

This is the behaviour described for "test:delta" (Run only those unit tests for which the source or test files have changed) not "test:all"  (Run all unit tests). ceedling test:all should run all tests irrespective of whether they passed last time they were run or whether they need a recompile or not.

The "workaround"  seems to be to manually remove the content of "build/test/results" before running again. Which causes ceedling to re-run the tests without forcing a recompile.

----
$ ceedling version
   Ceedling:: 0.29.1
      Unity:: 2.5.0
      CMock:: 2.5.1
 CException:: 1.3.2

----

I've checked with v0.28.3 and it doesn't behave in this way, in that version test:all always re-runs all tests.

**Comment by CezaryGapinski** [comment]
I have the same. I guess it stops working after change in this [commit](https://github.com/ThrowTheSwitch/Ceedling/commit/c04b327af516a38d9a3b58e35895aab606755842):

```diff
  task :all => [:directories] do
-    @ceedling[:test_invoker].setup_and_invoke(COLLECTION_ALL_TESTS)
+    @ceedling[:test_invoker].setup_and_invoke(COLLECTION_ALL_TESTS, TEST_SYM, {:force_run => false})
  end
```

Maybe it is intentional change, but I'm not sure.

**Comment by GardenTools** [comment]
Good spot @CezaryGapinski, I can confirm the I see the altered behaviour is in c04b327 but not in 2c0578d. Given the commit comment about preventing endless rebuilds I'd hazard a guess that it is an unintended consequence of the change. Preventing (unintended) repeated builds accidentally also prevents (intended) repeated test runs.
