### ISSUE TITLE
Empty Coverage report from "ceedling utils:gcov"

### ISSUE THREAD

**Issue by paul-das** [ThrowTheSwitch/Ceedling#447]
Hi,
My ceedling version is :: 0.28.3, gcovr version is :: 4.2 and I am on a Windows machine, I am working on getting gcovr to generate a coverage report based on data generated by gcov. I get the following output at the end of "ceedling gcov:all":
---------------------------
GCOV: CODE COVERAGE SUMMARY
---------------------------
adc_service.c Lines executed:100.00% of 50
adc_service.c Branches executed:100.00% of 20
adc_service.c Taken at least once:95.00% of 20
adc_service.c Calls executed:100.00% of 12

lod_service.c Lines executed:57.94% of 340
lod_service.c Branches executed:67.44% of 215
lod_service.c Taken at least once:40.47% of 215
lod_service.c Calls executed:50.85% of 59

pos_service.c Lines executed:66.94% of 360
pos_service.c Branches executed:77.78% of 216
pos_service.c Taken at least once:57.87% of 216
pos_service.c Calls executed:65.82% of 79

indicating that gcov did collect coverage data, however when I do "ceedling utils:gcov" I only get "GcovCoverageResults.html" file, but no other files. I read a few issue discussions on this topic:
https://github.com/ThrowTheSwitch/Ceedling/issues/224
https://github.com/gcovr/gcovr/issues/112
https://github.com/gcovr/gcovr/issues/152

even though the symptoms looked similar, I couldn't find the root cause and it seems most of them should have been fixed in the versions I am using. I have tried running the demo for gcov and that works as expected, with the same ceedling framework (indicating the default.yml file is configured right). I compared the project.yml files between the demo and my project and they match (at least from what I can say). Here are the relevant options from my project.yml file:
:gcov:
    :html_report_type: detailed
:plugins:
  :load_paths:
    - ../..//test/test_frameworks/ceedling//plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov    

Would appreciate any pointers.

Thank you,
Paul

**Comment by mvandervoord** [comment]
The issues you're referencing are the old method of configuring gcov. We've since expanded its functionality significantly. Try this:

```
:gcov:
  :reports:
    - HtmlDetailed
```

alternatively, if you want to continue to use the old format, you need to enable that report first:

```
:gcov:
  :html_report: true
  :html_report_type: detailed
```

You'll probably want to read the documentation for the gcov plugin. There are a lot of options you can fiddle with to get just what you want. You can find it here: https://github.com/ThrowTheSwitch/Ceedling/tree/master/plugins/gcov

**Comment by paul-das** [comment]
Thank you for getting back. I tried both the versions of the gcov settings you suggested. In case of the "new format" (your first recommendation), I get the following output, the basic report is empty with only GcovCoverageResults file being generated.
```
In your project.yml, define:

:gcov:
  :html_report_type:

 to basic or detailed to refine this feature.
For now, just creating basic.
Creating a basic html report of gcov results in build/artifacts/gcov/GcovCoverageResults.html...
Done.
```
And if I try the old format, I get the following, however the report is still empty.
```
Creating a detailed html report of gcov results in build/artifacts/gcov/GcovCoverageResults.html...
Done.
```

The part about the readme,md file in the link you sent me that I am confused with, is that the initial part of it under the heading "Reports" showcase the newer format you mentioned in the previous comment. However, the following examples for individual reports have the old format. Are they mutually exclusive?

I tried the following to see if I can change the title of the report and I didn't have any luck:

```
:gcov:
  :html_report: true
  :html_report_type: detailed
  :gcovr:
    :html_title: NotHead
```
I tried combinations of single and double quotes around NotHead and the title unfortunately, still remained "Head".

Apart from listing my source files under the ":source:" sub-section in the ":paths:" section, do I need them to be specified else where?

**Comment by mvandervoord** [comment]
My apologies. I wasn't paying attention to the ceedling gem version in your first email. You ARE on an older gem, therefore the older format is appropriate.

So stick with the old format.

If you execute the following, does it give you any clues as to what might be wrong?

```
ceedling clobber verbosity[4] gcov:all utils:gcov
```

**Comment by paul-das** [comment]
Unfortunately, not. It has the same line:

```
Creating a detailed html report of gcov results in build/artifacts/gcov/GcovCoverageResults.html...
> Shell executed command:
'gcovr -p -b -e "^vendor.*|^build.*|^test.*|^lib.*" --html --html-details -r . -o  "build/artifacts/gcov/GcovCoverageResults.html"'

Done.
```
I am starting to suspect it might be due to a difference between my ceedling version and my gcovr version (which I only installed last week, so is the latest version). I will try the latest version of Ruby, ceedling and gcovr on a different machine and get back to you if I had any luck.

Thank you.

**Comment by mvandervoord** [comment]
If you execute the gcovr line from the command prompt, does it work?

**Comment by paul-das** [comment]
Should have mentioned that in my previous comment. It doesn't. Generates the same empty HTML file as running 
`ceedling utils:gcov`

**Comment by mvandervoord** [comment]
One more question, out of curiosity. Does the path `build/artifacts/gcov` already exist? If not, could you manually create it and then try the gcovr line again? I just want to rule out path issues.

**Comment by paul-das** [comment]
I tried it with and without the HTML file present in that directory and in either case I have the same empty HTML file. One thing I forgot to mention until now is that I see a host GCOV files being created in the root directory when I execute the command, they all get deleted at the end of the process.

**Comment by paul-das** [comment]
Hi Mark,
Turns out I had the same problem as this person:
https://github.com/ThrowTheSwitch/Ceedling/issues/449

reverting gcovr to 4.1 does the trick for me.

Thank you for the help and developing an awesome framework.

**Comment by mvandervoord** [comment]
Thanks for letting me know. Best of luck!  :)

**Comment by HomoHabilis** [comment]
Same problem here on Ceedling 0.31.1. I went back to gcovr 4.1 and it solved the issue.
