### ISSUE TITLE
[gcov] gcovr 4.2 breaks gcov plugin - project source files missing from html report

### ISSUE THREAD

**Issue by justaddobvious** [ThrowTheSwitch/Ceedling#449]
Just installed MacOS Catelina from scratch, and as such grabbed everything I needed anew.
pip3 install gcovr
ceedling clobber
ceedling test:all
ceedling gcov:all utils:gcov

This produces the following html report, missing my source:

File | Lines | Branches 
unity/src/unity.c |   |   | 16.8 % | 101 / 601 | 7.1 % | 32 / 451
cmock/src/cmock.c |   |   | 0.0 % | 0 / 65 | 0.0 % | 0 / 36

Downgraded to gcovr 4.1
pip3 uninstall gcovr
pip3 install gcovr==4.1
ceedling clobber
ceedling test:all
ceedling gcov:all utils:gcov

This produces the following complete html report

File | Lines | Branches 
transfer/transfer.c |   |   | 68.0 % | 608 / 894 | 48.3 % | 170 / 352
framer/framer.c |   |   | 38.9 % | 14 / 36 | - % | 0 / 0
crc/crc.c |   |   | 20.8 % | 11 / 53 | 16.7 % | 2 / 12
testtransfer/vendor/ceedling/vendor/unity/src/unity.c |   |   | 16.8 % | 101 / 601 | 7.1 % | 32 / 451
testtransfer/vendor/ceedling/vendor/cmock/src/cmock.c |   |   | 0.0 % | 0 / 65 | 0.0 % | 0 / 36
 
gcovr release notes talk about some breaking changes in arguments which might be causing this to happen.  See [http://gcovr.com/en/stable/changelog.html#november-2019](http://gcovr.com/en/stable/changelog.html#november-2019)

Thanks for the great tool and plugin.  And, yes, I am trying to get my coverage higher than 68 % ;)

**Comment by mvandervoord** [comment]
Thank you so much for digging into this. It's nice to hear why it's breaking. I really appreciate the time you spent and the link to the changes!

**Comment by gsmithufl** [comment]
This _may_ be related to this: https://github.com/gcovr/gcovr/issues/364. I've found in ceedling 0.30.0 I encounter an issue where detailed reports aren't generated and the sonarqube .xml is empty. Logfiles are also empty. Downgrading to 4.1 allows detailed reports to be generated correctly.

**Comment by binarymaker** [comment]
My solution is to uninstall gcovr and install 4.1
```shel
pip install -Iv gcovr==4.1
```
remember the same in CI docker file

**Comment by AlexandreMarkus** [comment]
@mvandervoord I did face the same issue. GCOVR is now at version 5.0. Would it be possible to fix this to use the latest library version please. Very great plugin !!
