### ISSUE TITLE
Modifying a define in header does not trigger file rebuild

### ISSUE THREAD

**Issue by JuPrgn** [ThrowTheSwitch/Ceedling#452]
Hi,

I have to call `ceedling clean` before calling `ceedling test:test_foo.c` when i modify a define in `device.h`. 
If I don't clean, my tests are executed with the previous defined value.

I have a module `test_foo.c` `foo.c` and `foo.h` that include `device.h` and call `device.c` functions.

- Ceedling:: 0.29.1
- Unity:: 2.5.0
- CMock:: 2.5.1
- CException:: 1.3.2

**Comment by CezaryGapinski** [comment]
Hi!

Do you have the same issue when you set `use_test_preprocessor` and `use_deep_dependencies` options?
Please try enable these options under `:project:` section in your project.yml file.

```yml
:project:
  ...
  :use_test_preprocessor: TRUE
  :use_deep_dependencies: TRUE
  ...
```

**Comment by JuPrgn** [comment]
Hi 
Thank you for looking at my issue ! 
I can't try this until Monday but I disabled test_preprocessor because my current configuration is not working when this is activated. I don't remember if deep_dependencies was activated but I will let you know asap.

**Comment by JuPrgn** [comment]
When I set `:use_test_preprocessor: TRUE` and/or `:use_deep_dependencies: TRUE`, I get error 

> ERROR: Shell command failed.

I am not using GCC and preprocessor seems to call gcc.exe should I had some "preprocessor" configuration to my current compiler which is XC16 from Microchip ? I did not seen such parameters in YAML example but I may look for this.

Please note that my project is currently configured with : ` :use_auxiliary_dependencies: TRUE`

**Comment by CezaryGapinski** [comment]
To run use_deep_dependencies feature you can try to set `generate_deep_dependencies` to false, because it looks that XC16 compiler have the same flags like standard gcc.

```yml
:project:
  ...
  :use_test_preprocessor: TRUE
  :use_deep_dependencies: TRUE
  :generate_deep_dependencies: FALSE
  ...
```
You need to set correctly `test_compiler` and `test_file_preprocessor` (as you already know based on your comment in #42)

```yml
:tools:
  :test_compiler:
    :executable: <your XC16 compiler>
    :name: 'XC 16 Test Compiler'
   :arguments:
     ...
     - -MMD
     - -MF ${4}
     ...
  :test_file_preprocessor:
    :executable: <your XC16 compiler>
    :name: 'XC 16 Test File Preprocessor'
    :arguments:
      ...
```

As an arguments list you have to base on default arguments from gcc in [default.rs file](https://github.com/ThrowTheSwitch/Ceedling/blob/master/lib/ceedling/defaults.rb) - and  and Tool Element Runtime Substitution: Notational Substitution section [in documentation](https://github.com/ThrowTheSwitch/Ceedling/blob/master/docs/CeedlingPacket.md)

**Comment by JuPrgn** [comment]
Thank you for your help, I will work on this as soon as I fix spaces in paths.

I have some difficulties to understand how ceedling use preprocessor because my current project (without preprocessor enabled) also process define and preprocessor things...

The substition is a bit tricky for me at the moment with YAML syntax and ruby things I was trying to figure out what is done by YAML and what is changed with ruby =)

**Comment by JuPrgn** [comment]
I could work again on this with ceedling 0.30.0 and `use_deep_dependencies: TRUE` solve this.
