### ISSUE TITLE
Test platform-specific conditionally compiled code

### ISSUE THREAD

**Issue by ojousima** [ThrowTheSwitch/Ceedling#454]
Hello, 

I'm running same code on three MCUs which have different peripherals available. For example one of the MCUs doesn't have a FPU, while other two require handling FPU interrupts. I've solved this by having code like this:

```
#ifdef FLOAT_ABI_HARD
// Function handles and clears exception flags in FPSCR register and at the stack.
// During interrupt, handler execution FPU registers might be copied to the stack
// (see lazy stacking option) and it is necessary to clear data at the stack
// which will be recovered in the return from interrupt handling.
void FPU_IRQHandler (void)
{
    // Prepare pointer to stack address with pushed FPSCR register 
    // (0x40 is FPSCR register offset in stacked data)
    uint32_t * fpscr = (uint32_t *) (FPU->FPCAR + 0x40);
    // Execute FPU instruction to activate lazy stacking
    (void) __get_FPSCR();

    // Check exception flags
    // Critical FPU exceptions signaled:
    // - IOC - Invalid Operation cumulative exception bit.
    // - DZC - Division by Zero cumulative exception bit.
    // - OFC - Overflow cumulative exception bit.
    if (*fpscr & 0x07)
    {
        ri_log (RI_LOG_LEVEL_WARNING, "FPU Error \r\n");
    }

    // Clear flags in stacked FPSCR register. To clear IDC, IXC, UFC, OFC, DZC and IOC flags, use 0x0000009F mask.
    *fpscr = *fpscr & ~ (0x0000009F);
}

static void fpu_init (void)
{
    NVIC_SetPriority (FPU_IRQn, APP_IRQ_PRIORITY_LOW);
    NVIC_ClearPendingIRQ (FPU_IRQn);
    NVIC_EnableIRQ (FPU_IRQn);
}

#else //<! FLOAT_ABI_HARD
static void fpu_init (void)
{}
#endif
```
Is there a way to run the same test twice, once with the source file being preprocessed with `FLOAT_ABI_HARD` defined and once without it being defined?
The most related issues I could find are #196 and #335, but I couldn't figure out a way to test both code segments without splitting the file into two different .c-files and testing them separately with test-specific defines.

**Comment by Letme** [comment]
Have two target.yml files which also have defines in them and common project.yml then when you call from command line take target and then test and it will run with one defines and afterwards again with other target.

**Comment by ojousima** [comment]
Thanks @Letme, this probably will work for my use case. For reference of others, #127 .  
I ran into some other issues with the IC provider's SDK relying on conditional compiling of correct headers, but it's unrelated to this. Closing.
