### ISSUE TITLE
Ceedling only has 6 commands

### ISSUE THREAD

**Issue by mohannadmaklad** [ThrowTheSwitch/Ceedling#458]
When I enter "ceedling" in my command line it only show 6 commands, which don't do any real work..  
  
![Image](https://a.top4top.io/p_1484ddvqm1.png)

**Comment by mvandervoord** [comment]
Those are the commands for creating projects (either new projects or projects based on built in examples).

If you've already made a project, move into the root directory of that project (the one that contains the `project.yml` file) and run `ceedling help` again. You'll see a much richer selection of things you can do now.
