### ISSUE TITLE
static inline function mocks

### ISSUE THREAD

**Issue by LittleBasdart** [ThrowTheSwitch/Ceedling#463]
I'm trying out the CMock feature for mocking static inline functions in header files, but I cannot get it working...

What I have
------------
I have a flat workspace, which looks like that:
```
:paths:
  :test:
    - unittest/**
    - softwaretest/**
    - .
  :source:
    - src
    - src/classB-tests
    - src/isotp-c
    - src/tiny-json
  :include:
    - src/Interfaces
```
where
- src contains modulename.c, modulename.h
- src/Interfaces contains i_modulename.h.
This is done to sepparate interface header information from implementation defined header information.

What I want to achieve
-------------
To increase test coverage in this automotive project, I want to unit test the drivers. For that purpose I have to get rid of all hardware registers and compiler dependend header files, but without creating a new source file. A new header file is created which is filled with static inline functions to wrap all hardware register accesses.

What I did so far
--------------
I started with the Architecture Support Package, as it was the first one in my project explorer. I created a header file and filled it with all registers and assembler instructions:
```
ASP_Registers.h
#include <stdint.h>

#ifdef __XC
#include <xc.h>
#endif

static inline void ASP_INTCON_set(uint32_t value)
{
    INTCON = value;
}

static inline void ASP_PRISS_set (uint32_t value)
{
    PRISS = value;
}
...
```
adding the path to project.yaml and added also the cmock feature
```
diff --git a/project.yml b/project.yml
index 01f0667..4331517 100644
--- a/project.yml
+++ b/project.yml
@@ -40,6 +40,7 @@
     - src/tiny-json
   :include:
     - src/Interfaces
+    - src/HardwareRegisters
 
 :defines:
   # in order to add common defines:
@@ -61,6 +62,8 @@
 
 :cmock:
   :mock_prefix: mock_
+  :treat_inlines:
+    :include
   :when_no_prototypes: :warn
   :enforce_strict_ordering: TRUE
   :plugins:

```
Running unit tests creates now:
```
Compiling test_ASP.c...
In file included from src/ASP.c:14:
src/HardwareRegisters/ASP_Registers.h: In function 'ASP_INTCON_set':
src/HardwareRegisters/ASP_Registers.h:25:5: error: 'INTCON' undeclared (first use in this function); did you mean 'INT8_C'?
     INTCON = value;
     ^~~~~~
...
```
By looking at the command line:
```
gcc.exe -I"unittest" -I"softwaretest" -I"src" -I"src/classB-tests" -I"src/isotp-c" -I"src/tiny-json" -I"src/Interfaces" -I"src/HardwareRegisters" -I"D:/Projekte/eclipse workspace/Helmholtz/ceedling/vendor/unity/src" -I"D:/Projekte/eclipse workspace/Helmholtz/ceedling/vendor/cmock/src" -I"build/test/mocks" -DCEEDLING_TEST -DGNU_COMPILER -g -c "src/ASP.c" -o "build/test/out/c/ASP.o" -MMD -MF "build/test/dependencies/ASP.d"
```
you can see that the include order is the wrong way around. The mocked headers should be included first! So I did:
```
diff --git a/ceedling/lib/ceedling/configurator_builder.rb b/ceedling/lib/ceedling/configurator_builder.rb
index da8a816..7cf9e18 100644
--- a/ceedling/lib/ceedling/configurator_builder.rb
+++ b/ceedling/lib/ceedling/configurator_builder.rb
@@ -250,8 +250,8 @@ class ConfiguratorBuilder
   def collect_test_support_source_include_vendor_paths(in_hash)
     return {
       :collection_paths_test_support_source_include_vendor =>
-        in_hash[:collection_paths_test_support_source_include] +
-        get_vendor_paths(in_hash)
+        get_vendor_paths(in_hash) +
+        in_hash[:collection_paths_test_support_source_include]
       }
   end
```
test_ASP.c compiles and runs fine, but it clashes somewhere else:
```
 Compiling test_ErrorStates.c...
In file included from src/errorStates.h:20,
                 from src/errorStates.c:17:
build/test/mocks/i_errorInfo.h:23:46: error: unknown type name 'uint32_t'
 void errorInfo_faultComponents(char* buffer, uint32_t bufferSize);
                                              ^~~~~~~~
```
because inclusion of <stdint.h> is not copied from original i_errorInfo.h to the mocked one. This was not an issue before, as ceedling never used the mocked headers because of the wrong include order.
And by the way, I had to add ./ to my include paths, as all mocks use workspace relative paths.

Has someone got this feature running? What am I missing here? Help is pretty much appreciated!

Kind Regards,
Florian Kaup
Sentinel Software GmbH

**Comment by mvandervoord** [comment]
I'm not following why the order of the include directories would matter in this instance? It's only going to find you mock_ includes in the mock directory, no matter which order you place them in... and it's only going to find the non-mock includes in the other directory, no matter which order they are searched. So the end results should be identical, should they not?

In any case, you'll need to trick your compiler into being able to compile this. If you have a function declared as `static inline`, and a mock version of that same function declared in a mock, it's going to continue to use the `static inline` version at best (because they will have already been inlined in the build step) or fail during link due to multiple conflicting definitions.

You can get around this by doing something like this in that header file:

```
#ifdef TEST
// Mockable API
void ASP_INTCON_set(uint32_t value);
void ASP_PRISS_set (uint32_t value);
#else 
// Real API
static inline void ASP_INTCON_set(uint32_t value)
{
    INTCON = value;
}

static inline void ASP_PRISS_set (uint32_t value)
{
    PRISS = value;
}
#endif
```

If you are going to want to test the low-level wrapper itself (which it sounds like you've decided against this already) you would have to get a little fancier with the defines there and allow for a custom define for testing this specific module.

I hope this helps. If I've misunderstood something, please let me know.

**Comment by LittleBasdart** [comment]
You are right, in the build/test/mock-folder only mock_*-files are present ... As long as you are not using ":treat_inlines: include". With this feature, cmock generates header files, which have the same name as the original ones.

Your idea with the compiler switch looks good, I will take that into consideration as soon as my refactoring is done and I can start testing.

BUT....

With the cmock "treat_inline"-feature, the work of creating special testable header files is done by cmock. The input file src/HardwareRegisters/ASP_Registers.h:
```
#ifndef ASP_REGISTERS_H_
#define ASP_REGISTERS_H_

#include <stdint.h>

#ifdef __XC
#include <xc.h>
#endif

static inline void ASP_INTCON_set(uint32_t value)
{
    INTCON = value;
}

static inline void ASP_PRISS_set (uint32_t value)
{
    PRISS = value;
}

static inline void ASP_IPC_set (uint8_t reg, uint8_t entry, uint8_t value)
{
    (&IPC0SET)[reg * 4u] = (uint32_t)value << (8u * entry);
}
...
```
is processed into build/test/mock/ASP_Registers.h:
```



void ASP_INTCON_set(uint32_t value);



void ASP_PRISS_set (uint32_t value);



void ASP_IPC_set (uint8_t reg, uint8_t entry, uint8_t value);


...
```
At that point the include order matters.

This new ASP_Registers.h has the appropriate mocks generated, which reside in the same folder.
The compiler searches all include paths until a matching file name is found. So the generated one must be first in paths, else the original static inline functions will be used.

As I mentioned already, these generated header files are missing some system includes (as you can see above, stdint.h is missing). Maybe this is a cmock issue?

Thank you for your quick response!
Kind Regards, Florian Kaup

**Comment by mvandervoord** [comment]
:) Ah I see. Yes, this is a new feature that some community members have been rolling into CMock. It's possible that it's not fully baked yet? I suspect they're dropping the includes on purpose because they don't want it to try to pull in too much stuff? 

You could force it to include those headers by adding to :includes maybe?

**Comment by LittleBasdart** [comment]
Adding to :includes does not solve this, as the includes are put into `mock_filename.h`, but not into the generated `build/test/mock/filename.h`. I will check with cmock project for this issue.

What about the include order issue?
https://github.com/ThrowTheSwitch/CMock/blob/master/docs/CMock_Summary.md states:
>We have to set the mock folder before the other includes to avoid the test code including the original header instead of the newly generated header (without inline functions).

**Comment by mvandervoord** [comment]
Yes, I'd appreciate it if you posted the issue on the cmock issues list. While they're all ThrowTheSwitch projects and I'm the primary maintainer of all of them, it is MUCH easier to keep track of things when they're organized. Plus, it'll be easier to get help from those who wrote this feature. :)

I'm understanding now why the include order matters in this instance. It should be a hard change. I'll try tackling that soon. :)

**Comment by LittleBasdart** [comment]
Thank you very much! You can find my proposal to solve this issue in my first post.

**Comment by mvandervoord** [comment]
You rock. Thanks for being patient with me while I pieced together what you already knew. ;)

**Comment by mvandervoord** [comment]
Fixed the Ceedling portion of this issue. Thanks!
