### ISSUE TITLE
"bundle execute rake" in README.md doesn't work

### ISSUE THREAD

**Issue by zanedp** [ThrowTheSwitch/Ceedling#47]
The README says to run this command:
> bundle execute rake # Run all CMock library tests

However, I get this error message when I do it on my system:
> Could not find command "execute".

I don't know what the command should be instead.

It may also be useful to mention that Ruby should be in your `PATH` and the `bundle` gem installed.

**Comment by zanedp** [comment]
I think it's supposed to be `exec` instead of `execute`, but I don't know what parameter to pass:
>`$ bundle exec rake`
`rake aborted!
Don't know how to build task 'default'`

**Comment by lpil** [comment]
bundle exec rake spec

**Comment by dpostorivo** [comment]
As of [this commit](https://github.com/ThrowTheSwitch/Ceedling/commit/474e6f8c683582a072024b0ec92ffa5a1b42c6e6)  `bundle exec rake` works.

**Comment by mvandervoord** [comment]
Thanks for checking dpostorivo. I hate to test the installation issues myself. It doesn't prove much to say that it works on my (development) machine!
