### ISSUE TITLE
sh: 1: ^build.*: not found

### ISSUE THREAD

**Issue by Cherish-Gww** [ThrowTheSwitch/Ceedling#471]
I have deploy ceedling on my server.  in my local PC I can run it pass, but server, could you help me , is there any software need to be install? here is server log:

Test 'test_block_memory_manage.c'
Generating dependencies for test_block_memory_manage.c...
Generating dependencies for unity.c...
Generating dependencies for block_memory_manage.c...
Generating runner for test_block_memory_manage.c...
Compiling test_block_memory_manage_runner.c...
Compiling test_block_memory_manage.c...
Compiling unity.c...
Compiling block_memory_manage.c with coverage...
Compiling CException.c...
Compiling cmock.c...
Linking test_block_memory_manage.out...
Running test_block_memory_manage.out...
Creating a detailed html report of gcov results in build/artifacts/gcov/GcovCoverageResults.html...
sh: 1: ^build.*: not found
sh: 1: ^test.*: not found
sh: 1: ^lib.* : not found
usage: gcovr [options] [search_paths...]
gcovr: error: argument -e/--exclude: expected one argument
ERROR: Shell command failed.
> Shell executed command:
'gcovr -p -b -e "-r "." -e "^vendor.*|^build.*|^test.*|^lib.*" " --html --html-details -f /home/weig/workspace/patches/src -r . -o  "build/artifacts/gcov/GcovCoverageResults.html"'
> And exited with status: [127].

rake aborted!
ShellExecutionException: ShellExecutionException

**Comment by dpostorivo** [comment]
This looks like a an issue with quoting in that specific command. Try just running:

`gcovr -p -b -e "-r "." -e "^vendor.|^build.|^test.|^lib." " --html --html-details -f /home/weig/workspace/patches/src -r . -o "build/artifacts/gcov/GcovCoverageResults.html`

If it's the same result, try removing some quotes.

**Comment by Cherish-Gww** [comment]
Thank you, I was found the issue:
gcovr 4 is not support more -e parameter.
So the command is:
```
gcovr -p -b -r . -e "^vendor.|^build.|^test.|^lib." " --html --html-details -f /home/weig/workspace/patches/src -r . -o "build/artifacts/gcov/GcovCoverageResults.html
