### ISSUE TITLE
Place header files on a separate directory

### ISSUE THREAD

**Issue by felipebalbi** [ThrowTheSwitch/Ceedling#476]
Hi,

So here's the question:

In my repository, I have the following directory structure:

```
src                                     -> all source files
include/#{projectName}/   -> all headers
test/                                   ->
```

Is there a way to tell ceedling to generate headers under include/projectName/srcName.h instead of src/srcName.h?

**Comment by art-of-dom** [comment]
Yep see https://github.com/ThrowTheSwitch/Ceedling/blob/master/plugins/module_generator/README.md for full configuration options, but TL;DR  you would add this your project.yml:


```
:module_generator:
  :project_root: ./
  :source_root: src/
  :inc_root: include/#{projectName}/ 
  :test_root: test/
```

**Comment by felipebalbi** [comment]
Worked beautifully, thank you
