### ISSUE TITLE
Can't link `-lm` with 0.29.1

### ISSUE THREAD

**Issue by felipebalbi** [ThrowTheSwitch/Ceedling#477]
Hi,

There's a bug in `0.29.1` which prevents me from linking any extra libraries:

```
'gcc "build/test/out/c/test_foo_runner.o" "build/test/out/c/test_foo.o" "build/test/out/c/mock_bar.o" "build/test/out/c/mock_driver.o" "build/test/out/c/mock_baz.o" "build/test/out/c/mock_sleep.o" "build/test/out/c/unity.o" "build/test/out/c/foo.o" "build/test/out/c/cmock.o" -o "build/test/out/test_foo.out" -l-lm'
```

Note how the linker flag is generated. If I just build my own gem from git, then it all works fine:

```
--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  5
PASSED:  5
FAILED:  0
IGNORED: 0
```

It looks like it's time to tag `0.29.2` perhaps? I can't use the gem as is for automated testing on e.g. TravisCI or Azure Pipelines

**Comment by felipebalbi** [comment]
Hi,

a gentle reminder of this ticket.

Cheers

**Comment by Letme** [comment]
Its nice that its a bug, but on the other hand how do you have the config?  Instaed of `-lm` you could just put `m` and the `-l` seems like it is pre-pended.

**Comment by felipebalbi** [comment]
Right, and that's what I have :-). It adds another `-l` for some reason. Works fine if I use Ceedling `HEAD`
