### ISSUE TITLE
How add .c files in compilation which do not exist in src directory 

### ISSUE THREAD

**Issue by hemalbhatt26** [ThrowTheSwitch/Ceedling#482]
I am new to ceedling. I am using ceedling in my project.
I am facing an issue when I run ceedling. I have one .c FIle which I need to test , That file exists in /src directory, but in that file, one API called which is defined in another c file, and this c files path is /src/services.
Now I don't want to mock this API and I want to use real API instead.
So I have added that C files path in my yml file as below.
  :source:
    - src/**
    - src/services/**
but when I run ceedling then it is giving me an error like an undefined reference to that API, and the .c file where this API is Defined is also not compiled when ceedling executed.

I want to know how I can compile another c file that exist in another path then the /src path.

**Comment by mvandervoord** [comment]
You've done the right thing. By adding it to the list of source directories, Ceedling will be able to find it. 

The next (and hopefully last) step is that you need to tell Ceedling that it NEEDS that file for this particular test. You do that by #include-ing that files' corresponding header file in the test itself. Once it sees that you are #include-ing both of the files, it will look for both and compile each of them to include in that unit test executable.

**Comment by hemalbhatt26** [comment]
Hi mvandervoord,
Thanks for your help, after adding #include to test file .c file starts compiling.
I am closing this issue, it is being resolved.
