### ISSUE TITLE
How to take all files of project for compilation in ceedling 

### ISSUE THREAD

**Issue by hemalbhatt26** [ThrowTheSwitch/Ceedling#486]
Hi I have started using Ceedling in my project fot making test coverage.
My Project is containing too many files, third party code as well.
If I take one source C file, create Test_source file and compile test_source c file then it gives linker Error because source c file contains different API calls, and These APIs are defined in other .c Files, there are many such Dependent .c files for source .c File to be tested.

Currently, I have to add .c files in compilation using TEST_FILE(); in test_source file because header files of similar name of source file is not available in project. 
But there are many files dependent c source files So it is taking more amount of time for adding dependent c files manually. and it increases size of test_source file, because there is a large number of dependent source files.
I had tried with setting label  :auto_link_deep_dependencies: TRUE  but still it gives compilation error.
If we use makefile then we can find source .c files and also we can compile all source files using several operations.

Is there any way in which first I can compile all source files of the project so I don't need to provide dependent files manually to Test_source file?

**Comment by mvandervoord** [comment]
Am I understanding that you want to avoid using mocking and compile ALL dependencies in every "unit" test?

**Comment by hemalbhatt26** [comment]
Hi Mark,
Yes, I need to add real APIs instead of mock APIs.
In my project, I want to only mock the Low-level APIs which contain hardware dependency.

**Comment by mvandervoord** [comment]
That makes sense when testing the units that use those low-level api's... in fact, you would only need to include a mock of the headers that a particular unit actually talks to.

Each unit gets compiled into its own test executable, therefore most often you will only want to include a single source file (the one being tested) with mocks of anything that this module requires. Done any other way, it quickly gets to a point where you can't successfully test it (or at least not UNIT test it... systems tests work in this way).
