### ISSUE TITLE
16-bit integer division issue with Ceedling that works with Unity

### ISSUE THREAD

**Issue by nono313** [ThrowTheSwitch/Ceedling#488]
I have been running Unity based unit tests for a few months now using a simple Makefile.

I am trying to move to using Ceedling but one of my test that passed on Unity with Makefile now fails with Ceedling :

```
  int16_t a = 4864;
  int16_t b = 1080;
  int16_t c = 1000;
  int16_t d = 4442;
  int16_t e = 1100;
  int16_t res = a + (b - c) * (d - a)/(e - c);
  TEST_ASSERT_EQUAL_INT16(4526, res);
```
Any idea what could cause this issue ?

**Comment by respic** [comment]
What compilers or compiler flags did you use in those two test runs: Unity vs. Ceedling?

The "devil" might hide in the signed integer division:

`(b - c) * (d - a)/(e - c) = 80 * (-422) / 100 = (-33760) / 100`

Note that signed integer division in C89 is implementation-defined:
> If either operand is negative, whether the result of the / operator is the largest integer less than the algebraic quotient or the smallest integer greater than the algebraic quotient is implementation-defined, as is the sign of the result of the % operator.

Whereas C99 seems to have chosen the FORTRAN way of truncation towards zero.

See:
[What is the behavior of integer division?](https://stackoverflow.com/a/3604984)

**Comment by nono313** [comment]
Thanks for the information. My Makefile defines `-std=gnu99` as compiler flag.

For Ceedling, I have the following in my configuration :
```
:flags:
  :test:
    :compile:
      :*:
        - -std=gnu99
```

Should it be enough to get the same behavior on both ?

I should add that I am running Unity / Makefile locally on my Machine (through CygWin) and Ceedling in the madsciencelab docker container.

**Comment by mvandervoord** [comment]
If you don't mind checking, `:flags` is a seldom-used feature with Ceedling. I *believe* it's working, but you can verify by calling `ceedling verbosity[4] test:all` and verifying that the flag IS getting added during each compilation step.

If it is, I'd be curious to see which version of gcc is being run on each platform. It's possible there is a difference there?

**Comment by nono313** [comment]
Oh, you are right, it seems that the options are not actually passed to gcc.

Sorry for that. Could you tell me what the preferred way is to pass arguments to gcc with ceedling ? And what is the `flag:` feature suppose to do if it does not work like I expected it ?

**Comment by mvandervoord** [comment]
I believe you're using it correctly. I'm wondering if that Ceedling feature is broken. I'm going to try it over here and see if I can figure out what is happening...

**Comment by nono313** [comment]
Oh, you are right, it seems that the options are not actually passed to gcc.

Sorry for that. Could you tell me what the preferred way is to pass arguments to gcc with ceedling ? And what is the `flag:` feature suppose to do if it does not work like I expected it ?

**Comment by mvandervoord** [comment]
On my system, using Ceedling `0.29.1` and `0.30.0` it's working with the `:flags` snippet you have above. One thing to be careful of is to use `compile` instead of `compiler`, but you already have that correct. Another thing people commonly mess up is the dash-space-dash notation for listing the arguments... but you have that correct too.

On each compile step (not link), it's putting the `-std=gnu99` directly after `gcc` in the full command line. 

Double check the yaml file notation for the `:flags:`, double-check that the flag definitely isn't getting inserted?

I'm getting docker fired up so that I can try it on the madsciencelab as well.

**Comment by nono313** [comment]
After looking at the verbose output again, it seems that the std argument is indeed passed but not at all stages : 

```
Test 'test_temp_monitor.c'
--------------------------
> Shell executed command:
'gcc -E -MM -MG -I"test" [...] "build/temp/_test_temp_monitor.c"'
> Produced output:
_test_temp_monitor.o: build/temp/_test_temp_monitor.c \
 /usr/local/bundle/gems/ceedling-0.29.1/vendor/unity/src/unity.h \
 /usr/local/bundle/gems/ceedling-0.29.1/vendor/unity/src/unity_internals.h \
 @@@@unity.h temp_monitor.h @@@@temp_monitor.h

> Shell executed command:
'gcc -E -I"test" -I"test/support" -I"." [...] "test/test_temp_monitor.c" -o "build/test/preprocess/files/test_temp_monitor.c"'

Compiling test_temp_monitor.c...
> Shell executed command:
'gcc -std=gnu99 -fshort-enums -w -Wall -mno-ms-bitfields [...] -g -c "test/test_temp_monitor.c" -o "build/test/out/c/test_temp_monitor.o" -MMD -MF "build/test/dependencies/test_temp_monitor.d"'

Linking test_temp_monitor.out...
> Shell executed command:
'gcc "build/test/out/c/test_temp_monitor_runner.o" "build/test/out/c/test_temp_monitor.o" "build/test/out/c/unity.o" "build/test/out/c/temp_monitor.o" "build/test/out/c/cmock.o" -o "build/test/out/test_temp_monitor.out"'
```

Maybe should I add the options for the other stages via the `:flags:` section ?

**Comment by mvandervoord** [comment]
You can if you like. That first call is using gcc to generate dependencies. It's not actually compiling anything. So I don't *think* it should matter for this situation?

That brings us back to your original problem, though: We've proven that you're compiling for gnu99 for both platforms, but you're seeing a difference in behavior.

I'm wondering if the issue is when it gets this far:

```
(-33760) / 100
```

The number `-33760` isn't a legal `int16_t` value... it's overrun. 

What happens if you update the line to look like the following. I would expect it to become consistent across platforms, since it forces both platforms to upcast the multiply and divide to `int32_t` 's which can handle the full numbers, before downcasting the result back to `int16_t`

```
int16_t res = a + (int16_t)( (int32_t)(b - c) * (int32_t)(d - a)/(e - c) );
```

**Comment by respic** [comment]
oh, I tried switching to int32_t. The same result. I think compiler converts operands to int32_t quietly.

**Comment by nono313** [comment]
I tried it also and got the same error on my side.

**Comment by mvandervoord** [comment]
What is the failure you're getting?

```
  int16_t a = 4864;
  int16_t b = 1080;
  int16_t c = 1000;
  int16_t d = 4442;
  int16_t e = 1100;
  int16_t res = a + (b - c) * (d - a)/(e - c);
  // 4864 + (1080 - 1000) * (4442 - 4864) / (1100 - 1000)
  // 4864 + (80) * (-422) / (100)
  // 4864 - 33760 / 100
  // 4864 - 337
  // 4527
  TEST_ASSERT_EQUAL_INT16(4526, res);
```

It seems like the answer should be 4527 as the divide in C truncates instead of rounds if we're using C99?

**Comment by nono313** [comment]
The issue I have is that my previous setup with Unity / Makefile give me 4526 so I assumed I would get the same with Ceedling inside docker.

As both systems build with std=gnu99, I don't really see why there is a difference.

My local Makefile setup uses GCC 9.3.0 while the docker image seems to be using GCC 6.4.0. Maybe there is something going on here...

**Comment by respic** [comment]
So, it looks like the newer GCC 9.3.0 gives you Non-C99 behavior?

**Comment by nono313** [comment]
I guess it's the other way around : GCC 9.3.0 gives me what @mvandervoord showed is the right C99 behavior.

It's GCC 6.4.0 that should have given me 4527 from the start.

Any reason as to why such an old GCC version is being used in the docker image of ceedling ?

**Comment by respic** [comment]
With gcc version 9.2.0 (MinGW.org GCC Build-20200227-1) I am getting the valid C99 result **4527**

**Comment by mvandervoord** [comment]
I agree. It's strange that there is a difference here. But I also agree that it's most likely caused by differences in the compiler. I can't imagine how Ceedling would effect this (once we were sure we're passing the same flags, anyway).

I don't have a good answer for why the madsciencelab is using such an old version of gcc. I've made myself a note to check that out.

**Comment by respic** [comment]
Nathan, you said that 
> I have been running Unity based unit tests for a few months now using a simple Makefile.

And you've been getting 4526 (ASSERT with 4526 passed). And:
> My local Makefile setup uses GCC 9.3.0 while the docker image seems to be using GCC 6.4.0.

So, that means that GCC 9.3.0 (local Makefile setup) gives you 4526, not the other way around. Am I missing something?

**Comment by nono313** [comment]
Oh yes, sorry you're right. 
I'll see if I can test other GCC version (maybe an update, not sure which GCC version is the latest).

**Comment by respic** [comment]
BTW, what machine (CPU) you use to compile your local Makefile setup? Is it standard Intel?

**Comment by nono313** [comment]
The Makefile runs within CygWin on a Windows 10 Intel based machine

**Comment by respic** [comment]
Weird... I have GCC 9.2.0 and am getting 4527:

>   "Expected 4526 Was 4527"

**Comment by nono313** [comment]
I did an additional test : with Cygwin calling directly `gcc -std=gnu99` on a simple main.c file with the integer division code, I do get 4527.

But my Makefile running the unit tests with Unity gives 4526

So it's definitely not an issue with Ceedling, but still a strange behavior. 

I'll try building a very small Makefile to test that again without Unity...

**Comment by respic** [comment]
I don't have any experience with standalone Unity. Does Unity take GCC options from the Makefile? Or it has some separate config file?

**Comment by respic** [comment]
Nathan, could you list here your Makefile?

**Comment by nono313** [comment]
Alright, I can't believe why I'm seeing.

I'm really sorry guys, there is absolutely nothing wrong here except me.

The unity tests I was running with my Makefile setup were written by hand and I just noticed that the test that included the computation was missing from the Runner.c file. So when I was running my tests locally I was seeing no issue with my ASSERT only because the test was not actually executed...

Thank you very much guys and please me once again.

**Comment by mvandervoord** [comment]
No problem. We've all made similar mistakes. 

I'm glad it makes sense in the end. I always worry when we can't find a root cause.

Shameless plug: This is a reason to use Ceedling, in that it automatically makes runners for you. :)
