### ISSUE TITLE
Getting NoMemoryError: failed to allocate memory while run ceedling on project

### ISSUE THREAD

**Issue by hemalbhatt26** [ThrowTheSwitch/Ceedling#490]
Hi I am running ceedling on my project , Project contains some of large APIs.
While making test cases using ceedling it gives me an error related to memory.
Getting NoMemoryError: failed to allocate memory.
what can be the reason for such errors and how we can solve this issue?

once this error arrives then I  am not able to run Ceedling again,  it gives an error for denied permission to access .out file.
For run ceedling again I have to close and open MSYS terminal again.

**Comment by mvandervoord** [comment]
Wow. I've never tried to process a file so large that Ruby itself runs out of memory. 

Does it seem to be while mocking a particular header? Do you need that full API mocked? (I strongly suspect if it's so large that Ruby can't even process the file, then creating a mock of it is unlikely to be small enough to compile and run?). Maybe you want to create a smaller header or headers which contain just the parts you actually need mocked, and mock those instead. The release code can still use the large header... you'd just have smaller headers for more precise mocking.

**Comment by hemalbhatt26** [comment]
Hi Mark,
The issue was in code, one while loop was used and, due to some improper operation while loop was not breaking down that's why the issue of memory was occurring.
Thanks for your help and support.
