### ISSUE TITLE
GCov HTML Report Generation Issue

### ISSUE THREAD

**Issue by dhananjaysbg** [ThrowTheSwitch/Ceedling#495]
I am facing issue in GCOV report generation, Please find the below details of my folder structure and gcov configuration in yml file.

Project Folder Structure
-----------------------------------
Application
|->include
|->Src
   |->SystemConfiguration(SystemConfigurationUtils.c)
    ->UnitTestProjectDir
	  |->build
      |->src(TestSystemConfigurationUtils.c)
      |->test	
      |->project.yml	  
	
	
GCov Configuration
----------------------------------
:gcov:
    :html_report: TRUE
    :html_report_type: detailed
    :html_medium_threshold: 70
    :html_high_threshold: 85
    :xml_report: FALSE
	:report_root: "D:/Application"            
    :report_exclude: "^build|^vendor|^test|^support"
    :report_include: "D:/Application/Src/SystemConfiguration"
	
Gcovr is reporting below error 
------------------------------------------
Parsing coverage data for file Y:\Application\Src\SystemConfiguration\SystemConfigurationUtils.c
Filtering coverage data for file Y:\Application\Src\SystemConfiguration\SystemConfigurationUtils.c
Gathered coveraged data for 0 files

Please help me to resolve this issue.

**Comment by CezaryGapinski** [comment]
Based on your config I can guess that you are not using ceedling from the latest release (v0.30.0).
Nevertheless you should reconsider your `:report_root:` path and `:report_exclude:` filter.
```
Parsing coverage data for file Y:\Application\Src\SystemConfiguration\SystemConfigurationUtils.c
Filtering coverage data for file Y:\Application\Src\SystemConfiguration\SystemConfigurationUtils.c
Gathered coveraged data for 0 files
```
As you can see in your output report drive `Y:\` is used but your `:report_root:` path and `:report_exclude:`  pointing out to `D:\` drive.

When it is a symlink, then it can cause a problem, as it is stated in [gcovr Filters for symlinks section in the documentation](https://gcovr.com/en/stable/guide.html#filters-for-symlinks)

**Comment by dhananjaysbg** [comment]
i removed symlink then it is working. I would like to add multiple filter to include in the report but like below it is not considering. Can you help me on this it would be good.
:report_include: "D:/Application/Src/SystemConfiguration/src | D:/Application/Src/OtherFolder/"
