### ISSUE TITLE
Source file is not included when building

### ISSUE THREAD

**Issue by JanErikFoss** [ThrowTheSwitch/Ceedling#510]
Hi,

I've been struggling with "Undefined symbols" errors for a while, and eventually decided to test with an empty project.

Can anyone tell me why ceedling won't include and compile otherFile.c?
I haven't even touched the project.yml file, so src path is "src/**".
Happens on both macos and linux.
I'm pretty sure I must have missed something crucial, but I just can't seem to solve this.

Steps to reproduce:

> ceedling new ceed
> cd ceed
> ceedling module:create[fileToTest]
> touch src/otherFile.c src/otherFile.h

```
// test_fileToTest.c
#include "fileToTest.h"
void setUp(void) {}
void tearDown(void) {}
void test_fileToTest(void) {
    int res = funcToTest();
}

// fileToTest.c
#include "otherFile.h"
void funcToTest() {
  otherFunc();
}

// fileToTest.h
void funcToTest();

// otherFile.c
void otherFunc() {}

// otherFile.h
void otherFunc();
```

**Full error:**

```
> ceedling test:all


Test 'test_fileToTest.c'
------------------------
Generating runner for test_fileToTest.c...
Compiling test_fileToTest_runner.c...
Compiling test_fileToTest.c...
Linking test_fileToTest.out...
Undefined symbols for architecture x86_64:
  "_otherFunc", referenced from:
      _funcToTest in fileToTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: Shell command failed.
> Shell executed command:
'gcc "build/test/out/c/test_fileToTest_runner.o" "build/test/out/c/test_fileToTest.o" "build/test/out/c/fileToTest.o" "build/test/out/c/unity.o" "build/test/out/c/cmock.o" -o "build/test/out/test_fileToTest.out"'
> And exited with status: [1].


NOTICE: If the linker reports missing symbols, the following may be to blame:
  1. Test lacks #include statements corresponding to needed source files.
  2. Project search paths do not contain source files corresponding to #include statements in the test.
  3. Test does not #include needed mocks.

rake aborted!

/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/generator.rb:151:in `rescue in generate_executable_file'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/generator.rb:137:in `generate_executable_file'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/rules_tests.rake:39:in `block in <top (required)>'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/task_invoker.rb:107:in `invoke_test_results'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/test_invoker.rb:124:in `block in setup_and_invoke'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/test_invoker.rb:51:in `setup_and_invoke'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/bin/ceedling:346:in `block in <top (required)>'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/bin/ceedling:333:in `<top (required)>'
/usr/local/bin/ceedling:23:in `load'
/usr/local/bin/ceedling:23:in `<main>'

Caused by:
ShellExecutionException: ShellExecutionException
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/tool_executor.rb:88:in `exec'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/generator.rb:136:in `generate_executable_file'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/rules_tests.rake:39:in `block in <top (required)>'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/task_invoker.rb:107:in `invoke_test_results'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/test_invoker.rb:124:in `block in setup_and_invoke'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/test_invoker.rb:51:in `setup_and_invoke'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/bin/ceedling:346:in `block in <top (required)>'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/bin/ceedling:333:in `<top (required)>'
/usr/local/bin/ceedling:23:in `load'
/usr/local/bin/ceedling:23:in `<main>'
Tasks: TOP => build/test/results/test_fileToTest.pass => build/test/out/test_fileToTest.out
(See full trace by running task with --trace)
ERROR: Ceedling Failed
```

**Comment by mvandervoord** [comment]
Hi.

Ceedling learns what files you want to compile together by looking at the
headers included in the test. Since you've only included "fileToTest.h", it
only attempts to compile "fileToTest.c" with your test file.

To get it to include the REAL otherFile.c, you can just add #include
"otherFile.h" to the test. If instead you'd like to test against a mock,
include "mock_otherFile.h"

Mark

**Comment by JanErikFoss** [comment]
Thank you the quick response, that clears it up!

But is there no way to avoid having to include all dependencies in the test itself?
Can I configure it to recursively find matching source files instead of only doing it in the test file?
Or if that isn't possible, can I configure it to include all source files in all tests?

**Comment by JanErikFoss** [comment]
Actually I've thought some more about it and I think this makes a lot of sense. 
Thanks again for the quick response!

**Comment by mvandervoord** [comment]
Neither of those things are automatic. That's actually intentional. 

One of the goals of unit testing is to promote separation between modules. By forcing the user to include all the headers, it's clear what dependencies it still has. This is self documenting and sometimes illuminating.

This also allows us flexibility in what we test. For each of the modules that this module interacts with, you have the choice to use the real or mock interface. This allows you to focus on testing one unit at a time, without needing to pull in all the dependency chain. This promotes much more focused and thorough tests.

Does that make sense?

**Comment by JanErikFoss** [comment]
Definitely, I'm excited to get started!

**Comment by homedad** [comment]
At first this felt like a deficit, but now I am using it to my advantage. By breaking up a module into smaller pieces, and giving each a header file, I'm able to limit the code brought into each test file, and I don't have to create mocks for things I'm not testing.
