### ISSUE TITLE
Using Multiple Plugins: FFF and CMOCK

### ISSUE THREAD

**Issue by DPastl** [ThrowTheSwitch/Ceedling#516]
Hello,

We're currently in the process of merging libraries from an older code base that was written using CMOCK and UNITY with one that was written with ceedling and the Fake Function Framework.  What we're running into is that the older CMOCK tests will not run properly unless the fff plugin is disabled.

Is there a way to run both, or select the correct mocking framework to use for particular files?

Thanks!

**Comment by EighthMayer** [comment]
Hello DPastl!

I believe the only way is to use two separate Ceedling projects, one with CMock and other with FFF. When enabled, FFF plugin replaces CMock's mock generation, and there is no way to control enabled plugins for each individual test suite.

**Comment by isoment01** [comment]
> Hello DPastl!
> 
> When enabled, FFF plugin replaces CMock's mock generation, and there is no way to control enabled plugins for each individual test suite.
> 
> I believe the only way is to use two separate Ceedling projects, one with CMock and other with FFF. I think you can have two project yml files in the same directory and tell Ceedling which one to use. You can use different prefixes for test suite files to differentiate which of them should use CMock and which FFF.

How can I tell Ceedling which one to use ? -_-

**Comment by EighthMayer** [comment]
> How can I tell Ceedling which one to use ? -_-

Well, in theory you just need to [enable the FFF plugin in your project.yml](https://github.com/ElectronVector/fake_function_framework#enable-the-plug-in).

But currently the version of plugin which is shipped with Ceedling is broken, so you also need to [replace it with the latest version](https://github.com/ElectronVector/fake_function_framework#get-the-latest-version-of-this-plugin).

**Comment by isoment01** [comment]
> > How can I tell Ceedling which one to use ? -_-
> 
> Well, in theory you just need to [enable the FFF plugin in your project.yml](https://github.com/ElectronVector/fake_function_framework#enable-the-plug-in).
> 
> But currently the version of plugin which is shipped with Ceedling is broken, so you also need to [replace it with the latest version](https://github.com/ElectronVector/fake_function_framework#get-the-latest-version-of-this-plugin).

Hmm, If I duplicate my current project.yml which is not enabled FFF in it (in this case Cmock is active) and then, If I enable FFF in second one, can I use these two framework together for a module??

**Comment by EighthMayer** [comment]
> Hmm, If I duplicate my current project.yml which is not enabled FFF in it (in this case Cmock is active) and then, If I enable FFF in second one, can I use these two framework together for a module??

Yes, but it won't be as seamless as you may hope. You'll have to make two separated test suites (in different folders or with different file name prefixes, so one will be used by your first project.yml, and the second by second project.yml), one of which will be using CMock, and the second will be using FFF plugin. You currently can't mix these mocking frameworks in a single project.yml or test suite (I mean a file with tests by this), hence the separation.
