### ISSUE TITLE
Using vendored version in Travis

### ISSUE THREAD

**Issue by joustava** [ThrowTheSwitch/Ceedling#517]
Hello, I'm new to ceedling and the whole unity ecosystem, looking great.

I have a local seedling setup for a project and set it up with the extra info in https://github.com/ThrowTheSwitch/Ceedling#bonding-your-tools-and-project.
On my host machine I can run all tests like './ceedling'.

On travis however it doesn't seem to work and my build fails with
``` 
`require': cannot load such file -- constructor 
```

my basic travis.yml looks like:
```
language: ruby c

script:
  - ./ceedling
```
it does not install gems as I assumed ceedling is vendored already with the project.

of course this travis.yml works
```
language: ruby c

install: gem install ceedling

script:
  - ceedling
```

Bu I was wondering about the bonding option, I guess I missed something obvious.

**Comment by mvandervoord** [comment]
Hi.

Unfortunately a vendored installation gives a vendored version of Ceedling, but not all of its dependencies... so the gems Ceedling depends on are still required to be installed. This is something I'd like to improve in the future, as this severely limits the usefulness of vendoring it.

**Comment by joustava** [comment]
Ah, ok, then it makes sense this won't yet work.

Is [this the place where this functionality might be added](https://github.com/joustava/Ceedling/blob/918ca8c7b8cbcada23bca1283d6e513e1ef5f573/bin/ceedling#L120)?
`bundle cache` or `bundle package` seem to be options for tackling this?
 Are there any foreseen issues?

**Comment by art-of-dom** [comment]
Part of my clean up a while ago most likely caused this. We used to have constructor inside ceedling instead of installing the gem itself. It's possible extra steps in the set up for a local, but if I remember correctly it was a bit more complex than than when it was integrated in the repo and just using the gem simplified a lot if it.


In the mean time as a partial solution instead of installing ceedling, try just installing constructor.
```
language: ruby c

install: gem install constructor

script:
  - ceedling
```

**Comment by joustava** [comment]
@art-of-dom thanks for the hint!
```yaml
language: ruby c

install: 
  - gem install constructor
  - gem install ceedling

script:
  - ceedling
```

Made it work by installing both.
