### ISSUE TITLE
Junit test time flag

### ISSUE THREAD

**Issue by jaymedq** [ThrowTheSwitch/Ceedling#519]
Hi all,

We are using the `junit_tests_report` plugin to extract some embedded unit test results and store them into a database,
so i realized that the 'time' tag is always 0 for testcases as bellow:

```
<?xml version="1.0" encoding="utf-8" ?>
<testsuites tests="50" failures="0" skipped="5" time="10.870826">
  <testsuite name="UnitTestXXX" tests="23" failures="0" skipped="0" time="7.566558">
    <testcase name="test_XXX" time="0.000000"/>
    <testcase name="test_XXX" time="0.000000"/>
```

It's really important to us knowing how long each test takes to run, in order to certify the well functioning of our project.

I don't know much about ruby but i can say that the plugin uses `unity_test_time` extracted from `generator_test_results.rb`.
How can we make this variable carry the test duration, so the testcase time flag can show this info?

Thank you.
Jayme

**Comment by art-of-dom** [comment]
I'm pretty sure this is doable by adding UNITY_INCLUDE_EXEC_TIME to your defines in your project.yml.

```
:defines:
  :commmon: &common_defines
    [
        TEST, UNITY_INCLUDE_EXEC_TIME
    ]
  :test:
    - *common_defines
  :test_preprocess:
    - *common_defines
    - TEST_PP

```



Having tweaked this is the past I know testsuite time is done by Ceedling in ruby and the testcase time is controlled by Unity timing mechanisms in C so it needs to be compiled in.
