### ISSUE TITLE
Empty HTML report output on gcovr

### ISSUE THREAD

**Issue by sebahansen** [ThrowTheSwitch/Ceedling#523]
Hi!
I'm having the following issue when trying to generate a HTML report with gcov
I'm currently using ceedling 0.30.0, and i downgraded gcovr version to 4.1 as i saw on issue #449 it could fix some compatibility issues.
I have enabled gcov on the .yml file, and my configuration is this:
:gcov:
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed
  :gcovr:
    :report_root: ".."

When running:  `ceedling gcov:all utils:gcov`

I get the following output:

/var/lib/gems/2.5.0/gems/ceedling-0.30.0/lib/ceedling/system_wrapper.rb:25: warning: Insecure world writable dir /mnt/c in PATH, mode 040777

Test 'test_1.c'
---------------------------
Running test_1.out...

Test 'test_2.c'
----------------------
Running test_2.out...
Creating a gcov HTML report in 'build/artifacts/gcov'... Done in 1.535 seconds.

-----------------
GCOV: TEST OUTPUT
-----------------
[test_2.c]
  - "Buffer error"
  - "Buffer error"
  - "Buffer error"
  - "Buffer not large enough for decompressed data"

--------------------------
GCOV: OVERALL TEST SUMMARY
--------------------------
TESTED:  14
PASSED:  14
FAILED:   0
IGNORED:  0

---------------------------
GCOV: CODE COVERAGE SUMMARY
---------------------------
util1.c Lines executed:91.89% of 185
util1.c Branches executed:92.68% of 164
util1.c Taken at least once:80.49% of 164
util1.c Calls executed:100.00% of 18

util2.c Lines executed:0.00% of 36
util2.c Branches executed:0.00% of 12
util2.c Taken at least once:0.00% of 12
util2.c Calls executed:0.00% of 22

util3.c Lines executed:96.43% of 56
util3.c Branches executed:100.00% of 42
util3.c Taken at least once:76.19% of 42
util3.c Calls executed:100.00% of 12

util4.c Lines executed:16.50% of 491
util4.c Branches executed:24.26% of 338
util4.c Taken at least once:18.05% of 338
util4.c Calls executed:0.00% of 9

util5.c Lines executed:42.70% of 89
util5.c Branches executed:55.00% of 40
lutil5.c Taken at least once:40.00% of 40
util5.c Calls executed:15.38% of 26

Could not find coverage results for obsw/src/main.c

But when opening **GcovCoverageResults.html**  i get:

![SCSH](https://user-images.githubusercontent.com/55140845/95782984-4fa1af00-0ca7-11eb-8715-2b7ce5dcdadd.png)

Thanks in advance!

**Comment by georgeslabreche** [comment]
@sebahansen you might want to look into setting the` :report_include` and `:report_exclude: `configuration properties. Especially the former.

**Comment by zarkokv036** [comment]
have you find solution for this problem? If you found can you upload .yaml file?

**Comment by jifengtx** [comment]
`---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  # :release_build: TRUE
  :test_file_prefix: Test

#:release_build:
#  :output: TempSensor.out
#  :use_assembly: FALSE

:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
  :source:
     - ../source/Component/app/App_Sensor/hmi/inc/**
     - ../source/Component/app/App_Sensor/hmi/src/**
      - +:source/Component/hal/hal_base_lib/src/stm32wb_hal_base_lib/Driver/Inc/stm32wbxx_hal_gpio.h
  :include: 
    - +:../source/Component/hal/hal_base_lib/src/stm32wb_hal_base_lib/CMSIS/Device/ST/STM32WBxx/Include/**
    - +:../source/Component/hal/cmsis_headers/src/cmsis_headers/Core/Include/**
    - +:../source/Component/rtos/Source/include/**
    - +:../source/Component/sys_manager/src/**
    - +:../source/Component/hal/hal_base_lib/src/stm32wb_hal_base_lib/Driver/**
    - +:../source/Component/rtos/**
    - +:../source/Component/hal/hal_base_lib/src/board/**     
    - +:../source/Component/hal/cmsis_headers/src/cmsis_headers/Driver/Include/**
    - +:../source/Component/hal/hal_base_lib/src/stm32wb_hal_base_lib/Driver/Inc/**
    - +:../source/Component/hal/hal_base_lib/src/stm32wb_hal_base_lib/Driver/Src/**


:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines
    - STM32WB55xx
    - UNIT_TEST
    - FREERTOS
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
    
:gcov:
  :html_report: true
  :html_report_type: detailed
  :xml_report: true
  :gcovr:
    :xml_pretty: true
    :cobertura_pretty: true

:libraries:
  :system:
    - m
    
    
:tools:
   :test_compiler:
  # :subprojects_compiler:     
    # :executable: compiler              #exists in system search path
    # :name: 'acme test compiler'
    # :arguments:
      # - -mcpu=stm32WB55
      # - -x c
      # - -c
      # - "${1}"
      # - -o "${2}"
      # - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      # - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      # - -Wall
      # - -Werror  # We can't keep this on during test becuase of a CMock pointer issue
      # - -Os
      # - -mlarge-code
      # - -mlarge-arrays
  # :test_linker:
    # :executable: arm-none-eabi-gcc
    # :arguments:
      # - -mcpu=stm32WB55
      # - ${1}
      # - -o "./build/release/TestBuild.out"
      # - -Wl,-Tp24HJ128GP202.gld,-Map=./build/release/TestOutput.map,--report-mem
  # :test_fixture:
    # :executable: ruby
    # :stderr_redirect: :win #inform Ceedling what model of $stderr capture to use
    # :arguments:
      # - test/simulation/sim_test_fixture.rb  
:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - xml_tests_report 
    - warnings_report 
    - gcov
    
...
`

**Comment by jifengtx** [comment]
[
[project.txt](https://github.com/ThrowTheSwitch/Ceedling/files/5606139/project.txt)
](url)
