### ISSUE TITLE
Ignoring tests

### ISSUE THREAD

**Issue by sison54** [ThrowTheSwitch/Ceedling#534]
Is there a way to include ignored tests in the ignored test list?

Thanks

**Comment by mvandervoord** [comment]
I'm not sure I'm understanding the question?

If you add `TEST_IGNORE()` or `TEST_IGNORE_MESSAGE(msg)` to a test, it will automatically be ignored and it should automatically be listed with the other ignored tests at the end of the test suite.

**Comment by sison54** [comment]
Ah got it, thanks. Sorry, I missed that part. I thought the function name had to be something special.

**Comment by mvandervoord** [comment]
:) No problem. I'm glad we got it cleared up.
