### ISSUE TITLE
Fix plugin config load order

### ISSUE THREAD

**Issue by tbates-redarc** [ThrowTheSwitch/Ceedling#536]
#365 broke my plugin which depended on being able to overwrite the Ceedling default values for various things.

#### The problem
Currently the configuration load order is:
1. Load `project.yml`
2. Merge Ceedling defaults (using deep_merge!)
3. Merge plugin configs (using deep_merge)
4. Merge plugin defaults (using a manual merge loop)

Prior to #365, step 3 overwrote the configuration, now it does not, making it behave essentially the same as step 4, and giving no way for a plugin to overwrite the Ceedling default values (except using custom code e.g. in the `setup` hook). The fundamental problem is that by the time we get to step 3, there's no way for the plugin to know if the value now in the config hash came from `project.yml` (and should be preserved) or from the Ceedling defaults.rb (and should be overwritten).

#### Possible solutions
1. Revert #365, and fix #208 by moving the problematic values from `module_generator/config/module_generator.yml` to `module_generator/config/defaults.yml`. This still has the problem that values in a plugin config file will overwrite values in `project.yml`
2. Rework plugin load order to allow plugin defaults to override Ceedling defaults
3. Do nothing and I work around it in my `setup` hook

Option 2 would be preferable to me, but it's not clear what the load order should be. For example, what was intended to be the difference between `myplugin/config/myplugin.yml` and `myplugin/config/defaults.yml`? When should array values be merged vs being replaced?

My requirement is simply that plugins have the ability to overwrite the Ceedling defaults (via `myplugin.yml` or `defaults.yml`, or perhaps by `defaults_myplugin.rb` if #511 is merged), ideally without also overwriting values provided by `project.yml` (the original problem in #208).

#### Proposed solution
One possible priority order is as follows, although I'm not sure whether this will break existing plugins:
1. Values in `project.yml` (or options files) have highest priority
2. Values in `plugin/config/plugin.yml` are deep_merge!d with values in `project.yml` (used if not present in project.yml, or array values combined)
3. Values in `plugin/config/defaults.yml` (or `defaults_myplugin.rb`) are non-deep merged (used only if not present in `project.yml` or a plugin's `config.yml`)
4. Values in `lib/ceedling/defaults.rb` are non-deep merged (used only if not defined in steps 1-3)

If this is acceptable, or if some amendments are provided, I'd be happy to start working on a pull request.

**Comment by mkarlesky** [comment]
See resolution in the conversation thread for PR #818.
