### ISSUE TITLE
ceedling test:build_only recognize build_only as source file

### ISSUE THREAD

**Issue by zLukas** [ThrowTheSwitch/Ceedling#542]
Hi,
I'm new to ceedling and I 've got a problem that ceedling do not recognize `test:build_only ` command.
Basing on [documetation:](https://github.com/ThrowTheSwitch/Ceedling/blob/master/docs/CeedlingPacket.md)

`ceedling:build_only` should build all of my tests files. 

instead of it, I'm getting errors `test_build_only.c not found`

![cedling_build_only](https://user-images.githubusercontent.com/20104521/102089799-fe37ac80-3e1c-11eb-8607-bf2b8becb55c.PNG)
what am I doing wrong ?

**Comment by CezaryGapinski** [comment]
Did you call `ceedling test:build_only` from directory with `project.yml` file?
I had this when I call ceedling command from directory which is not a ceedling project. You should check whether you created ceedling project correctly.

**Comment by zLukas** [comment]
Yes, I called this command from directory with ` project.yml`.
Project is set up correctly as other commands, works properly.

Should i specify some additiona settings in `project.yml` than default ones?

**Comment by mvandervoord** [comment]
Hi @zLukas -- What version of Ceedling are you using? (type `ceedling version` to find out for sure). Does it have any files to build yet? What happens when you try `ceedling files:test`?

**Comment by zLukas** [comment]
My version is 0.28.3.
![Capture](https://user-images.githubusercontent.com/20104521/102322912-16740c80-3f80-11eb-9a45-d310e6d485ad.PNG)
After i type `ceedling files:test`  all of my my 55 tests files appears.
![Capture](https://user-images.githubusercontent.com/20104521/102322972-2b50a000-3f80-11eb-9c9d-ecef6838310d.PNG)

**Comment by mvandervoord** [comment]
Curious. Are you running ceedling as a vendor-install or as a gem? If you're not sure, you could paste the start of your project.yml file here and we could help.

**Comment by CezaryGapinski** [comment]
@mvandervoord Based on commit e3f1ffc4faa35d8025d0f5faee888b266f17d476 I think `test:build_only` feature was released in version 0.29.0, so @zLukas need to update ceedling :).

**Comment by mvandervoord** [comment]
@CezaryGapinski -- Thanks! You are correct. I was sidetracked by the lack of versions... but I think that is also a bug that was fixed since then.

**Comment by zLukas** [comment]
Ok , update to 0.30.0 solved the problem. 
Thanks for help.
