### ISSUE TITLE
ERROR: Config filepath

### ISSUE THREAD

**Issue by Sezginnn** [ThrowTheSwitch/Ceedling#544]
Hello, firstly, sorry if I don't use ceedling language correctly, this is all very new. 
I want to run STM32CubeIDE(eclipse based)with ceedling but I get an error I installed Ruby, MinGW and Ceedling. I'm creating a project in ceedling but I am getting this error. This error occurs when test is running and creating modules. Can you help me on this issue?
Thank you
*****

C:\>ceedling new --local test_ceedling
Welcome to Ceedling!
      create  C:/test_ceedling/vendor/ceedling/plugins
      create  C:/test_ceedling/vendor/ceedling/plugins/beep/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/beep/lib/beep.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/bullseye/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/bullseye/assets/template.erb
      create  C:/test_ceedling/vendor/ceedling/plugins/bullseye/bullseye.rake
      create  C:/test_ceedling/vendor/ceedling/plugins/bullseye/config/defaults.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/bullseye/lib/bullseye.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/colour_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/colour_report/lib/colour_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/command_hooks/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/command_hooks/lib/command_hooks.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/compile_commands_json/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/compile_commands_json/lib/compile_commands_json.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/dependencies/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/dependencies/config/defaults.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/dependencies/dependencies.rake
      create  C:/test_ceedling/vendor/ceedling/plugins/dependencies/lib/dependencies.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/Rakefile
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/project.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/rakefile.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/bar.c
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/bar.h
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/custom_types.h
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/display.c
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/display.h
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/event_processor.c
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/event_processor.h
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/foo.c
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/foo.h
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/subfolder/zzz.c
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/src/subfolder/zzz.h
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/test/test_event_processor.c
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/examples/fff_example/test/test_foo.c
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/lib/fake_function_framework.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/lib/fff_mock_generator.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/spec/fff_mock_header_generator_spec.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/spec/fff_mock_source_generator_spec.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/spec/header_generator.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/spec/spec_helper.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/fake_function_framework/src/fff_unity_helper.h
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/assets/template.erb
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/config/defaults.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/gcov.rake
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/lib/gcov.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/lib/gcov_constants.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/lib/gcovr_reportinator.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/lib/reportgenerator_reportinator.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/gcov/lib/reportinator_helper.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/json_tests_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/json_tests_report/lib/json_tests_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/junit_tests_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/junit_tests_report/lib/junit_tests_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/module_generator/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/module_generator/config/module_generator.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/module_generator/lib/module_generator.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/module_generator/module_generator.rake
      create  C:/test_ceedling/vendor/ceedling/plugins/raw_output_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/raw_output_report/lib/raw_output_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_gtestlike_tests_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_gtestlike_tests_report/assets/template.erb
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_gtestlike_tests_report/assets/template.erb copy
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_gtestlike_tests_report/config/stdout_gtestlike_tests_report.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_gtestlike_tests_report/lib/stdout_gtestlike_tests_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_ide_tests_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_ide_tests_report/config/stdout_ide_tests_report.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_ide_tests_report/lib/stdout_ide_tests_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_pretty_tests_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_pretty_tests_report/assets/template.erb
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_pretty_tests_report/config/stdout_pretty_tests_report.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/stdout_pretty_tests_report/lib/stdout_pretty_tests_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/subprojects/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/subprojects/config/defaults.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/subprojects/lib/subprojects.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/subprojects/subprojects.rake
      create  C:/test_ceedling/vendor/ceedling/plugins/teamcity_tests_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/teamcity_tests_report/config/teamcity_tests_report.yml
      create  C:/test_ceedling/vendor/ceedling/plugins/teamcity_tests_report/lib/teamcity_tests_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/warnings_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/warnings_report/lib/warnings_report.rb
      create  C:/test_ceedling/vendor/ceedling/plugins/xml_tests_report/README.md
      create  C:/test_ceedling/vendor/ceedling/plugins/xml_tests_report/lib/xml_tests_report.rb
      create  C:/test_ceedling/vendor/ceedling/lib
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/build_invoker_utils.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/cacheinator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/cacheinator_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/cmock_builder.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/configurator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/configurator_builder.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/configurator_plugins.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/configurator_setup.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/configurator_validator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/constants.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/defaults.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/dependinator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/erb_wrapper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/file_finder.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/file_finder_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/file_path_utils.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/file_system_utils.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/file_system_wrapper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/file_wrapper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/flaginator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/generator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/generator_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/generator_test_results.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/generator_test_results_sanity_checker.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/generator_test_runner.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/loginator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/makefile.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/objects.yml
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/par_map.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/plugin.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/plugin_builder.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/plugin_manager.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/plugin_manager_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/plugin_reportinator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/plugin_reportinator_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/preprocessinator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/preprocessinator_extractor.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/preprocessinator_file_handler.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/preprocessinator_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/preprocessinator_includes_handler.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/project_config_manager.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/project_file_loader.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rake_utils.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rake_wrapper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rakefile.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/release_invoker.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/release_invoker_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/reportinator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rules_cmock.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rules_preprocess.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rules_release.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rules_release_deep_dependencies.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rules_tests.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/rules_tests_deep_dependencies.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/setupinator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/stream_wrapper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/streaminator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/streaminator_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/system_utils.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/system_wrapper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/target_loader.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/task_invoker.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tasks_base.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tasks_filesystem.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tasks_release.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tasks_release_deep_dependencies.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tasks_tests.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tasks_tests_deep_dependencies.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tasks_vendor.rake
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/test_includes_extractor.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/test_invoker.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/test_invoker_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tool_executor.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/tool_executor_helper.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/verbosinator.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/version.rb
      create  C:/test_ceedling/vendor/ceedling/lib/ceedling/yaml_wrapper.rb
      create  C:/test_ceedling/vendor/ceedling/bin
      create  C:/test_ceedling/vendor/ceedling/bin/ceedling
      create  C:/test_ceedling/vendor/ceedling/vendor/c_exception/lib
      create  C:/test_ceedling/vendor/ceedling/vendor/c_exception/lib/CException.c
      create  C:/test_ceedling/vendor/ceedling/vendor/c_exception/lib/CException.h
      create  C:/test_ceedling/vendor/ceedling/vendor/c_exception/lib/meson.build
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/config
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/config/production_environment.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/config/test_environment.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_config.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_file_writer.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_plugin_array.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_plugin_callback.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_plugin_cexception.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_plugin_expect.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_plugin_expect_any_args.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_plugin_ignore.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_plugin_ignore_arg.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_plugin_return_thru_ptr.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_generator_utils.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_header_parser.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_plugin_manager.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/lib/cmock_unityhelper_parser.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/src
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/src/cmock.c
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/src/cmock.h
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/src/cmock_internals.h
      create  C:/test_ceedling/vendor/ceedling/vendor/cmock/src/meson.build
      create  C:/test_ceedling/vendor/ceedling/vendor/deep_merge/lib
      create  C:/test_ceedling/vendor/ceedling/vendor/deep_merge/lib/deep_merge.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/diy/lib
      create  C:/test_ceedling/vendor/ceedling/vendor/diy/lib/diy.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/diy/lib/diy/factory.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/colour_prompt.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/colour_reporter.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/generate_config.yml
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/generate_module.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/generate_test_runner.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/parse_output.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/run_test.erb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/stylize_as_junit.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/test_file_filter.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/type_sanitizer.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/unity_test_summary.py
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/unity_test_summary.rb
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/auto/unity_to_junit.py
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/src
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/src/meson.build
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/src/unity.c
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/src/unity.h
      create  C:/test_ceedling/vendor/ceedling/vendor/unity/src/unity_internals.h
      create  C:/test_ceedling/ceedling.cmd
      create  test_ceedling/project.yml

Project 'test_ceedling' created!
 - Execute 'ceedling help' from test_ceedling to view available test & build tasks

C:\>cd test_ceedling

C:\test_ceedling>ceedling test:all

C:\test_ceedling>ruby vendor\ceedling\bin\ceedling test:all
ERROR: Config filepath [:tools][:test_compiler][:executable]['gcc.exe'] does not exist in system search paths.
ERROR: Config filepath [:tools][:test_file_preprocessor][:executable]['gcc.exe'] does not exist in system search paths.
ERROR: Config filepath [:tools][:test_includes_preprocessor][:executable]['gcc.exe'] does not exist in system search paths.
ERROR: Config filepath [:tools][:test_linker][:executable]['gcc.exe'] does not exist in system search paths.
Traceback (most recent call last):
        5: from vendor/ceedling/bin/ceedling:330:in `<main>'
        4: from vendor/ceedling/lib/ceedling.rb:66:in `load_project'
        3: from vendor/ceedling/lib/ceedling.rb:66:in `load'
        2: from vendor/ceedling/lib/../lib/ceedling/rakefile.rb:48:in `<top (required)>'
        1: from C:/test_ceedling/vendor/ceedling/lib/ceedling/setupinator.rb:32:in `do_setup'
C:/test_ceedling/vendor/ceedling/lib/ceedling/configurator.rb:299:in `validate': unhandled exception

**Comment by Letme** [comment]
Seems like you dont have gcc.exe in your path (from wherever console you are running the commands). I assume you have gcc installed and want to run tests on your local cpu which is amd64 based?

**Comment by Sezginnn** [comment]
Yes. I installed GCC with MinGW. What I want is to integrate with STM32CubeIDE and run tests but I can't run ceedling correctly yet.

![ss](https://user-images.githubusercontent.com/76174285/102520032-4ddbd980-40a4-11eb-8659-af3354b243c5.PNG)

**Comment by Sezginnn** [comment]
Yes. I installed GCC with MinGW. What I want to integrate with STM32CubeIDE and run tests but I can't run ceedling correctly yet.
![ss](https://user-images.githubusercontent.com/76174285/102520213-7fed3b80-40a4-11eb-94e6-c3e2fe662b98.PNG)

**Comment by Sezginnn** [comment]
Yes. I installed GCC along with MinGW. What I want is to integrate with STM32CubeIDE and run tests. but at this point I can't run ceedling correctly yet. How can I add this path?
![ss](https://user-images.githubusercontent.com/76174285/102520468-c93d8b00-40a4-11eb-85b9-788a55b69cef.PNG)

**Comment by Sezginnn** [comment]
Yes that is right.I installed GCC along with MinGW. What I want is to integrate with STM32CubeIDE and run tests. but at this point I can't run ceedling properly yet. How can I add this path?
![ss](https://user-images.githubusercontent.com/76174285/102520659-f8ec9300-40a4-11eb-89d8-3011fc72619a.PNG)

**Comment by Letme** [comment]
So you are running that ceedling command from the mingw console or somewhere else? If you are in mingow console, then you might be able to find out about mingw if you write `whereis gcc` ? Usually its added to path automatically, you can also try by running for example `gcc --version` or `gcc.exe --version`. If it requires without exe, then you will need ot define custom `test_compiler` in your `project.yml`

**Comment by Sezginnn** [comment]
I forgot to write an answer. First of all thank you very much. It was not automatically added to the path. i added it manually and the issue was solved. Thanks again.

**Comment by sundar-ltts** [comment]
Hi @Sezginnn  I am facing the same issue faced by you,

**D:\Ceedling_test\ceedling_unit_test\test_add>ceedling test:all
ERROR: Config filepath [:tools][:test_compiler][:executable]['C:/Program'] does not exist on disk.
ERROR: Config filepath [:tools][:test_file_preprocessor][:executable]['C:/Program'] does not exist on disk.
ERROR: Config filepath [:tools][:test_includes_preprocessor][:executable]['C:/Program'] does not exist on disk.
Traceback (most recent call last):
        7: from C:/Ruby27-x64/bin/ceedling:23:in `<main>'
        6: from C:/Ruby27-x64/bin/ceedling:23:in `load'
        5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ceedling-0.31.0/bin/ceedling:329:in `<top (required)>'
        4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ceedling-0.31.0/lib/ceedling.rb:66:in `load_project'
        3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ceedling-0.31.0/lib/ceedling.rb:66:in `load'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ceedling-0.31.0/lib/ceedling/rakefile.rb:47:in `<top (required)>'
        1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ceedling-0.31.0/lib/ceedling/setupinator.rb:32:in `do_setup'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ceedling-0.31.0/lib/ceedling/configurator.rb:304:in `validate': unhandled exception**

Please tell which file did you added manually.
Please elaborate your solution which will really helpful to us.

Thank you in advance.

**Comment by Letme** [comment]
I think you tried to add a path to executable with spaces and without backslashes and quotes? I am afraid you need to add it to path and call the short version of it (not the full path). Maybe additional quotes would make the full path also callable.

**Comment by sundar-ltts** [comment]
Hi @Letme 

Thank you for the respone

I add only gcc path in the environment variables
C:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin

**Comment by Sezginnn** [comment]
Sorry, I just noticed your message. yes it has to be this way

**Comment by sundar-ltts** [comment]
@Sezginnn 
But still I am getting the same error
Anything else need to be done ?

**Comment by Letme** [comment]
@sundar-ltts I think in your `project.yml` you have `'C:Program Files...' `as executable instead of `gcc.exe`

**Comment by sundar-ltts** [comment]
This is my project.yml file content

---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
#  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.0
  :default_tasks:
    - test:all

#:test_build:
#  :use_assembly: TRUE

#:release_build:
#  :output: MyApp.out
#  :use_assembly: FALSE

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :libraries: []

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

# Add -gcov to the plugins list to make sure of the gcov plugin
# You will need to have gcov and gcovr both installed to make it work.
# For more information on these options, see docs in plugins/gcov
:gcov:
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []    # for example, you might list 'm' to grab the math library
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
...

**Comment by Letme** [comment]
Please make it MArkdown code block. I don't know how you added to path, but I assume `gcc --version` is working in that console? I know spaces need quotes in most cases, so most probably there is something related to how path is extracted.

**Comment by sundar-ltts** [comment]
Yes @Letme gcc version working for me

Microsoft Windows [Version 10.0.19042.928]
(c) Microsoft Corporation. All rights reserved.

C:\Users\40013109>gcc --version
gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


C:\Users\40013109>

**Comment by Letme** [comment]
So the only question is: how did you set path, because it seems like spaces are not taken into account when it is expanded (not sure this is a problem within ceedling).

**Comment by JuPrgn** [comment]
A fast fix could be to install mingw directly on C: instead of Program Files as you will not have path with spaces ?

**Comment by sundar-ltts** [comment]
![image](https://user-images.githubusercontent.com/78742653/121364043-0f3d2280-c955-11eb-9e96-71cb226cddbd.png)

**Comment by stephennacion06** [comment]
Any update on this issue? Also encountering the same problem

**Comment by mkarlesky** [comment]
Ceedling version 0.32 is nearing its release. It includes better handling for executables with spaces in their names. Specifically, it no longer makes guesses on how to handle this and reports on the problem in a clearer way.

Generally, the best approach is to concentrate on managing the search path for executables rather than specifying a full path to an executable in a Ceedling tool definition.

Options:

- Use your OS and/or shell features to modify the executable search paths so that when Ceedling spawns a shell to run your compiler, the shell can find the executable.
- Use Ceedling's environment variable features to modify executable search paths for you (`:environment` ↳ `:path`). See _CeedlingPacket_'s discussion of the `:environment` configuration section in your project file.
