### ISSUE TITLE
project.yml issue

### ISSUE THREAD

**Issue by jifengtx** [ThrowTheSwitch/Ceedling#545]
hi，
May I ask you a question? I have the idea of creating project1.yml and Project.yml files and transferring the project1.yml subpath file into project.yml file.
Is that allowed?

**Comment by Letme** [comment]
What do you want to achieve? If it is for different compilers then it is more advised to put it into targets/ subfolder and then you can call `rake test[name_of_file]` speaking from the top of my head `targets` directory could probably also be `.` as it is a setting in yml

**Comment by jifengtx** [comment]
hi,
Thank you for your help. 
I finished importing the config.yaml file under the other path in the project.yaml with "import"
![image](https://user-images.githubusercontent.com/34359893/102867898-68330000-4474-11eb-8572-0a0adbba0f17.png)
The subpath config.YAMl content is as follows
![image](https://user-images.githubusercontent.com/34359893/102868161-cd86f100-4474-11eb-8b14-f693d3d54882.png)

**Comment by jifengtx** [comment]
I want to include the submodules test, source, and include files under the subpath. Should I use **module_generator** or continue with the **"paths"** function
