### ISSUE TITLE
Ceedling chokes on bad stdout data:  "ArgumentError: invalid byte sequence in UTF-8"

### ISSUE THREAD

**Issue by recursify** [ThrowTheSwitch/Ceedling#56]
If the tests output bad utf8 data, the `shell_result[:output] =~ TEST_STDOUT_STATISTICS_PATTERN` line will choke.

Not sure what the proper fix is, but I think either scrubbing stdout to remove bad byte sequences, or at least a more indicative error would be helpful.

I have a patch, but I can't seem  to make a change to the repo without git trying to replace the line endings of every single file.  Very confused.

Anyway:

In generator_helper.rb
```
sanitized_output = shell_result[:output].dup
sanitized_output.scrub!
```

and a similar change to `unity_shell_result[:output]` in generator_test_results.rb

Original error: 
```
rake aborted!
ArgumentError: invalid byte sequence in UTF-8
/src/vendor/ceedling/lib/ceedling/generator_helper.rb:21:in `=~'
/src/vendor/ceedling/lib/ceedling/generator_helper.rb:21:in `test_results_error_handler'
/src/vendor/ceedling/lib/ceedling/generator.rb:153:in `generate_test_results'
/src/vendor/ceedling/lib/ceedling/rules_tests.rake:42:in `block in <top (required)>'
/src/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
/src/vendor/ceedling/lib/ceedling/test_invoker.rb:68:in `block in setup_and_invoke'
/src/vendor/ceedling/lib/ceedling/test_invoker.rb:32:in `each'
/src/vendor/ceedling/lib/ceedling/test_invoker.rb:32:in `setup_and_invoke'
/src/vendor/ceedling/lib/ceedling/rules_tests.rake:57:in `block (2 levels) in <top (required)>'
```

**Comment by recursify** [comment]
However - it's probably best to sanitize once, earlier in the pipeline.  Not sure where that place would be, though.

**Comment by mvandervoord** [comment]
Thanks! I have this fixed, I believe. It's in the main branch on github. It'll make it into the next gem release.
