### ISSUE TITLE
Parsing Ceedling Errors in Eclipse

### ISSUE THREAD

**Issue by pfaco** [ThrowTheSwitch/Ceedling#59]
Hello guys!

I'm trying to run my unit test directly from Eclipse.
I succesfully followed the following tutorial: http://throwtheswitch.squarespace.com/white-papers/using-eclipse-ide.html 

It's great. I just need to double click on the target to run the tests and I can see the results on the Eclipse console.

What I'm trying to achive now is for Eclipse to understand the errors and warnings output by Ceedling/Unit and display them accordingly in the "Problems" tab.

I tried enabling the stdout_ide_tests_report plugin on my project.yml, but that didn't help.

Anyone knows how to perform this? I hope to keep using the default Eclipse error parser, cause I use this same project to run Lint.

Thank you.

**Comment by pfaco** [comment]
Just to clarify: I tried the solution proposed in the tutorial, it is, using the SunShade plugin. Unfortunately this plugin doesn't seems to work in newer version of Eclipse (Mars).

The ideal solution for this would be for ceedling to allow the user to define the message format (something similar to what PC-Lint allows).

I've searched all over the documentation and the internet but couldn't find such solution.

I imagine this would be very useful for plenty of users.

**Comment by okz** [comment]
Hi, 

Instead of sunshade plugin, you could use "gnu GCC/G++ Parser", which allows you to configure the regex search patterns used.  If you are using Eclipse CDT it should already be available. 

It can be enabled through: Project Settings:C/C++ Build:Settings, error parser tab. 

good luck.

**Comment by mvandervoord** [comment]
Awesome. Thanks for the advice! I'll check into that.

**Comment by pfaco** [comment]
Thanks @okz ! 
For someone wondering, the pattern to get ceedling errors in eclipse is this: (.*?):(\d+):(.*)
