### ISSUE TITLE
Enabling FreeRTOS in the mocking/testing - Ceedling does not parse all functions listed in the header file

### ISSUE THREAD

**Issue by wdembinski** [ThrowTheSwitch/Ceedling#601]
I'm trying to enable Ceedling in my personal project which uses FreeRTOS. It seems this is a little tricky to get it working.

My source file looks as follows:

```
#include "test.h"

#include "FreeRTOSConfig.h"
#include "FreeRTOS.h"
#include "queue.h"

void TestRtos(void)
{
    // QueueHandle_t someQueue = xQueueCreate(8, 16);
    xQueueGenericSend(someQueue, NULL, 10, 0);
    // uxQueueMessagesWaiting(someQueue);
}
```

There's also a really simple test for the code above:

```
#include "unity.h"
#include "cmock.h"

#include "FreeRTOSConfig.h"
#include "FreeRTOS.h"
#include "mock_queue.h"

#include "test.h"

void setUp(void) {
    mock_queue_Init();

}

void tearDown(void) {
    mock_queue_Verify();
}

void test_Rtos(void)
{
    TestRtos();
}
```

I configured my *project.yml* to include FreeRTOS files and it looks as follows:

```
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
#  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.0
  :default_tasks:
    - test:all

#:test_build:
#  :use_assembly: TRUE

#:release_build:
#  :output: MyApp.out
#  :use_assembly: FALSE

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
    - ../build/_deps/rtos.freertos-src/portable/GCC/ARM_CM4F
    - ../build/_deps/rtos.freertos-src/include/
    - ../debug/
    - ../
  :source:
    - src/**
  :support:
    - test/support
  :libraries: []

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST
    - INC_FREERTOS_H

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
  :includes:
    - "FreeRTOS.h"
    - "FreeRTOSConfig.h"
  :includes_h_pre_orig_header:
    - "FreeRTOS.h"
    - "FreeRTOSConfig.h"
```

I'm getting an error that linker cannot find _xQueueGenericCreate_ and _xQueueGenericSend_. That's strange so I looked for _mock_queue.h_ file and it looks like Ceedling parsed only few function from the entire _queue.h_. Other not parsed functions are not event guarded by #if preprocessor statements.

Only functions marked with red circle below are parsed and added to the output _mock_queue.c_ file.
![image](https://user-images.githubusercontent.com/69972090/120930432-807a9c80-c6ed-11eb-9117-b89e1df06863.png)

1. What I did wrong?
2. There are also macro definitions, e.g. xQueueCreate() which are enabled by preprocessor flag. _xQueueCreate_ results in *xQueueGenericCreate*:

```
#if ( configSUPPORT_DYNAMIC_ALLOCATION == 1 )
    #define xQueueCreate( uxQueueLength, uxItemSize )    xQueueGenericCreate( ( uxQueueLength ), ( uxItemSize ), ( queueQUEUE_TYPE_BASE ) )
#endif
```

 I added *FreeRTOSConfig.h* config file as in the above code snippet. In that config file the flag _configSUPPORT_DYNAMIC_ALLOCATION_ is set to 1. I understand that Ceedling can't parse macros so I will not see _xQueueCreate_ functions in the output _mock_queue.h_ but I don't understand what I did wrong that I can't see _xQueueGenericCreate_ functions there?

3. I added INC_FREERTOS_H flag to _:test_preprocess:_ to avoid errors that _FreeRTOS.h_ is not included before _queue.h_ header file or other components. However I think this is the key to resolve problems in 1. and 2. What I did wrong that _FreeRTOS.h_ is not added while Ceedling is parsing _queue.h_ header? How can I force it to load _FreeRTOS.h_ and _FreeRTOSConfig.h_ first and then start parsing _queue.h_ header file?

**Comment by MuckleEwe** [comment]
Try adding `PRIVILEGED_FUNCTION=` to your defines.

**Comment by wdembinski** [comment]
It works if I add `PRIVILEGED_FUNCTION=` and `configSUPPORT_DYNAMIC_ALLOCATION=1` to _:defines:/:test_preprocess:_ list. Does it mean I should copy all settings from _FreeRTOSConfig.h_ to that list? IS it possible to force Ceedling to use _FreeRTOSConfig.h_ for preprocessing? I tried adding it to _:includes:_ and _:includes_h_pre_orig_header:_ but it seems not working.
