### ISSUE TITLE
Test cases are not run independently

### ISSUE THREAD

**Issue by wdembinski** [ThrowTheSwitch/Ceedling#602]
Let's assume I have an init function in module which is tested with Unity/Ceedling. I implemented multiple test cases and now would like to test some scenarios when module is not initialized / initialized. I noticed that once I call init function in some test case, all following test cases are executed with a module state same as left in the previously executed test case.
Is it intentional test cases are not independent from each other. I also tried Google Test for C++ testing. There each test case is treated independently, test class object is destroyed and created each time a new test case is executed. Is it possible to add such feature here, in Ceedling? Maybe it already exists? I checked docs but struggle to find it.

**Comment by Letme** [comment]
That's why you have setUp and TearDown - to clean after the tests and to prepare a clean environment for the tests. So use one to de-init each time, and use second to set some variables you want.
