### ISSUE TITLE
Compilation database generation support

### ISSUE THREAD

**Issue by carlogravador** [ThrowTheSwitch/Ceedling#611]
Does ceedling has a feature to automatically generate a compilation database?

**Comment by mvandervoord** [comment]
I'll need you to define what "compilation database" means in this context. :)

**Comment by carlogravador** [comment]
Sorry for not being clear, what I mean by compilation database is the one being read by the language server to provide functionalities like code completion, go to def, go to ref, etc... (in most cases, a compile_commands.json)

I'm just new to ceedling and base on what I know, it also acts as a build system for your project, so it knows how to compile your code, so I'm thinking if ceedling can generate it automatically.

Thanks :-)

**Comment by Letme** [comment]
Aka cscope for vim users or project file for Eclipse right?

**Comment by carlogravador** [comment]
I think I found the answer [here](https://github.com/ThrowTheSwitch/Ceedling/tree/master/plugins/compile_commands_json)

Ceedling has a plugin for generating compile_commands.json, to enable it

```yaml
:plugins:
  :enabled:
    - compile_commands_json
```

I'll be closing this ticket. Thanks :-)
