### ISSUE TITLE
Trouble testing function written in assembly

### ISSUE THREAD

**Issue by LanceBeasley** [ThrowTheSwitch/Ceedling#613]
I'm new to Ceedling but have a couple of unit tests working. My third one will test a function written in assembly. I keep getting the error:
`undefined symbols:
_main(startup.o) start_initialization(startup.o)`

Any ideas?

Here is the full output:
`ceedling verbosity[4] test:get_sys_values

Test 'test_get_sys_values.c'
----------------------------
Generating runner for test_get_sys_values.c...
Compiling test_get_sys_values_runner.c...
> Shell executed command:
'xc8-cc -mcpu=16LF1704 -c -o "build/test/out/c/test_get_sys_values_runner.p1" -fno-short-float -fno-short-double -Os -fasmfile -maddrqual=require -xassembler-with-cpp -I"test" -I"test/simulation" -I"test/support" -I"../lib" -I"../lib/detectors_dev" -I"../lib/include" -I"../source" -I"../source/include" -I"C:/Program Files/Microchip/xc8/v2.32/pic/include/proc" -I"C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/vendor/unity/src" -I"C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/vendor/cmock/src" -I"build/test/mocks" -mwarn=-9 -DXPRJ_default=default -ginhx32 -Wl -Wa,-a -D__DEBUG=1 -std=c99 build/test/runners/test_get_sys_values_runner.c'
> Produced output:
build/test/runners/test_get_sys_values_runner.c:49:35: warning: implicit conversion changes signedness: 'int' to 'UNITY_UINT' (aka 'unsigned long') [-Wsign-conversion]
    Unity.CurrentTestLineNumber = line_num;
                                ~ ^~~~~~~~
1 warning generated.

Compiling test_get_sys_values.c...
> Shell executed command:
'xc8-cc -mcpu=16LF1704 -c -o "build/test/out/c/test_get_sys_values.p1" -fno-short-float -fno-short-double -Os -fasmfile -maddrqual=require -xassembler-with-cpp -I"test" -I"test/simulation" -I"test/support" -I"../lib" -I"../lib/detectors_dev" -I"../lib/include" -I"../source" -I"../source/include" -I"C:/Program Files/Microchip/xc8/v2.32/pic/include/proc" -I"C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/vendor/unity/src" -I"C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/vendor/cmock/src" -I"build/test/mocks" -mwarn=-9 -DXPRJ_default=default -ginhx32 -Wl -Wa,-a -D__DEBUG=1 -std=c99 test/test_get_sys_values.c'

Compiling get_sys_values.s...
ERROR: Shell command failed.
> Shell executed command:
'xc8-cc -mcpu=16LF1704 -D__PIC16LF1704__ -DUNITY_INCLUDE_CONFIG_H -DTEST -D__XC8 -I"test" -I"test/simulation" -I"test/support" -I"../lib" -I"../lib/detectors_dev" -I"../lib/include" -I"../source" -I"../source/include" -I"C:/Program Files/Microchip/xc8/v2.32/pic/include/proc" -I"C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/vendor/unity/src" -I"C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/vendor/cmock/src" -I"build/test/mocks" -Wl -Wa,-a -fno-short-float -fno-short-double -Os -fasmfile -maddrqual=require -xassembler-with-cpp -mwarn=-9 -ginhx32 -std=c99 -o "build/test/out/c/get_sys_values.p1" -D__DEBUG=1 ../lib/get_sys_values.s'
> Produced output:
:0:: error: (500) undefined symbols:
        _main(build/test/out/c\startup.o) start_initialization(build/test/out/c\startup.o)
(908) exit status = 1
> And exited with status: [1].

#<Thread:0x000001e666cb3290 C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/par_map.rb:7 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        11: from C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/par_map.rb:10:in `block (2 levels) in par_map'
        10: from C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/task_invoker.rb:91:in `block in invoke_test_objects'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
         2: from C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/rules_tests.rake:26:in `block in <top (required)>'
         1: from C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/generator.rb:99:in `generate_object_file'
C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/tool_executor.rb:88:in `exec': ShellExecutionException (ShellExecutionException)
rake aborted!
ShellExecutionException: ShellExecutionException
C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/tool_executor.rb:88:in `exec'
C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/generator.rb:99:in `generate_object_file'
C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/rules_tests.rake:26:in `block in <top (required)>'
C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/task_invoker.rb:91:in `block in invoke_test_objects'
C:/Users/lance/WS/Teak/Classic/Ceedling/vendor/ceedling/lib/ceedling/par_map.rb:10:in `block (2 levels) in par_map'
Tasks: TOP => build/test/out/c/get_sys_values.p1
(See full trace by running task with --trace)
ERROR: Ceedling Failed`

**Comment by Letme** [comment]
I am not even going to look into the details, but are you running this on target?

otherwise as btw you are compiling that assembler file as C file. So either make it a c file with embedded assembly, but keep in mind that main in in testfile so something else is fishy with this file...

**Comment by LanceBeasley** [comment]
Is it possible Rake is having a problem generating the right build commands given one of the dependencies is a .s file?

Still being new, I'm still learning what is what. I can compile and run a simple C application that calls the assembly file, so I have to assume its OK. Attempting to run the test file from Ceedling is failing.

I'm not running this on target, but rather in the Microchip MDB hardware simulator. The code is 8-bit, compiled in XC8 for a PIC16LF1704.


This function is super simple. Calls to the function get_sys_val pass a single argument through the working register (WREG). The routine does a branch based on the value in WREG (BRanch W offset), and returns the hard-coded value from flash.
`#include <xc.inc>
#include "get_sys_value_constants.h"
 

#define GET_SYS_VALUE_ADDR_TABLE_START (0x14-0x01) //Bytes from table start to first table entry	
psect   get_sys_value,abs,local,class=CODE,delta=2 ; PIC10/12/16
ORG GET_SYS_VALUE_ADDR_TABLE_START;
	
global _get_sys_value ; extern of bar function goes in the C source file

//Ugh. There's just not enough to gain testing the value being passed. Currently this routine
//is getting the sensor's address, and that from a hard-coded constant. 
//I'm leaving the parameter test out, after spending a couple of hours learning how to put it in...
_get_sys_value:    
    BRW;					      0x13  Offset to the actual location of the lookup table
    RETLW default_ADDR1;	    //Must be at addr 0x14
    RETLW default_ADDR2;	    //Must be at addr 0x15	  
    //RETLW default_ADDR2;	    //Must be at addr 0x16
    retlw 0;`

**Comment by LanceBeasley** [comment]
Is Ceedling able to do unit tests that include assembly files?

**Comment by LanceBeasley** [comment]
This issue has more to do with how XC8 generates different object/intermediate files for c and assembly. For multi-step C compilation, XC8 generates a P-code file (with a .p1 extension) for each C file. Assembly files are compiled into object files (with a .o extension).

Ceedling doesn't anticipate 2 different object file formats.

As such, I'm closing this issue and created a [feature request](https://github.com/ThrowTheSwitch/Ceedling/issues/617) for Ceedling to support different extensions for C and assembly files.
