### ISSUE TITLE
Ruby 27 and Ceedling 0.31.1

### ISSUE THREAD

**Issue by LanceBeasley** [ThrowTheSwitch/Ceedling#615]
After realizing I'm running an old version of Ceedling, I ran "gem update" which took a while. After running, Ceedling was still at version 0.29, so I ran "gem uninstall ceedling", then "gem install ceedling" which brought the version up to 0.31.1.

`C:\Users\lance\WS\Teak\Classic>ceedling version
Welcome to Ceedling!
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fiddle-1.0.9/lib/fiddle.rb:67: warning: already initialized constant Fiddle::RTLD_GLOBAL
C:/Ruby27-x64/lib/ruby/2.7.0/fiddle.rb:53: warning: previous definition of RTLD_GLOBAL was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fiddle-1.0.9/lib/fiddle.rb:68: warning: already initialized constant Fiddle::RTLD_LAZY
C:/Ruby27-x64/lib/ruby/2.7.0/fiddle.rb:54: warning: previous definition of RTLD_LAZY was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fiddle-1.0.9/lib/fiddle.rb:69: warning: already initialized constant Fiddle::RTLD_NOW
C:/Ruby27-x64/lib/ruby/2.7.0/fiddle.rb:55: warning: previous definition of RTLD_NOW was here
    Ceedling:: 0.31.1
       CMock:: 2.5.4
       Unity:: 2.5.4
  CException:: 1.3.3

C:\Users\lance\WS\Teak\Classic>`

I created a new empty project, every ceedling command returns "unknown alias: common_defines":

`C:\Users\lance\WS\Teak\Classic\classic_project>ceedling clean
Traceback (most recent call last):
        38: from C:/Ruby27-x64/bin/ceedling:23:in `<main>'
        37: from C:/Ruby27-x64/bin/ceedling:23:in `load'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ceedling-0.31.1/bin/ceedling:278:in `<top (required)>'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych.rb:670:in `load_file'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych.rb:670:in `open'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych.rb:671:in `block in load_file'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych.rb:370:in `load'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych.rb:335:in `safe_load'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:338:in `register_empty'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:338:in `each'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:338:in `block in register_empty'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: common_defines (Psych::BadAlias)

C:\Users\lance\WS\Teak\Classic\classic_project>`

**Comment by LanceBeasley** [comment]
Probably user error.

**Comment by seabrow** [comment]
Hello.

Did you fix this issue because I am having the same problem.

It feels like the call to *common_defines is made before the &common_defines is declared

**Comment by peterwrigley** [comment]
Seems to be caused by an update to "psycho" gem recently. It is part of the Ruby install. gem uninstall pyscho will revert to a compatible version.
