### ISSUE TITLE
Test file includes are not extractes for test runners

### ISSUE THREAD

**Issue by jannisbaudisch** [ThrowTheSwitch/Ceedling#621]
When you use parameterized test and use macros or enum values inside the TEST_CASE macro of external headers, the linker will exit with an error. The reason for this is, that header files from the test file are not written into the test runner.

The reason for this is that we pass an empty array to generator_test_runner in generator.rb line 70
```ruby
    test_file_includes = [] # Empty list for now, since apparently unused

    # build runner file
    begin
      @generator_test_runner.generate(module_name, runner_filepath, test_cases, mock_list, test_file_includes)
```

**Comment by jannisbaudisch** [comment]
Fix with pull request https://github.com/ThrowTheSwitch/Ceedling/pull/622 github is not able to link these two at the moment

**Comment by HenrikJo** [comment]
Any workaround for now?

**Comment by mkarlesky** [comment]
This has been fixed with latest prerelease build of Ceedling 1.0.0.
