### ISSUE TITLE
Compiler flags not present when compiling assembly file

### ISSUE THREAD

**Issue by BojanG72** [ThrowTheSwitch/Ceedling#640]
I'm trying to setup my release build to work on an STM32L4 mcu. I have been able to get the cross compiler to start compiling my c code. But I have an assembly file for the startup file. When the compiler reaches the .s file, for some reason it does not use any of the compiler flags I set up in the YAML file.

//////////////////
      TOOLS
/////////////////

:tools:
  :release_compiler:
    :executable: arm-none-eabi-gcc             #exists in system search path
    :arguments:
      - ${1}
      - -DTARGET
      - -mcpu=cortex-m4
      - -mthumb
      - -Ilib/CMSIS/Device/ST/STM32L4xx/Include/
      - -Ilib/CMSIS/Include/
      - -Ilib/STM32L4xx_HAL_Driver/Inc/
      - -Isrc/bsp/
      - -Wall
      - -Os
      - -c
      - -o ${2}
  :release_linker:
    :executable: arm-none-eabi-gcc
    :arguments:
      - -mcpu=cortex-m4
      - -mthumb
      - -Ilib/CMSIS/Device/ST/STM32L4xx/Include/
      - -Ilib/CMSIS/Include/
      - -Ilib/STM32L4xx_HAL_Driver/Inc/
      - -Isrc/bsp/
      - ${1}
      - -o ${2}.elf

//////////////
      LOG
///////////////

Compiling stm32l4xx_hal_tim_ex.c...
Command: {:line=>"arm-none-eabi-gcc lib/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c -DTARGET -mcpu=cortex-m4 -mthumb -Ilib/CMSIS/Device/ST/STM32L4xx/Include/ -Ilib/CMSIS/Include/ -Ilib/STM32L4xx_HAL_Driver/Inc/ -Isrc/bsp/ -Wall -Os -c -o build/release/out/c/stm32l4xx_hal_tim_ex.o", :options=>{:stderr_redirect=>:none, :background_exec=>:none}}
Verbose: exec(): arm-none-eabi-gcc lib/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c -DTARGET -mcpu=cortex-m4 -mthumb -Ilib/CMSIS/Device/ST/STM32L4xx/Include/ -Ilib/CMSIS/Include/ -Ilib/STM32L4xx_HAL_Driver/Inc/ -Isrc/bsp/ 
-Wall -Os -c -o build/release/out/c/stm32l4xx_hal_tim_ex.o

'arm-none-eabi-gcc lib/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c -DTARGET -mcpu=cortex-m4 -mthumb -Ilib/CMSIS/Device/ST/STM32L4xx/Include/ -Ilib/CMSIS/Include/ -Ilib/STM32L4xx_HAL_Driver/Inc/ -Isrc/bsp/ -Wall -Os -c -o 
build/release/out/c/stm32l4xx_hal_tim_ex.o'

Compiling startup_stm32l496agix.s...
Command: {:line=>"as.exe -I\"src\" -I\"src/app\" -I\"src/bsp\" -I\"src/common\" -I\"lib\" -I\"lib/CMSIS\" -I\"lib/CMSIS/Device\" -I\"lib/CMSIS/Device/ST\" -I\"lib/CMSIS/Device/ST/STM32L4xx\" -I\"lib/CMSIS/Device/ST/STM32L4xx/Include\" -I\"lib/CMSIS/Device/ST/STM32L4xx/Source\" -I\"lib/CMSIS/Device/ST/STM32L4xx/Source/Templates\" -I\"lib/CMSIS/Include\" -I\"lib/STM32L4xx_HAL_Driver\" -I\"lib/STM32L4xx_HAL_Driver/Inc\" -I\"lib/STM32L4xx_HAL_Driver/Inc/Legacy\" -I\"lib/STM32L4xx_HAL_Driver/Src\" -I\"startup\" \"startup/startup_stm32l496agix.s\" -o \"build/release/out/asm/startup_stm32l496agix.o\"", :options=>{:stderr_redirect=>:none, :background_exec=>:none}}
Verbose: exec(): as.exe -I"src" -I"src/app" -I"src/bsp" -I"src/common" -I"lib" -I"lib/CMSIS" -I"lib/CMSIS/Device" -I"lib/CMSIS/Device/ST" -I"lib/CMSIS/Device/ST/STM32L4xx" -I"lib/CMSIS/Device/ST/STM32L4xx/Include" -I"lib/CMSIS/Device/ST/STM32L4xx/Source" -I"lib/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"lib/CMSIS/Include" -I"lib/STM32L4xx_HAL_Driver" -I"lib/STM32L4xx_HAL_Driver/Inc" -I"lib/STM32L4xx_HAL_Driver/Inc/Legacy" -I"lib/STM32L4xx_HAL_Driver/Src" -I"startup" "startup/startup_stm32l496agix.s" -o "build/release/out/asm/startup_stm32l496agix.o"
startup/startup_stm32l496agix.s: Assembler messages:
startup/startup_stm32l496agix.s:29: Error: unknown pseudo-op: `.syntax'
startup/startup_stm32l496agix.s:30: Error: unknown pseudo-op: `.cpu'
startup/startup_stm32l496agix.s:31: Error: unknown pseudo-op: `.fpu'
startup/startup_stm32l496agix.s:32: Error: unknown pseudo-op: `.thumb'
startup/startup_stm32l496agix.s:60: Warning: .type pseudo-op used outside of .def/.endef: ignored.
startup/startup_stm32l496agix.s:60: Error: junk at end of line, first unrecognized character is `R'
startup/startup_stm32l496agix.s:62: Error: no such instruction: `ldr sp,=_estack'
startup/startup_stm32l496agix.s:65: Error: no such instruction: `bl SystemInit'
startup/startup_stm32l496agix.s:68: Warning: `r1' is not valid here (expected `(%rsi)')
startup/startup_stm32l496agix.s:68: Error: expecting operand after ','; got nothing
startup/startup_stm32l496agix.s:69: Error: no such instruction: `b LoopCopyDataInit'
startup/startup_stm32l496agix.s:72: Error: no such instruction: `ldr r3,=_sidata'
startup/startup_stm32l496agix.s:73: Error: no such instruction: `ldr r3,[r3,r1]'
startup/startup_stm32l496agix.s:74: Error: too many memory references for `str'
startup/startup_stm32l496agix.s:75: Error: too many memory references for `add'
startup/startup_stm32l496agix.s:78: Error: no such instruction: `ldr r0,=_sdata'
startup/startup_stm32l496agix.s:79: Error: no such instruction: `ldr r3,=_edata'
startup/startup_stm32l496agix.s:80: Error: too many memory references for `add'
startup/startup_stm32l496agix.s:81: Error: too many memory references for `cmp'

From the log above you can see that when compiling the .c files it includes the compiler flags, specifically -mcpu=cortex-m4, and -mthumb. But when it starts compiling the assembly file those flags are not present and as a result the compilation fails because it needs those flags to understand the assembly code.

Any idea what I could be missing?

[ceedlingLog.txt](https://github.com/ThrowTheSwitch/Ceedling/files/7493380/ceedlingLog.txt)

**Comment by mvandervoord** [comment]
Hi. You want to specify a :release_assembler: tool for compiling your assembly files, again with the flags needed.

**Comment by BojanG72** [comment]
Thank you!!
