### ISSUE TITLE
Ceedling does not use custom named YML on Ubuntu

### ISSUE THREAD

**Issue by MichaelBMiner** [ThrowTheSwitch/Ceedling#648]
I am using Jenkins on Ubuntu 20.04 to automate my build process. Two projects have been given to me and they are heavily coupled. I will work on separating the two but first I need some tests set up. The two projects are PNE and BLDC for reference.

The two projects share some code filtered by ifdefs. In my ceedling tests I created two yml files.` bldc_project.yml` and `pne_project.yml`. Each YML file defines the necessary variables and point to the tests to be ran for each project.

To run my tests I do

```
set CEEDLING_MAIN_PROJECT_FILE=pne_project.yml
ceedling clobber test:all
```
This works on windows, I have tested this with ` bldc_project.yml` and `pne_project.yml` the correct tests are run. When I perform this on my Jenkins server I get errors that clobber and test:all commands cannot be found.

![setMainProjectFile](https://user-images.githubusercontent.com/7850720/146080036-59fb5258-f596-4a7d-af7f-77acb7b4bf1d.PNG)

**Comment by art-of-dom** [comment]
Was able to reproduce this and will poke around this in the next few days. A temporary suggestion though would be try having your jenkins server symlink them each to project.yml temporarily before each run.

**Comment by MichaelBMiner** [comment]
> Was able to reproduce this and will poke around this in the next few days. A temporary suggestion though would be try having your jenkins server symlink them each to project.yml temporarily before each run.

I am so happy you can re-create this and it is not just my setup! I will do some searching for symlink.

**Comment by MichaelBMiner** [comment]
Preliminary tests are promising, I will implement this into my pipeline and report back!

**Comment by art-of-dom** [comment]
So digging more into this, we were setting the environment variables incorrectly. You either need to set it on the command before the command or use the export command so both:

```
export CEEDLING_MAIN_PROJECT_FILE=foo.yml
ceedling 
```


and

```CEEDLING_MAIN_PROJECT_FILE=foo.yml ceedling```


should work. If you point me to the docs you were looking at I can update them so others can see it or you can update the docs too,

**Comment by MichaelBMiner** [comment]
I believe I tried export and still had it fail. As for the documentation I found it [here](https://github.com/ThrowTheSwitch/Ceedling/blob/master/docs/CeedlingPacket.md) but no examples are given. I had to search how to set the environment variables. 

As two solutions/workarounds have been found I will close this. Thank you for the help.
