### ISSUE TITLE
update Ceedling documentation with TEST_FILE

### ISSUE THREAD

**Issue by ajc-novo** [ThrowTheSwitch/Ceedling#696]
When Ceedling can not find the file to be tested when running a test, the issue can be resolved by added this option to the project.yml file. Unfortunately it is not documented. Only found it by reviewing the Ruby code.

**Comment by mkarlesky** [comment]
`TEST_FILE()` is still not officially documented, but it will be when version 0.32 is released. 0.32 is a significantly refactored version of Ceedling that addresses a number of bugs and shortcomings (you can see a fair amount of activity on the branch). In fact, multiple build directives will be available via macros in test files. `TEST_FILE()` has been renamed `TEST_SOURCE_FILE()` to provide naming options and clarity for these.
