### ISSUE TITLE
undefined method `exists?' for File:Class for ruby 3.2.0

### ISSUE THREAD

**Issue by BranLiang** [ThrowTheSwitch/Ceedling#724]
```
➜  ceedling help    
/Users/bran/.gem/ruby/3.2.0/gems/ceedling-0.31.1/bin/ceedling:12:in `<top (required)>': undefined method `exists?' for File:Class (NoMethodError)

  project_found = File.exists?(main_filepath)
                      ^^^^^^^^
Did you mean?  exist?
        from /Users/bran/.gem/ruby/3.2.0/bin/ceedling:25:in `load'
        from /Users/bran/.gem/ruby/3.2.0/bin/ceedling:25:in `<main>'
```

Error when using the ceedling with ruby version 3.2.0

**Comment by BranLiang** [comment]
Related https://bugs.ruby-lang.org/issues/17391

**Comment by ckielstra** [comment]
More likely related to #https://github.com/ThrowTheSwitch/Ceedling/pull/635

**Comment by mvandervoord** [comment]
Fixed.

**Comment by Daimonion1980** [comment]
@mvandervoord 
Stumbled upon this minutes ago as tried to install ceedling 

Installed Ceedling Version 0.31.1 via gem which is 1.5 years old, but the latest stable on a fresh installed ruby 3.2.0 (2022-12-25 revision a528908271) [x64-mingw-ucrt]

Which commit fixes this issue?

**Comment by cHemingway** [comment]
I am also having this problem, with the same version of Ruby (installed via Scoop) and Ceedling 0.31.1

**Comment by mvandervoord** [comment]
I'm still catching up on working around the breaking changes in Ruby 3.2. You can see the progress on this topic on the `test/ceedling_0_32_rc` branch. I'm very sorry for the headaches! If you want to patch this yourself, that particular bug is just replacing the deprecated `exists?` with `exist?`. It appears that's likely going to lead you to more issues, depending on the features you have enabled.
