### ISSUE TITLE
CMock IgnoreArg functions not being generated

### ISSUE THREAD

**Issue by JonTBeckett** [ThrowTheSwitch/Ceedling#726]
I am using ceedling for my unit testing at work and when the mocks are generated for functions, the IgnoreArg functions are not being generated with them. There are a lot of pointer parameters in the arguments that need ignored since they generally point to a stack location that isn't known. 

Is a special argument required or something for ceedling to generate them as well as the typical ExpectAndReturn, Ignore, and Return mock helpers?

**Comment by mvandervoord** [comment]
Maybe you don't have the IgnoreArg plugin enabled in your project.yml file?

```
:cmock:
  :plugins:
    - ignore_arg
```

**Comment by JonTBeckett** [comment]
I did not have that in the project.yml. I will try adding it tomorrow morning and see if that works (I assume it will). For future reference, is there a list of the CMock plugins somewhere that I'm overlooking?

Thanks for the quick reply!

**Comment by Letme** [comment]
https://github.com/ThrowTheSwitch/CMock/blob/master/docs/CMock_Summary.md#generated-mock-module-summary

**Comment by Letme** [comment]
Please close the issue :)
