### ISSUE TITLE
Bug test:pattern[*]

### ISSUE THREAD

**Issue by JuPrgn** [ThrowTheSwitch/Ceedling#748]
Hi,
Not sure if this has been already reported and/or fixed for next release but in v 0.31 calling :
`ceedling test:pattern[test_AB*]`
Will run all test matching to `test_A*`, it seems the regex does not take care of the last character.

**Comment by mvandervoord** [comment]
That's correct. A regular expression of `test_AB*` means that it must include `test_A` exactly, followed by `B` zero or more times. The string `test_A` matches those requirements. I suspect you want `test_AB.*` or more simply just `test_AB`, which both mean it must contain `test_AB` and it doesn't care if there is anything before or after it.

**Comment by mvandervoord** [comment]
Aren't regular expressions "fun"? 

I highly recommend rubular.com for trying expressions out if you want to learn more. You can enter your own expressions and examples and see what matches. :)

**Comment by JuPrgn** [comment]
@mvandervoord thank you for your answer and the link ! 
I am going to revise my regular expressions right now :)

**Comment by JuPrgn** [comment]
Got it, the expression I was looking for is  : 
`ceedling test:pattern[test_AB+]`
Which will run every test including `test_A` followed by one or more `B` : 
`Test_ABC`
`Test_AB`
And not : `Test_A`
