### ISSUE TITLE
Does the gcov plugin need a maintainer?

### ISSUE THREAD

**Issue by austinglaser** [ThrowTheSwitch/Ceedling#75]
I'm opening this here since there's not a lot of action on the ceedling-gcov repo -- hopefully this isn't beating a dead horse _too_ much.

In any case, the gcov plugin has been broken for a while, and in general has seen very little maintenance. I've been using it for a while (with a local patch for the current issue), and I have a vested interested in seeing it maintained -- code coverage is pretty important for my testing workflow.

I'd be willing to take on its maintenance, and to add a couple of features that I'd like to use (namely, the generation of output files so one can see _which_ lines aren't getting coverage in a file).

Full disclosure, I'm primarily a C developer, and have only recently started learning Ruby in earnest. With that said, I'm very keen to get involved in the Ceedling project, since I've found it about the best embedded-C unit-testing project out there.

**Comment by mvandervoord** [comment]
:) We'd love to get some help with the gcov plugin. If you have a patch already, that's awesome!

**Comment by austinglaser** [comment]
Great! My patch to simply get it working is open as a pull request to the gcov repo (from my work account). Or should I submit it to the Ceedling repository itself?

**Comment by pJunger** [comment]
The same thing should hold for the Bullseye plugin, which then should not work either (or does it)?

**Comment by mvandervoord** [comment]
Good thinking. Would one of you be willing to do that?

**Comment by austinglaser** [comment]
I could try, but I don't have a license for bullseye so I couldn't test my patch fully

**Comment by mvandervoord** [comment]
Ah. Good point. I know some people using Bullseye. I'll see if I can pull them in to help.
