### ISSUE TITLE
Ruby for Windows Does Not Include PTY

### ISSUE THREAD

**Issue by Bandoth** [ThrowTheSwitch/Ceedling#76]
Ceedling seems to support running tests via invoking Ceedling rather than calling rake directly.  However, Windows does not have an implementation for PTY included with Ruby (using V1.9.3 atm).  A Google search shows that rubysl-pty (v1.0.0 for Ruby V1.9.3) may be a workaround, but Ruby informs me this gem is dependent on the Ruby Dev Kit, yet another frustrating step.

Calling rake to run tests still works, but with the changeover in documentation, this could cause issues with new users on Windows systems.

**Comment by mvandervoord** [comment]
Fixed in d60fe4b

Thanks!
