### ISSUE TITLE
Multiple source extension

### ISSUE THREAD

**Issue by cobrunet** [ThrowTheSwitch/Ceedling#765]
Hi everyone,

I would like to use multiple source file extensions.
My project contain both of C and CPP files and there is dependencies between them.

Extension section example I would like to create:
```
:extension:
  :source:
    - .c
    - .cpp
  :executable: .out
```

Actually, the `source` section only support one string. Maybe there is a way to tell Ruby to match any case with a regex ?

Thank you in advance for your answers.

**Comment by mkarlesky** [comment]
Closing this issue but only to cull the open issue list a bit. I'm also rolling this issue up into a single issue that deals with multiple file extensions for a single file type.
