### ISSUE TITLE
Pointer Issue using Ceedling

### ISSUE THREAD

**Issue by mvrebolo** [ThrowTheSwitch/Ceedling#768]
Hello everyone,

I'm facing a problem using pointer in Ceedling, when I run: **ceedling test:all**, I'm getting this error:

```
Test 'test_code.c'
----------------------------
Running test_code.out...

ERROR: Test executable "test_code.out" failed.
> Produced no output to $stdout.
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test code.

rake aborted!

C:/Ruby27-x64/bin/ceedling:23:in `load'
C:/Ruby27-x64/bin/ceedling:23:in `<main>'
Tasks: TOP => unit_test/build/test/results/test_code.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.
```

My code:

```
#include "unity.h"

typedef struct
{
   int		test_value;
}test_struct;

test_struct   *test_struct_value;

void setUp(void)
{

}

void tearDown(void)
{

}

void test_1(){

    test_struct_value->test_value = 1;

    TEST_ASSERT_EQUAL(0, 0);
    TEST_ASSERT_EQUAL(0, 0);

}
```

Why am I facing this problem?

**Comment by mvandervoord** [comment]
Hi Marcus:

The problem you're running into is that you're writing a value to a dereferenced pointer, but you've never initialized that pointer.

You create a pointer here:

test_struct *test_struct_value;

It might be better if you instead create an instance of the struct, like this:

test_struct test_struct_value;

Or (if you prefer) you can create an instance in setup and free it in teardown:

void setUp(void) {
    test_struct_value = malloc(test_struct);
}

void tearDown(void) {
    if (test_struct_value) {
        free(test_struct_value);
        test_struct_value = 0;
    }
}

If you do the first option, you'd have to modify the usage of the struct to match:

void test_1(){

test_struct_value.test_value = 1;
// ...
}

 I hope this helps

Mark

**Comment by mvrebolo** [comment]
Ohhh I see,

Thanks very Much Mark, I'm a little bad with pointers in C.

I need to use the second way, because the code that I'm testing, uses pointer:

`test_struct *test_struct_value;`

So I tested your code and I realized that malloc needs to add the sizeof.

```
void setUp(void) {
    test_struct_value = malloc(sizeof(test_struct));
}

```
As I added the "sizeof", it is working. Thanks very much!

**Comment by mvrebolo** [comment]
Ohhh I see,

Thanks very Much Mark, I'm a little bad with pointers in C.

I need to use the second way, because the code that I'm testing, uses pointer:

`test_struct *test_struct_value;`

So I tested your code and I realized that malloc needs to add the sizeof.

```
void setUp(void) {
    test_struct_value = malloc(sizeof(test_struct));
}
```
As I added the "sizeof", it is working. Thanks very much!
