### ISSUE TITLE
Fresh windows install (ruby + ceedling) raise exception when trying `ceedling --version`

### ISSUE THREAD

**Issue by FZGabriel** [ThrowTheSwitch/Ceedling#770]
I'm not a ruby programmer, but it seems the plural version of `exist` has been deprecated in ruby 3.2.2

```txt
$ ceedling --version
ruby/gems/gems/ceedling-0.31.1/bin/ceedling:12:in `<top (required)>': undefined method `exists?' for File:Class (NoMethodError)

  project_found = File.exists?(main_filepath)
                      ^^^^^^^^
Did you mean?  exist?
```` 

Thanks for ceedling;
It's a great tool.

**Comment by mvandervoord** [comment]
This has already been fixed. The next release just hasn't been released yet. You can see the pre-release gems in the releases area.

**Comment by FZGabriel** [comment]
Great news.
My apologies for the noise in the issues.

**Comment by mvandervoord** [comment]
No need to apologize. I appreciate your thorough report! :)
