### ISSUE TITLE
Gcovr coverage report - rake aborted!

### ISSUE THREAD

**Issue by pwr230047** [ThrowTheSwitch/Ceedling#771]
I have a problem with command: `ceedling gcov:all`
I wrote this issue under link: https://github.com/msys2/MSYS2-packages/issues/3769#issuecomment-1550906558

1. Why does this problem occur?
2. Are the commands in the correct order?
3. What should I put in the _project.yml_ unit test configuration file?

**Comment by Letme** [comment]
The error in the other issue tells you gcov:all does not exist, so I do wonder how did you install ceedling and how do you invoke it. Figure out where loadpaths in the `project.yml` `plugin` section is pointing too, as I have a feeling it does not enable the plugins.

**Comment by pwr230047** [comment]
### Solution
https://github.com/msys2/MSYS2-packages/issues/3769#issuecomment-1550906558
