### ISSUE TITLE
Ceedling cannot handle tests with dash in test file name

### ISSUE THREAD

**Issue by swaldhoer** [ThrowTheSwitch/Ceedling#780]
Ceedling cannot handle test with dash in test name (that is derived from the file name):

This for example works fine

```yaml
:defines:
  :common: &common_defines
    - UNITY_UNIT_TEST
  :my_other_test_with_underscores:
    - BLA
  :test:
    - *common_defines
```

while this does not work as ceedling cannot parse the configuration file:
```yaml
:defines:
  :common: &common_defines
    - UNITY_UNIT_TEST
  :my-other-test-with-dashes:
    - BLA
  :test:
    - *common_defines
```

**Comment by mkarlesky** [comment]
Hi @swaldhoer. I'm working with @mvandervoord. This issue should be fixed with commit https://github.com/ThrowTheSwitch/Ceedling/commit/d3c0bffd8a2daef028c9803ccd6e7e107fc97f15
