### ISSUE TITLE
Memory Mismatch

### ISSUE THREAD

**Issue by Emre-ee** [ThrowTheSwitch/Ceedling#781]
Hello,

I got memory mismatch error. I researched too many documents but i didn't understand.  

**My tools versions:**
```
Welcome to Ceedling!
    Ceedling:: 0.31.1
       CMock:: 2.5.4
       Unity:: 2.5.4
  CException:: 1.3.3
```
I will share my test suites. 

**test_Func.c:**

```
void test_Func(void)
{
   HAL_GPIO_WritePin_Expect(GPIOC, RELAY_1_Pin, GPIO_PIN_SET);
   HAL_GPIO_ReadPin_ExpectAndReturn(GPIOC, RELAY_1_Pin, GPIO_PIN_SET);

   TEST_ASSERT_EQUAL(SUCCESS, SetRelay(STATUS_RELAY_ON, RELAY_1));


   // Scenario-2
   HAL_GPIO_WritePin_Expect(GPIOC, RELAY_1_Pin, GPIO_PIN_SET);
   HAL_GPIO_ReadPin_ExpectAndReturn(GPIOC, RELAY_1_Pin, GPIO_PIN_RESET);

   TEST_ASSERT_EQUAL(FAILURE, SetRelay(STATUS_RELAY_ON, RELAY_1));

   // Scenario-3
   HAL_GPIO_WritePin_Expect(GPIOC, RELAY_1_Pin, GPIO_PIN_RESET);
   HAL_GPIO_ReadPin_ExpectAndReturn(GPIOC, RELAY_1_Pin, GPIO_PIN_RESET);

   TEST_ASSERT_EQUAL(SUCCESS, SetRelay(STATUS_RELAY_OFF, RELAY_1));


   // Scenario-4
   HAL_GPIO_WritePin_Expect(GPIOC, RELAY_1_Pin, GPIO_PIN_RESET);
   HAL_GPIO_ReadPin_ExpectAndReturn(GPIOC, RELAY_1_Pin, GPIO_PIN_SET);
 
   TEST_ASSERT_EQUAL(SUCCESS, SetRelay(STATUS_RELAY_ON, RELAY_1));
}
```

When i run the test i get **Memory Mismatch. Byte 0 Expected 0x00 Was 0x01. Function HAL_GPIO_WritePin Argument PinState. Function called with unexpected argument value**  error. This error occurs in Scenario-4 part. 

When i looked PinState variable, it is enum variable .  Variable declaration below:
```
typedef enum
{
  GPIO_PIN_RESET = 0U,
  GPIO_PIN_SET
} GPIO_PinState;

```

That's all. Is there any problem in my test suite?

**Comment by Letme** [comment]
I think test suite is correct, if in scenario 4 the WritePin is expected to be called with enum `GPIO_PIN_RESET`, your code seems to call it with GPIO_PIN_SET (as scenario 2). So question is why do you think it is a problem?

**Comment by Emre-ee** [comment]
Thank you for your time.
Actually my question is why PinState value not changed? Because i expected value GPIO_PIN_RESET. For example, i expected  value GPIO_PIN_RESET in scenario-3 and i think, it is changed value of PinState. So what happened in scenario-4, i didn't understand.

**Comment by Letme** [comment]
I have a hunch what you are doing, but mocking, does not change the variable, it only changes the return value. I do not see a scenario 4 where STATUS_RELAY_ON would return SUCESS, since it returns FAIL in scenario 2 where status and write-pin are not equal (logically)

I am guessing your setRelay function should look something like below, to achieve what you want:

```
int SetRelay(int status, int relay_id)
{
    int ret=FAIL;
    if (relay_id == RELAY_1) {
        HAL_GPIO_WritePin(GPIOC, RELAY_1_Pin, GPIO_PIN_RESET);
        int read_val = HAL_GPIO_ReadPin(GPIOC, RELAY_1_Pin);
        if (read_val == status) { /* This is assuming GPIO_PIN_RESET matches 
             * STATUS_RELAY_OFF which is really bad assumption but shows that you should 
             * use local variable to check the status of the ReadPin - not ReadPin directly */
            ret = SUCCESS
        }
   }

   return ret;
}

**Comment by Emre-ee** [comment]
Ok, i got you. Thank you.
