### ISSUE TITLE
ceedling projects nested as submodules

### ISSUE THREAD

**Issue by fededc88** [ThrowTheSwitch/Ceedling#791]
### Discussed in https://github.com/ThrowTheSwitch/Ceedling/discussions/790

<div type='discussions-op-text'>

<sup>Originally posted by **fededc88** July 12, 2023</sup>
May be someone can help me. 

I have a situation where I have multiple repositories generated as Ceedling projects with multiple modules. One depends on the other one and should be included as submodule but I'll end up with two config .yml files. 
Besides that al the tests should be ran from the main project. 

Can any one describe me how to work with nested ceedling proyects? </div>

**Comment by mvandervoord** [comment]
The soon-to-be-released 1.0.0 version of Ceeding has a `dependencies` plugin which is the proper way to handle this sort of thing.

https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/plugins/dependencies/README.md

In the current 0.31.0 release, there isn't a straight-forward way of getting this functionality.

**Comment by fededc88** [comment]
Amazing news! Can't wait to try that new module! I'll stay tuned!

**Comment by mvandervoord** [comment]
If you'd like, you can try it by going to our [releases](https://github.com/ThrowTheSwitch/Ceedling/releases) and downloading the latest preview release. Once you've done that, you can install it at the command line like this:

```
gem install --local ceedling-1.0.0-whatever-filename
```

Please note that there ARE some [breaking changes](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/BreakingChanges.md) in this release that will require changes to your project.yml file!

**Comment by fededc88** [comment]
I'll give it a try if I have the chance! 

One more comment, I guess that right now you are reviewing open issues and closing them prior to the new release but for a long time I just thought that I wasn't understanding how Ceedling was supposed to handle dependencies. 
An early comment would have been really nice,
Again, more than happy with the new dependencies module and thanks for the time answering the issue!

**Comment by fededc88** [comment]
Gotcha! Thanks again for the good work! And no problem at all

**Comment by fededc88** [comment]
Hi Mark! I'm doing my first steps on v1.0.0 and it looks amazing! 

Quick question refloating this thread, I believe that the feature I'm looking is the subproject plugin , when will this be available?

**Comment by mvandervoord** [comment]
Hi! The `subprojects` plugin (and others) have been combined into the new `dependencies` plugin. It is part of the 1.0.0 release. You can enable the plugin and read the [readme](https://github.com/ThrowTheSwitch/Ceedling/blob/master/plugins/dependencies/README.md) here on how to use it. :)
