### ISSUE TITLE
`ceedling help` only shows 80 characters per line on Windows

### ISSUE THREAD

**Issue by matrdr** [ThrowTheSwitch/Ceedling#794]
When I try accessing the help using `ceedling help` with Ceedling version 0.31.1 it is always truncated at 80 characters with `...` when done on Windows. I tried the same thing with Ubuntu where it seemed to work as expected and showed the whole text.

I think this is quite annoying as the `help` command is not very helpful in this case.

Example:
```
PS C:\Users\matt> ceedling version
Welcome to Ceedling!
    Ceedling:: 0.31.1
       CMock:: 2.5.4
       Unity:: 2.5.4
  CException:: 1.3.3

PS C:\Users\matt> ceedling help
Welcome to Ceedling!
Commands:
  ceedling example PROJ_NAME [DEST]  # new specified example project (in DEST...
  ceedling examples                  # list available example projects
  ceedling help [COMMAND]            # Describe available commands or one spe...
  ceedling new PROJECT_NAME          # create a new ceedling project
  ceedling upgrade PROJECT_NAME      # upgrade ceedling for a project (not re...
  ceedling version                   # return the version of the tools installed
```

**Comment by mkarlesky** [comment]
@matrdr This is annoying, isn't it? The problem has to do with the minutiae of how Windows terminals handle width. I think we have a robust way to handle this now in Ceedling 1.0.0 (prerelease). We are using a Ruby library that queries terminal width and dynamically uses that to set Thor and Rake output width. That is, if you resize the width of your terminal, output will match it. If that functionality is unavailable (generally in certain Windows scenarios), the default is now a width of 120 characters as this seems a reasonable minimum on modern systems.

If this is not working properly for you, please reopen this issue.
