### ISSUE TITLE
sizeof(void) is not defined in ISO C

### ISSUE THREAD

**Issue by swaldhoer** [ThrowTheSwitch/Ceedling#795]
For a function like this

```c
MyFunction(
    void *bla,
) { /* */ }
```

CMock create a mock like this:

```c
#define MyFunction_ReturnThruPtr_bla(bla) \
    MyFunction_CMockReturnMemThruPtr_bla(__LINE__, bla, sizeof(void))
                                                     /* ^^^^^^^^^^^^^ */
```

which is not valid ISO C, as ``sizeof(void)`` is undefined behavior.

GCC returns 1u for ``sizeof(void)``, so maybe it be better to treat that special case like that.

Further, as I have no idea of the CMock, I wonder if the the mock should not use ``sizeof(void *)``? Then of course something like 4u for for 32bit machines would be correct

**Comment by mvandervoord** [comment]
Curious. usually void* gets translated to an unsigned char* internally by CMock. That must have been broken at some point. What version of CMock are you using? Can you past the actual function declaration that is being used? Does it possibly use an alias for void or have other descriptors?

**Comment by swaldhoer** [comment]
Actual function declaration:

```c
DATA_Read4DataBlocks(
    void *pDataToReceiver0,
    void *pDataToReceiver1,
    void *pDataToReceiver2,
    void *pDataToReceiver3);
```

CMock output :

```c
#define DATA_Read4DataBlocks_ReturnThruPtr_pDataToReceiver0(pDataToReceiver0) \
    DATA_Read4DataBlocks_CMockReturnMemThruPtr_pDataToReceiver0(__LINE__, pDataToReceiver0, sizeof(void))
```

- There is alias for void, however we are using the preprocessor option in the `project.yml`. Maybe it is related to that?
- CMock version: I think, the version that is pinned in the 0.31.1 release (https://github.com/ThrowTheSwitch/CMock/tree/3d4ba8d20b8958da5dace7dd5d31155c94b60819). But I need to verify that.

**Comment by mvandervoord** [comment]
Thanks for the details :)

I'll give it a whirl here too... Out of curiosity, does it just seem to be creating this error for the return thru pointer or for expectations as well? Maybe we missed some places that need this protection?

**Comment by swaldhoer** [comment]
Sure!

I need to check that tomorrow on the machine at work. I started to work on getting our test suite compiling with `-pedantic` and this was the first issue I ran into, so there maybe more to come😅 

If I get other findings, I'll share them here too.

**Comment by mvandervoord** [comment]
Thanks. That's what I'm seeing too. :)

**Comment by Hannes103** [comment]
The following issue seems to be related: https://github.com/ThrowTheSwitch/CMock/issues/319
