### ISSUE TITLE
TOOLS_GCOV_POST_REPORT_CUSTOM is used but never defined

### ISSUE THREAD

**Issue by informatimago** [ThrowTheSwitch/Ceedling#799]
See this commit in https://github.com/ThrowTheSwitch/Ceedling/pull/784 :
[Corrected unknown identifier error](https://github.com/ThrowTheSwitch/Ceedling/pull/784/commits/0f51e9f1518cb7bcdeb642c20dd9ba3a70c832e2) 
[0f51e9f](https://github.com/ThrowTheSwitch/Ceedling/pull/784/commits/0f51e9f1518cb7bcdeb642c20dd9ba3a70c832e2)
TOOLS_GCOV_POST_REPORT_CUSTOM does not appear anywhere else.
Is TOOLS_GCOV_GCOV_POST_REPORT the right substitute?

I've substituted it, but I don't know if that's correct; perhaps it's a new report that hasn't been committed yet?

**Comment by jamestiotio** [comment]
I don't think this issue exists on the latest commit of the master branch (see [here](https://github.com/ThrowTheSwitch/Ceedling/blob/master/plugins/gcov/lib/reportgenerator_reportinator.rb#L115)).

It seems that you modified it in another commit of your PR [here](https://github.com/ThrowTheSwitch/Ceedling/pull/784/commits/7e5752a9e256e48e8dce958dd1a1f41346054397#diff-2711cb5fb38befcf7b4bae75cf4eba44dbed1d7ca2ac78d554180f27270828c5) before you reverted it.

**Comment by informatimago** [comment]
ok. I wasn't sure about it.  Thank you.
