### ISSUE TITLE
Status of  :gcov_post_report_custom: ?

### ISSUE THREAD

**Issue by informatimago** [ThrowTheSwitch/Ceedling#812]
I have a project that uses the  :gcov_post_report_custom: tool/step to consolidate gcov reports.
It doesn't seem to be called in the version I use:
0f51e9f (HEAD -> 783--cmock-of-the-wrong-file-is-generated
based on:
1d783eb (origin/master, origin/HEAD, github/master, master) <Mark VanderVoord> Merge pull request #756 from NTDV/master
(I will rebase as soon as possible).

I have 
```
:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - xml_tests_report
    - module_generator
    - raw_output_report
    - gcov
```

The log only show a call to gcovr -version and that's it.
```
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/tasks_base.rake...
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/tasks_filesystem.rake...
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/tasks_tests.rake...
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/tasks_vendor.rake...
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/rules_tests.rake...
NOTICE: 
The option[s]:  
cannot be applied.To enable it, please add `:cmdline_args` under :test_runner option in your project.yml.
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/rules_cmock.rake...
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/rules_preprocess.rake...
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/rules_tests_deep_dependencies.rake...
Loading rakefile component: /build/pbourguignon/clang4/work/build.devel/utest-nkernel/vendor/ceedling/lib/ceedling/tasks_tests_deep_dependencies.rake...
Loading rakefile component: vendor/ceedling/plugins/module_generator/module_generator.rake...
Loading rakefile component: vendor/ceedling/plugins/gcov/gcov.rake...
Verbose: exec(): gcovr --version 2>&1
> Shell executed command:
'gcovr --version 2>&1'
> Produced output:
gcovr 4.1

Copyright 2013-2018 the gcovr authors
Copyright 2013 Sandia Corporation
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.

ls: cannot access 'build/gcov/out/utest*.info': No such file or directory
```
(The ls is the first command after calling ceedling).

Is this normal? Can I make a change to project.yml to have it run the custom report command?

**Comment by mkarlesky** [comment]
Hi @informatimago. So sorry for this trouble.

A couple items for you:

- The GCovr tool made some relatively sizable changes in the transition from 4.1 to 4.2. And, GCovr is now on version 7. While the plugin you're using does support 4.1 and earlier, it might be a good idea to update GCovr.
- Ceedling 0.32 is nearing release. It's a huge update. The `gcov` plugin has also received many updates and bug fixes. Its documentation has also been greatly improved.

**Comment by informatimago** [comment]
> Hi @informatimago. So sorry for this trouble.
> 
> A couple items for you:
> 
> * The GCovr tool made some relatively sizable changes in the transition from 4.1 to 4.2. And, GCovr is now on version 7. While the plugin you're using does support 4.1 and earlier, it might be a good idea to update GCovr.
> * Ceedling 0.32 is nearing release. It's a huge update. The `gcov` plugin has also received many updates and bug fixes. Its documentation has also been greatly improved.

Thanks for the info.  In the meantime, we've just used a custom script.
