### ISSUE TITLE
Adding library glib

### ISSUE THREAD

**Issue by DamianoBaroneSky** [ThrowTheSwitch/Ceedling#813]
Hi,
Probably is really simple problem, but I tried multiple things and it always failed.
I have this error:
 fatal error: glib.h: No such file or directory
 #include <glib.h>

when I see in console 
ERROR: Shell command failed.
> Shell executed command:
'gcc -I .....
all the library I can't see the glib.
I tried to change the yml file with multiple parameter such as:

:tools:
  :test_compiler:
    :executable: gcc
    :arguments:
      - -Wall
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I: "/usr/include/glib-2.0"
      - -I: "/usr/lib/x86_64-linux-gnu/glib-2.0/include"
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -c ${1}
      - -o ${2}
  :test_linker:
    :executable: gcc
    :arguments:
      - ${1}
      - -lpthread
      - -o ${2}

or 

:cmock:
  :includes:
    - /usr/include/glib-2.0
    - /usr/lib/x86_64-linux-gnu/glib-2.0/include
    
    
    
but in the gcc console I don't see the library and I get the same error.
I have just copied the gcc command generate from ceedling and add  -I "/usr/include/glib-2.0" and it seems working.
So is there a simple way to add in that project that library or at least when ceedling generate the command  have that line?
I always run 

ceedling clobber
ceedling test:all

thank you in advance

**Comment by Letme** [comment]
In your last statement you said you added `-I "/usr/include/glib-2.0"` and it works - did you add it to the end of command or on the spot where you have it now? Anyway looking through it again I think this is the problem:

Care to explain why you have (with colon `:`):
```
- -I: "/usr/lib/x86_64-linux-gnu/glib-2.0/include"
```

and not just a normal command syntax like:
```
- -I "/usr/lib/x86_64-linux-gnu/glib-2.0/include"
```
(although I dont think you need quotes).

**Comment by Letme** [comment]
You keep adding colon... why? I just told you to remove the colon between `-I` and value of the input argument. Like you say on command line you dont add it, so why are you adding int into the yaml file?

**Comment by mvandervoord** [comment]
Agreed. As @Letme suggests:

```
:tools:
  :test_compiler:
    :executable: gcc
    :arguments:
      - -Wall
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I "/usr/include/glib-2.0"
      - -I "/usr/lib/x86_64-linux-gnu/glib-2.0/include"
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -c ${1}
      - -o ${2}
  :test_linker:
    :executable: gcc
    :arguments:
      - ${1}
      - -lpthread
      - -o ${2}
```

**Comment by DamianoBaroneSky** [comment]
ah sorry I misunderstood .
it worked thank you

**Comment by DamianoBaroneSky** [comment]
thanks for the help,
The include worked but it seems is missing the link to the library.
    :arguments:
      - -Wall
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I/usr/include/glib-2.0
      - -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -DBUILD_FOR_PI
      - -DSAFEC_DUMMY_API
      - -c ${1}
      - -o ${2}
:test_linker:
  :executable: gcc
  :arguments:
    - ${1}
    - -lpthread
    - -lglib-2.0
    - -o ${2}
    
    
   but I have a lot of error about undefined reference. 
 undefined reference to `g_source_destroy'
 I thought this line will fix it  - -lglib-2.0, but it didn't
 I have run also 
  pkg-config --libs glib-2.0
-lglib-2.0
 so no problem in my machine. It's missing the link of the library.

**Comment by Letme** [comment]
You are adding to the right location at least for linking tests. If you only run the command does it work?

**Comment by DamianoBaroneSky** [comment]
which command do you mean?
if I run this  pkg-config --libs glib-2.0, it return this:
-lglib-2.0

so the library is installed and it can see the headers of glib but not the implementation (library)

**Comment by Letme** [comment]
Ceedling and gcc linking command? `-l`(as lambda) is the key here, but you also need system path in the linking command

**Comment by DamianoBaroneSky** [comment]
Hi,
The gcc command generate by ceedling doesn't have the reference of glib.
'gcc "build/test/out/c/test_btrMgr_runner.o" "build/test/out/c/test_myfile.o"  "build/test/out/c/mock_...ALL FILES.......o"  "build/test/out/c/unity.o" "build/test/out/c/myfile.o" "build/test/out/c/cmock.o" -o "build/test/out/test_myfile.out"'


I have run the gcc command manually and adding glib and there isn't error
gcc "build/test/out/c/test_btrMgr_runner.o" "build/test/out/c/test_myfile.o"  "build/test/out/c/mock_...ALL FILES.......o"  "build/test/out/c/unity.o" "build/test/out/c/myfile.o" "build/test/out/c/cmock.o" -o "build/test/out/test_myfile.out **`pkg-config --cflags --libs glib-2.0`**"

and the error has disappeared about glib. So I think it worked. Do you know how I can change the yml file to make ceedling generate that line?

**Comment by Letme** [comment]
yml you pasted would not procide the command you pasted above. Based on what you pasted you most likely have below yml, and you should then append the pconfig command (not sure why you add libs in that way):

```
:test_linker:
:executable: gcc
:arguments:
- ${1}
- -o ${2}
# Add pconfig for glib
- pkg-config --cflags --libs glib-2.0
```

If you ask me, I would put it like this:

```
:test_linker:
:executable: gcc
:arguments:
- ${1}
- -o ${2}
# Add path of the glib-2.0 if it is not in system path
- -L/usr/lib/blabababa
- -l glib-2.0
```

**Comment by DamianoBaroneSky** [comment]
I have tried both, but it's not working and the gcc command doesn't show any reference of glib.
Shall I mock the glib? i don't think is necessary.

![image](https://github.com/ThrowTheSwitch/Ceedling/assets/144350372/f5676c27-9012-4d80-9838-298ca243d8cf)

**Comment by Letme** [comment]
Test_linker is misaligned in your yml. Please align it under tools, at same level as test_compiler

**Comment by DamianoBaroneSky** [comment]
Ah yes it worked, thank you very much! I need to change my glasses 🤓 
I added just 
  :test_linker:
    :executable: gcc
    :arguments:
      - ${1}
      - -lpthread
      - -l glib-2.0
      - -o ${2}
      
  and it worked fine.
(pkg-config didn't work.)

**Comment by DamianoBaroneSky** [comment]
I will reopen the issue, because there is a problem with glib when I run ceedling gcov:all

**Comment by mvandervoord** [comment]
You need to add the same tool updates for gcov_compiler and gcov_linker.

**Comment by Letme** [comment]
Can you read documentation, because this has nothing to do with ceedling.

**Comment by DamianoBaroneSky** [comment]
ah ok, thank you, I will look it.
I thought was linked.

**Comment by Letme** [comment]
I have no idea why that would be linked. You changed the default tooling by adding glib, so now everything needs to be adjusted accordingly. https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/Instrumentation-Options.html (pick your gcc version)

Here are defaults for gcov plugin: https://github.com/ThrowTheSwitch/Ceedling/blob/master/plugins/gcov/config/defaults_gcov.rb

**Comment by DamianoBaroneSky** [comment]
thank you very much for posting the default file, it helped me.
now everything works. In case someone has similar issue to integrate a library, this is how I fixed the gcov issue.
it was missing     
  - -fprofile-arcs
  - -ftest-coverage
  and in the linked - -lgcov 
![image](https://github.com/ThrowTheSwitch/Ceedling/assets/144350372/a35a8c94-7fcb-497a-9264-6be78a44c203)
