### ISSUE TITLE
boilerplate_files option not working

### ISSUE THREAD

**Issue by CraigComberbach** [ThrowTheSwitch/Ceedling#814]
I am new to using Ceedling, so it might be something I am doing wrong, but the module_generator boilerplate_files option is not using the templates I have supplied it. Instead it is generating the default files. Neither an absolute or a relative reference to the files is working.

The details of my project.yml file are default, with only the inclusion of:
:module_generator:
  :boilerplate_files:
    :src: '<C:\Users\Craig\Desktop\CeedlingTest\Templates>\Template.c'
    :inc: '<..\Templates>\Template.h'

Command I am using:
ceedling module:create[DemoFile]

My project structure:
  Templates
  -Template.c
  -Template.h
  TestProject
  -src
  -test

Version of resources used:
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x64-mingw32]
Ceedling:: 0.31.1
Unity:: 2.5.4
CMock:: 2.5.4
CException:: 1.3.3

For what it is worth, I am also running on Windows 11, I don't think it is the cause of the issue, but I have seen things not always work as expected, so I can't rule it out.

**Comment by JuPrgn** [comment]
I am still on Ceedling 0.31.0 but if this can help, this is the detail of my project.yml : 
```
:module_generator:
  :boilerplate_files:
    :src: 'template\src_boilerplate.txt'
    :inc: 'template\inc_boilerplate.txt'
    :tst: 'template\tst_boilerplate.txt'
```

Project structure : 
```
project.yml
template
-src_boilerplate.txt
-inc_boilerplate.txt
-tst_boilerplate.txt
src
test
```
