### ISSUE TITLE
Unknown alias: common_defines (Psych::BadAlias)

### ISSUE THREAD

**Issue by PasVegan** [ThrowTheSwitch/Ceedling#819]
Hi,
I get error when running this command on my terminal: ceedling options:ci_sp test:all
I am on archlinux,
ruby version : ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
Ceedling:: 0.31.1
CMock:: 2.5.4
Unity:: 2.5.4
CException:: 1.3.3

[Here is the full error](https://pastebin.com/tmvtV0jp)

[Here is my project.yml file](https://pastebin.com/qg7ychn1)
[Here is my ci_sp.yml file (options)](https://pastebin.com/z4A037t7)
[Here is my ci_xp.yml file (options)](https://pastebin.com/j41ARmmb)

Thanks !

**Comment by deltalejo** [comment]
The issue is probably due to a breaking change with Ruby 3.1 / Psych 4.x as stated [here](https://bugs.ruby-lang.org/issues/17866). Try with Ruby 3.0, it comes with Psych 3.x so it should work.

**Comment by tchernobog** [comment]
@deltalejo the problem is that for instance in Debian stable (bookworm) openssl 1.0 was removed because end of life. Therefore, all ruby versions before 3.1 are impossible to build or install, even via rbenv.

As such, Ruby 3.1 is the minimum required version to have anything installed and working.

I don't think using Ruby 3.0 is going to be a viable solution for longer.

**Comment by deltalejo** [comment]
@tchernobog
I agree that using Ruby 3.0 is not a long term solution, we just need to wait for the next release of Ceedling that hopefully will fix this. But in the mean time, I manage to install Ruby 3.0.6 with rbenv on Debian Testing.

**Comment by mkarlesky** [comment]
@tchernobog @deltalejo @PasVegan And, thankfully, we just cleared the final big hurdle before the forever-in-coming 1.0.0 release. It was a mysterious and hard to reproduce threading bug that showed up primarily in Windows. All that's left is a couple tweaks and one more round of testing.
