### ISSUE TITLE
Run code generators as pre-build step

### ISSUE THREAD

**Issue by swaldhoer** [ThrowTheSwitch/Ceedling#822]
It would be nice if ceedling would support to run code generators as part of a pre-build step.

Questions I came up with: If the idea is considered a good one,
- is this a feature that should be implemented natively or is this something that a plugin should do (if that's possible)?
- how should it be called?
  `ceedling code-gen:<my-code-gen-task> test:all`
  or would it be better to keep
  `ceedling test:all` and ceedling just knows what to do?

**Comment by mvandervoord** [comment]
There is an immediate way to make this work, which is to use the command-hooks plugin and implement a `pre_test` hook to insert actions at the very beginning of the test sequence for a given test. 

Using a plugin is by far the best way to do this if you want to support a specific code generator. It can automatically add a hook like the one above, which will just become part of your process... but also you can add your own tasks for if you want to trigger code generation in other ways.

If you don't have a specific tool in mind, I don't see an advantage of creating another way of doing this, when the command-hooks plugin was already made for doing this sort of thing. If it's missing features that would interest you, it'd be better to expand the existing plugin.

**Comment by swaldhoer** [comment]
I didn't know about this plugin. Absolutely solves my problem! Thanks.
