### ISSUE TITLE
Could I run only one test_ function within one test file?

### ISSUE THREAD

**Issue by kafkaaaa** [ThrowTheSwitch/Ceedling#831]
Good Morning!

Could I run only one `test_` function within one test file?

or should I create another test file in the `src` directory?

Happy Coding ~ 😊

**Comment by LuisAfonso95** [comment]
I think the features might not be present in the 0.31 release. When I try it, including the added define mentioned in #747, it still runs all the tests in a file

**Comment by mkarlesky** [comment]
We are nearing an official release of 0.32. I can confirm that running individual test cases works as expected when `:test_runner` ↳ `:cmdline_args`  is set to `true`.
