### ISSUE TITLE
Tests pass with empty test functions

### ISSUE THREAD

**Issue by kozmotronik** [ThrowTheSwitch/Ceedling#835]
I don't know whether this is the intended behaviour of Ceedling. I ran tests on two empty test functions and the tests passed. Is this the intended behaviour or is it a bug?

### test_kayit.c
```c
#include "unity.h"

#include "mock_memory.h"
#include "mock_eepromio.h"
#include "mock_araclar.h"
#include "kayit.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_initStoreShouldLoadDefaultValuesOnFirstBoot(void) {
    
}

void test_initStoreShouldLoadStoredValuesFromEEPROMOnNormalBoot(void) {
    
}
```
I've translated the function names for convenience.

### The test report
```bash
$ ceedling test:kayit

Test 'test_kayit.c'
-------------------
Generating include list for memory.h...
Generating include list for eepromio.h...
Generating include list for araclar.h...
Creating mock for memory...
Creating mock for eepromio...
Creating mock for araclar...
Generating runner for test_kayit.c...
Compiling test_kayit_runner.c...
Compiling test_kayit.c...
Compiling mock_memory.c...
Compiling mock_eepromio.c...
Compiling mock_araclar.c...
Compiling unity.c...
Compiling kayit.c...
Compiling cmock.c...
Linking test_kayit.out...
Running test_kayit.out...

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  2
PASSED:  2
FAILED:  0
IGNORED: 0
```

### Tool set versions
```bash
$ ceedling version
   Ceedling:: 0.31.1
      Unity:: 2.5.4
      CMock:: 2.5.4
 CException:: 1.3.3

```

**Comment by mkarlesky** [comment]
Thanks for the report, @kozmotronik. Yes, at this time this is the intended behavior. Test case logic is such that a test passes if there is no failing assertion within it. This logic happens to also encompass a test case with no assertions.

With some effort we could probably detect blank test cases and/or test cases with no assertions and output an info message, but I tend to think this is low on the priority list and might necessitate a further option to enable that output message. (I can believe that some use empty test cases for some purpose or another.)

What would you suggest? Is this behavior breaking your brain?

**Comment by mkarlesky** [comment]
@kozmotronik We have a big ol' new release (0.32) about to come out. It includes a humongous revamp of documentation. I know just the place to add this!
