### ISSUE TITLE
ceedling command throws LoadError on Windows

### ISSUE THREAD

**Issue by adamjcasey** [ThrowTheSwitch/Ceedling#84]
This was addressed in #76 but still doesn't work.  On Windows we get the following:

```
$ ceedling
c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file
 -- pty (LoadError)
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/ceedling-0.20.3/bin/ceedling:151:in `<top (required)>'
        from c:/Ruby22/bin/ceedling:22:in `load'
        from c:/Ruby22/bin/ceedling:22:in `<main>'
```

This is because the `rescue` is looking for a `StandardError`.  When I change lines 167 and 183 to this:

```
  rescue LoadError
```

Then the `rescue` statements work, but even with `popen4 (0.1.2)` installed, the following error still occurs:

```
$ ceedling
c:/Ruby22/lib/ruby/gems/2.2.0/gems/ceedling-0.20.3/bin/ceedling:184:in `rescue in rescue in <top (required)>':
 Could Not Find PTY or POPEN4 gem. Install one or both like 'gem install pty' (RuntimeError)
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/ceedling-0.20.3/bin/ceedling:169:in `rescue in <top (required)
>'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/ceedling-0.20.3/bin/ceedling:150:in `<top (required)>'
        from c:/Ruby22/bin/ceedling:22:in `load'
        from c:/Ruby22/bin/ceedling:22:in `<main>'
```

**Comment by pkazakoff** [comment]
Also seeing this issue on Win 7 with Ruby 2.2.0. Bit of a pain as the eclipse integration doesn't work (while ceedling can fake being Google Test, rake can't).

**Comment by mvandervoord** [comment]
Before the `require 'popen4'` line, if you add `require 'rubygems'`, does the second problem go away?

Thanks for finding the first bug, btw. I'll submit both fixes together when we work this one out. :)

**Comment by pkazakoff** [comment]
Same issue:

![image](https://cloud.githubusercontent.com/assets/3944965/16213754/b6878ea4-3706-11e6-84b2-0c672a9bc206.png)

**Comment by pkazakoff** [comment]
Upon further inspection, it appears this is a result of POpen4 requiring win32-open3, which is not available for Ruby >1.9.

**Comment by mvandervoord** [comment]
Curious. It seems fine on my Win7 box running Ruby 2.2.  I'll keep digging. Thanks for the extra info!

**Comment by mvandervoord** [comment]
Ah, I see. I installed my version of Ruby originally using the SDK version, so when I installed POpen4, it downloaded the source version and built it for me. That appears to not be an option otherwise. Well, clearly I'll have to build in a backup to the backup. ;)

**Comment by tkindy** [comment]
I'm seeing the same issue with Ruby 2.3.1 on Windows 10. Is there an ETA for a fix for this? Thanks!

**Comment by DarkEnergy9** [comment]
I have this same error.  Is there a fix for this?
Windows 7 Pro. 
Ruby 2.2.5p319
ceedling 0.21.0
rake 11.3
thor 0.19.1

**Comment by plinnie** [comment]
I have the same issue on Windows 10.

ceedling (0.21.0)
did_you_mean (1.0.0)
io-console (default: 0.4.5)
json (default: 1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (default: 2.0.17)
rake (10.4.2)
rdoc (default: 4.2.1)
test-unit (3.1.5)
thor (0.19.1)

**Comment by mvandervoord** [comment]
@DarkEnergy9 and @plinnie , it appears neither of you actually installed the popen4 gem? You might want to try this. If that doesn't work, another option might be to try the popen4-mingw gem. If the latter works better for you, I'd love to know that. I'll update bundler to install that instead.

**Comment by plinnie** [comment]
installing Popen4 does not resolve it. I can't install Popen4-Mingw:
C:\Temp\ceelingtest\temp_sensor>gem install POpen4-mingw
ERROR:  Could not find a valid gem 'POpen4-mingw' (>= 0) in any repository

I do see it on rubygems.org. Maybe it is because I have a 64 bit version of Ruby, and this gem is 32 bit?

**Comment by plinnie** [comment]
Hmm.. tried it with Ruby 32 bits: 
```
Fetching: win32-open3-0.3.2-x86-mingw32.gem (100%)
ERROR:  Error installing POpen4-mingw:
      win32-open3 requires Ruby version < 1.9.0.
```
So, it seems I will need to revert to an old version of Ruby. :-( And even then success is not guaranteed. Is there any way we can resolve this? I'm not against getting my hands dirty, but I am not very familiar with Ruby yet (though I am doing the tutorial). How hard would it be to fix this issue?

**Comment by mvandervoord** [comment]
Hey @plinnie, maybe you can try some experiments for me?

You can find your Ruby gem somewhere like this (the details will vary based on the versions installed):

```
C:\Ruby22-x64\lib\ruby\gems\2.2.0\gems\ceedling-0.18.0
```

In there you will find a `bin` folder. In the `bin` folder you will find a file called only `ceedling` with no extension. Open that with your favorite text editor.

Somewhere near line 150, is this what you see? In particular, I want to verify that there are 4 sets of begin...rescue...end blocks in your codebase. (It's good to make sure we're at the same starting point).

```
  begin
    require 'pty'

    #if available, we use PTY because it will live-stream our data instead of buffering it all up
    def spawn_command(cmd, &block)
      begin
        PTY.spawn(cmd) do |stdout, stdin, pid|
          begin
            block.call(stdout)
          rescue Errno::EIO
          end
        end
      rescue Exception => e
        STDERR.puts e.inspect unless (e == PTY::ChildExited)
      end
    end

  rescue

    begin

      require 'popen4'

      #if pty wasn't available, we'll use POPEN instead
      def spawn_command(cmd, &block)
        POpen4.popen4(cmd) do |stdout, stderr, stdin|
          begin
            block.call(stdout)
          rescue Errno::EIO
          end
        end
      end

    rescue

      #if neither of these libraries were available, we can just shell out to the command and collect results
      def spawn_command(cmd, &block)
        block.call( `#{cmd}` )
      end
    end
```

Thanks!

**Comment by plinnie** [comment]
I've checked. It is identical. Not a single character is different

**Comment by plinnie** [comment]
Well, that was not so simple to fix. I can not install cursus on Windows. DevKit does not contain it, and there is no pacman in the msys2 environment.

**Comment by mvandervoord** [comment]
I'll have to check into what to do about Curses :(

I believe everything else in this thread should be fixed at this point.

**Comment by mvandervoord** [comment]
@plinnie, are you able to install from source instead of the gem? If so, can you grab the master and see if it works for you? If not, can you grab the latest gem and then apply the last commit's changes (it's only a few lines). I'd like to know if this makes Ceedling happy without curses.

**Comment by plinnie** [comment]
Okay, I grabbed the latest master. I tried to build it. I had to remove the " curses" dependency from the ceedling.gemspec in order for it to install. Now however, I get:
```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ceedling-0.22.0/bin/ceedling:283:in `block in <top (required)>': undefined method `each' for #<String:0x2967cc0> (N
oMethodError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/ceedling-0.22.0/bin/ceedling:187:in `spawn_command'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/ceedling-0.22.0/bin/ceedling:282:in `<top (required)>'
        from C:/Ruby23/bin/ceedling:22:in `load'
        from C:/Ruby23/bin/ceedling:22:in `<main>'
```
When executing ceedling test:all on the temp_sensor example.

I don't know if I actually made a valid gem. Since the description in the readme did not produce one. I actually executed 'gem build ceedling.gemspec' , and then installed that gem. So maybe I did something wrong.

**Comment by plinnie** [comment]
In addition, if I run 'bundle exec rake'  (wrongly named 'execute'  in the readme), I get this result:
```
rspec ./spec/system/deployment_spec.rb:25 # Ceedling deployed in a project's `vendor` directory.
rspec ./spec/system/deployment_spec.rb:26 # Ceedling deployed in a project's `vendor` directory.
rspec ./spec/system/deployment_spec.rb:27 # Ceedling deployed in a project's `vendor` directory.
rspec ./spec/system/deployment_spec.rb:28 # Ceedling deployed in a project's `vendor` directory.
rspec ./spec/system/deployment_spec.rb:29 # Ceedling deployed in a project's `vendor` directory.
rspec ./spec/system/deployment_spec.rb:39 # Ceedling deployed in a project's `vendor` directory without docs.
rspec ./spec/system/deployment_spec.rb:40 # Ceedling deployed in a project's `vendor` directory without docs.
rspec ./spec/system/deployment_spec.rb:41 # Ceedling deployed in a project's `vendor` directory without docs.
rspec ./spec/system/deployment_spec.rb:42 # Ceedling deployed in a project's `vendor` directory without docs.
rspec ./spec/system/deployment_spec.rb:43 # Ceedling deployed in a project's `vendor` directory without docs.
rspec ./spec/system/deployment_spec.rb:53 # Ceedling deployed as a gem
rspec ./spec/system/deployment_spec.rb:54 # Ceedling deployed as a gem
rspec ./spec/system/deployment_spec.rb:55 # Ceedling deployed as a gem
rspec ./spec/system/deployment_spec.rb:56 # Ceedling deployed as a gem
rspec ./spec/system/deployment_spec.rb:66 # Ceedling command: `ceedling examples` should list out all the examples
rspec ./spec/system/deployment_spec.rb:81 # Ceedling command: `ceedling example [example]` temp_sensor should be testable
```

**Comment by mchernosky** [comment]
I had the same `undefined method 'each' for #<String:0x2967cc0>` error above when running on Windows (without PTY or Popen).  I submitted PR #106 to fix it.

**Comment by mvandervoord** [comment]
Thanks Matt. Does this work for everyone who reported a problem now?

**Comment by plinnie** [comment]
It works!!!

However, I still had to comment the following line:
```
  # s.add_dependency "curses", ">= 1.0.0"
```
from the ceedling.gemspec 

Otherwise it would not install the gem created with `gem build ceelding.gemspec`
