### ISSUE TITLE
Ceedling cannot work if the header file and the source file do not share the same name?

### ISSUE THREAD

**Issue by roxysosa** [ThrowTheSwitch/Ceedling#847]
Hello, I'm experiencing an issue with Ceedling. It seems unable to link the header file properly. In this scenario, I have two files named A.c and B.c, and both are using the same header file named M.h. When I execute the test_A.c file, I encounter an error indicating that the functions in A.c are undefined. Upon further investigation, I realize that the issue arises because the header file and the source file do not share the same name (A.c -> M.h). Therefore, I need to find a solution that allows me to work with this naming configuration. What steps can I take to resolve this?
Thanks in advance. :)

**Comment by mvandervoord** [comment]
Hi. From your test, you can still include the header file (if you otherwise still want it included). In addition, you can use the following macro to specify that you also want to include an additional source file in your test:

```
TEST_FILE("A.c");
```

Also, a quick note: In the soon-to-be-released Ceedling, this feature is getting an updated name to the following:

```
TEST_SOURCE_FILE("A.c");
```

**Comment by roxysosa** [comment]
What about the header file? I don't want to include an additional source file in my test. The issue is that the header file used for this test has a different name than the source file I am testing, which causes the function I want to test to be undefined.
In this case, the header file is named bus.h, and the source file is buss.c, which includes #include "bus.h". My test file is named test_buss.c, also including #include "bus.h". The path is correct in the project.yml file.

<img width="350" alt="Capture" src="https://github.com/ThrowTheSwitch/Ceedling/assets/79508826/1f9042ff-77d5-4c18-9dd9-9ffb39b06579">

**Comment by mvandervoord** [comment]
Sorry. For clarity, is your situation that the following files exist:

 - bus.h
 - bus.c
 - buss.c

Or that only these two exist:

 - bus.h
 - buss.c

If it's the latter, it's easy. Your test would include the header and then specify the source file:

```
// test_buss.c
#include "bus.h"
TEST_FILE("buss.c")

// the rest of the file
```

If you're the first situation above, you're saying you want `test_buss.c` to use `bus.h` but NOT `bus.c`, correct?

This is going to sound silly, but you can do this:

```
// test_buss.c
#include "mock_bus.h"
TEST_FILE("buss.c")

// the rest of the file
```

The file `mock_bus.h` will include `bus.h` to give you the header you need access to, but it won't include the real `bus.c`. Instead, it'll include the mock... That doesn't mean you have to use the mock... you can make 0 calls to it. :)
