### ISSUE TITLE
Ceedling version should include the short SHA in the version identifier

### ISSUE THREAD

**Issue by swaldhoer** [ThrowTheSwitch/Ceedling#849]
It would be good if `Ceedling` would provide the short SHA in the version identifier, at least for `Ceedling` and in the best case also for the vendored dependencies, i.e., currently `ceedling version` reports

```text
Welcome to Ceedling!
    Ceedling:: 0.32.0
       CMock:: 2.5.4
       Unity:: 2.5.4
  CException:: 1.3.3
```

and it would be nice `Ceedling` would instead report

``` text
Welcome to Ceedling!
    Ceedling:: 0.32.0-3ba12fa   <----- Short commit SHA
       CMock:: 2.5.4-blabla  <----- Short commit SHA (optional, but nice)
       Unity:: 2.5.4-blabla  <----- Short commit SHA (optional, but nice)
  CException:: 1.3.3-blabla  <----- Short commit SHA (optional, but nice)
```

otherwise you have to manually keep track of the used `Ceedling` version when using a pre-release gem as it always just reports `0.32.0`.

**Comment by swaldhoer** [comment]
Note: If this feature request is accepted, I am willing to create a PR.

**Comment by mkarlesky** [comment]
Done! The latest Ceedling prerelease includes this much needed feature in the version output. It'll be a while until CMock, Unity, and CException get the same treatment.
