### ISSUE TITLE
Parameterized tests with Ceedling

### ISSUE THREAD

**Issue by matt21121** [ThrowTheSwitch/Ceedling#85]
Hi,

I have started using Ceedling for a few weeks and I found in the Unity documentation that it was possible to use parametrized tests which I think is an awesome feature. However, I have had a hard time making it work!

According my analysis of the ruby scripts the generator.rb will call the generate_test_runner method which calls two methods from Ceedling generator_test_runner.rb: find_test_cases and then generate. The generate method will create a UnityTestRunnerGenerator instance and then call the generate method of the UnityTestRunnerGenerator module. The problem is that this generate method takes as argument the output of the generator_test_runner.rb find_test_cases method which is pretty different from the UnityTestRunnerGenerator find_tests method which is thus never called and is the one dealing with the TEST_CASE macro parsing. Therefore parametrized tests are impossible to run with Ceedling as far as I understand, which is a shame as it is a cool feature.

What I don't understand is why the Ceedling generator_test_runner.rb find_test_cases method and the UnityTestRunnerGenerator find_tests method are so different.
I did a small modification that made it work and perhaps you might be interested in it:
In Ceedling generator_test_runner.rb:
  def find_test_cases(test_file)
    require 'generate_test_runner.rb'
    @test_runner_generator ||= UnityTestRunnerGenerator.new( @configurator.get_runner_config )
    return @test_runner_generator.find_tests(@file_wrapper.read(test_file))
  end

I am quite new to Ruby, so I hope this can be an input for enabling this feature on Ceedling :) (or it is already possible to make it work in an easier way and I have missed something :( ).

Best regards,
Matthieu Tardivon

**Comment by mvandervoord** [comment]
Matthieu:

Thanks so much for the help!  I'll merge this change in and see where it
gets us.

Second, I apologize for the lack of support in Ceedling. Ceedling tends to
lag the rest of the projects a bit, and so when features are added to other
projects (like the parameterized tests in Unity), it doesn't always make
its way into Ceedling. We're trying to be better about this... or rather
we're trying to make most of it automatic.

Anyway, thanks for the help!

Mark

**Comment by matt21121** [comment]
Great!
Thank you for your quick answer. I am looking forward to next release :)
Matthieu
