### ISSUE TITLE
gcovr` does not exist in system search path

### ISSUE THREAD

**Issue by TechLeadYoda** [ThrowTheSwitch/Ceedling#854]
Hi , 
I m a newbie  in ceedling . have this issue when executing ceedling gcov:all
CeedlingException ==> default_gcov_gcovr_report ↳ :executable => `gcovr` does not exist in system search paths.
Im working on windows 11 terminal. Gcovr and Gcov installed , ceedling last update, GCC installed and tested.  and followed all the steps of installation. 
Thanks

**Comment by mkarlesky** [comment]
Hi, @TechLeadYoda. Sorry for this trouble. I can tell from the error message that you're using pre-release 0.32. This means two things:

1. The `gcov` plugin has gotten lots of updates and attention for the upcoming 0.32 release. You're working with the latest greatest the project has to offer.
1. The documentation for `gcov` is quite thorough now and includes a [troubleshooting section](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/plugins/gcov/README.md#advanced-configuration--troubleshooting) that addresses this specific issue. That said, that troubleshooting section has not been vetted. Would you be willing to try it out and report back? I'd love to know if the advice works and if the quality of the writing works for you.

**Comment by CraigComberbach** [comment]
@mkarlesky, I was having the same problem. I tried the
```
:environment:
  - :gcovr: python -m gcovr # Call the gcovr module
```
solution and it worked for me. Thanks!

**Comment by TechLeadYoda** [comment]
Sorry for the late response. Thank you both.

**Comment by mkarlesky** [comment]
Great news, @CraigComberbach. Thank you @TechLeadYoda as well. I’ll close this issue. Please reopen if there’s more.
