### ISSUE TITLE
wildcard include paths order is inconsistent between environments

### ISSUE THREAD

**Issue by automat01** [ThrowTheSwitch/Ceedling#860]
test suites that were perfectly fine are no longer working after migration. Using the `compile_commands_json` plugin to debug this, I found that the include paths found by `project.yml` are in reversed order. all folders that are added by wildcards, either `/*` or `/**`

The funny thing is that this is all running in the same Docker image. the change is the environment where dockerd is running. I didn't expect this to have an impact on ceedling....

bash-for-windows -> call ceedling -> paths are included in alphabetical order  
windows docker -> ceedling image (based on Alpine) -> call ceedling -> works fine, path are alphabetically added to list.
AlpineWSL -> docker -> same ceedling image -> call ceedling -> bunch of tests don't compile, paths are in alphabetical order but reversed.

all 3 (well, all 2 , windows and docker image) have the same 0.31.1 ceedling version with the same gems. the image used in Docker was crafted to have the same tool versions as we use in our windows environments. I know there could be differences between windows builds and linux builds, but that is still a strange behaviour considering the same lunix image works fine with the dockerDesktop WSL environment. 

the order in which the paths are added to the `-I` list should be defined, and consistent across all systems.

**Comment by mkarlesky** [comment]
Wow. That's kinda nuts, @automat01. Thank you for the report. The only thing I can think of is that Ruby's directory listing methods are working differently on different platforms (not unheard of). We are concentrating on getting 0.32 released (massive update and bug fixes). I will add a task to our backlog to force a sort for the relevant directory listings. Unfortunately, we don't presently have the resources to actively maintain multiple releases of the project. So, 0.31.1 may not get much attention on this.
