### ISSUE TITLE
git , jenkins and unit test using ceedling 

### ISSUE THREAD

**Issue by MNasser-iono** [ThrowTheSwitch/Ceedling#866]
i want to automate the unit test case that use ceedling by jenkuns

**Comment by mvandervoord** [comment]
No problem! Ceedling can definitely be called by Jenkins as a command line tool and it has a variety of output reports to output in a format that Jenkins likes. What part of the process are you looking for help on?

**Comment by MNasser-iono** [comment]
the project i work at is a private repo , when i try to pull the code from the git , using jenkins , it can't because of the credentials, i tried all the method in in the internet , and it didn't work ,  and someone told me that jenkins won't see git and i should use bonobo local git instead
