### ISSUE TITLE
How to add list of source files to every test

### ISSUE THREAD

**Issue by thomasfinchbr** [ThrowTheSwitch/Ceedling#870]
Hi, 

I would like to know if the is a way to add a list of source files to be compiled and included in every test without actually adding than as "TEST_FILE(...)".

This would be useful for tests that use FreeRTOS for instance, and would allow me to not add all files at the beginning of every test.

Thanks.

**Comment by deltalejo** [comment]
What about adding them and/or their paths to the support files/paths on your **project.yml**?
e.g.:

```yaml
:files:
  :support:
    - file1.c
    - somewhere/file2.c
    - somewhere/else/file3.c
```

**Comment by thomasfinchbr** [comment]
Thanks for the response. I was not aware of this option ":files:".
Everything working here now.

**Comment by thomasfinchbr** [comment]
Closing as it is clear now.
