### ISSUE TITLE
unit test an output message written in the console with printf

### ISSUE THREAD

**Issue by TechLeadYoda** [ThrowTheSwitch/Ceedling#871]
![test](https://github.com/ThrowTheSwitch/Ceedling/assets/116717872/26536f72-827f-4889-9b24-75680c62062b)

**Comment by TechLeadYoda** [comment]
Hello, i have trouble testing with ceedling this simple code. I ve tried to redirect the stdout to a file and after  that I put the file contain in the string array . It's working but it is cluttered as a result  by the test summary output. So I don't have the result of the test printed in the terminal. Could you please help me to find an easier solution if possible. Thanks for your advices.

**Comment by kafkaaaa** [comment]
@TechLeadYoda

Try this

```
    // Arrange: make backup and redirect stdout to FILE
    const char* fname = "test_output.txt";
    int origin_stdout = dup(STDOUT_FILENO);
    fflush(stdout);
    freopen(fname, "w", stdout);

    // Act
    your_function( --- );
    FILE* fp = fopen(fname, "r");
    if (fp) {
        char buf[256];
        while (fgets(buf, sizeof(buf), fp)) {
            printf("%s", buf);
        }
        fclose(fp);
    }
    else printf("[Error] Fail to open %s\n", fname);

    // Assert
    TEST_ASSERT_EQUAL_STRING( --- );

    // restore stdout
    fflush(stdout);
    dup2(origin_stdout, STDOUT_FILENO);
    close(origin_stdout);
```

**Comment by mkarlesky** [comment]
@TechLeadYoda Generally speaking, directly testing stream handling with unit testing frameworks is discouraged. As you've already noticed it gets noisy and particularly in the case of files it becomes quite hard to manage the test set up and teardown.

The tried and true approach is:

- Write your code to test just up to the stream handling but not the stream handling itself. This can mean placing stream handling behind a wrapper you mock or simply separating your buffer handling from a simple handoff to stream handling. In the case of a `printf()` you might write code to prepare the string buffers that will be handed off to be printed and only unit test the string buffer handling.
- Use manual validation to verify the end result of the stream handling or begin relying on a system test framework (e.g. the Robot or Cucumber frameworks) to test your compiled and linked application with its output streams.

**Comment by mkarlesky** [comment]
TODO: @mkarlesky Add this discussion to Ceedling cookbook of testing needs and solutions.
