### ISSUE TITLE
Environment variables at flags and define fields

### ISSUE THREAD

**Issue by claudiiolima** [ThrowTheSwitch/Ceedling#879]
When use environment, `#{ENV[SOMETHING]}`, on flags or defines fileds, the variables aren't interpreted.

**Comment by claudiiolima** [comment]
Fo example on defines field I would like to use something like:

```yml
:defines:
  :release:
    :compile:
      - BOARD_REVISION=#{ENV['REVISION']}
```

> NOTE: I tried to use double quotes too. 
> - "BOARD_REVISION=#{ENV['REVISION']}"
> - BOARD_REVISION="#{ENV['REVISION']}"
> - \\"BOARD_REVISION=#{ENV['REVISION']}\\"
> - BOARD_REVISION=\\"#{ENV['REVISION']}\\"

**Comment by deltalejo** [comment]
I came across the same limitation quite a while. There is also [an old issue](https://github.com/ThrowTheSwitch/Ceedling/issues/630) about the same problem. A possible workaround would be to add the `-D` option to the compiler's arguments inside `:tools` section. e.g:

```yaml
:tools:
  :test_compiler:
    :name: awesome_compiler
    :executable: awesomecc
    :arguments:
      # some arguments
      - -DBOARD_REVISION=#{ENV['REVISION']}
      # more arguments
```

**Comment by claudiiolima** [comment]
Thank @deltalejo for your comments.

I'm using exactly this workaround, but it's becoming somewhat unproductive.

I will try to solve this issue and make a pull request

**Comment by claudiiolima** [comment]
@deltalejo maybe you can try the pull request above if you still need this feature.

This is my first contribution, so I hope everything goes well.

**Comment by mkarlesky** [comment]
Thank you for highlighting this and tying together PRs and existing issues. This is a good feature. I will be adding it to the latest pre-release version of Ceedling soon.

I am going to reject the PR but for a simple reason. Like path standardization and related tasks, this should all be collocated in the startup steps that process configuration before its used. The string replacement in tool handling is some of the very oldest code in Ceedling. It's not a pattern that should be copied elsewhere. We'll centralize this during configuration processing. This will have the added benefit of producing configuration modifications you can see and verify by running the new `dumpconfig` command line.
