### ISSUE TITLE
How do I enable test specific #defines?

### ISSUE THREAD

**Issue by joseph-eglu** [ThrowTheSwitch/Ceedling#886]

**Comment by jnz86** [comment]
Put them in your test file? 

Put them in the yaml file under `:defines:` ?

**Comment by mkarlesky** [comment]
@joseph-eglu @jnz86 Yes, under the `:defines:` section of your project configuration. Support for version 0.31 will be coming to an end very soon as the next major release, version 1.0.0 (still called 0.32 in various places) nears completion. I would suggest transitioning to the new Ceedling by working with the pre-release versions. The documentation for setting defines in the new version of the tool is [here](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md#defines-command-line-symbols-used-in-compilation).
