### ISSUE TITLE
Stop printing rake abort messages on compilation/linking failure

### ISSUE THREAD

**Issue by matrdr** [ThrowTheSwitch/Ceedling#890]
When compilation/and or linking fails, you always end up with a huge rake stack trace that takes way more space than the compiler/linker error message itself.

In my opinion, there is no benefit in having this stack trace for an average user.

I would opt for this stack trace not being there in the default verbosity option.

**Comment by mkarlesky** [comment]
Hi, @matrdr. Very sorry for this. Are you using version 0.31? The next major version nearing completion is a nearly complete rewrite of logging and exception handling. It's all quite tidy and configurable now.

**Comment by matrdr** [comment]
Yes, I am using 0.31.1.

That would be great if the next release fixes that.

If that is the case, feel free to close the issue again.

Keep up the great work! I am looking forward for the new release!
