### ISSUE TITLE
GcovCoverageResults are generated empty when build_root is outside of the project folder

### ISSUE THREAD

**Issue by slavko-m** [ThrowTheSwitch/Ceedling#893]
Hi,

When I change `build_root` to a folder above the folder where `project.yml` is, `GcovCoverageResults` are generated, but empty. 
```
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: "../build"
```
I get no errors on console, and generating coverage report works fine:
```
---------------------------
GCOV: CODE COVERAGE SUMMARY
---------------------------
some_lib.c Lines executed:80.00% of 15
some_lib.c Branches executed:75.00% of 8
some_lib.c Taken at least once:62.50% of 8
some_lib.c Calls executed:100.00% of 1
some_lib.c Lines executed:80.00% of 15

```
but `html` files are empty. If `build_root` is "build" or "some_folder/build" it works correctly. Any ideas what's wrong?

```
    Ceedling:: 0.31.1
       CMock:: 2.5.4
       Unity:: 2.5.4
  CException:: 1.3.3
```

**Comment by slavko-m** [comment]
I added 

`args += "--object-directory \"#{File.expand_path(GCOV_BUILD_PATH)}\" "`

alongside other options in the `args_builder_common` function from `gcovr_reportinator.rb`, and now it works correctly. I'm not sure if there is another solution that doesn't involve changing the source code.

**Comment by mkarlesky** [comment]
Hi, @slavko-m. So very sorry for the slow response. Your issue got missed.

We are finishing some final touches and testing on the big 1.0.0 release. Support for 0.31 is winding down. I just tested the build directory configuration you explained with a pre-release of 1.0.0. Everything worked fine including GCov coverage reporting. No errors reported and all artifacts and coverage results as you would exect.

In the interest of culling the list of issues and nudging all users towards 1.0.0, I am going to close this issue. If you need support with 1.0.0 and the GCov plugin, by all means, please open a new issue.
