### ISSUE TITLE
Ceedling 0.32.0 doesn't support verbosity task

### ISSUE THREAD

**Issue by Daedaliss9** [ThrowTheSwitch/Ceedling#899]
I am attempting to use Ceedling in a very basic fashion to learn how it is implemented to then use it during C development work.  I am running into difficulities with debugging and have found an issue with the verbosity task.  

I am attempting to link to a simple file in my project, run a test that will instantiate a circular buffer to test with.  When I link to the buffer files, instantiate a buffer, and compile with Ceedling, I get the following error:

![image](https://github.com/ThrowTheSwitch/Ceedling/assets/55674538/d4d3bce5-4192-4682-affc-9549dd4e86d1)

I attempt to turn on verbosity to troubleshoot, and get the next error:

![image](https://github.com/ThrowTheSwitch/Ceedling/assets/55674538/d1cc5731-0561-4210-8025-f0f8ab580311)

Finally, check with Rake about tasks, and see this:

![image](https://github.com/ThrowTheSwitch/Ceedling/assets/55674538/3e0ccdf0-f657-451c-9dfc-d8a144ef925d)

Ceedling version information:

![image](https://github.com/ThrowTheSwitch/Ceedling/assets/55674538/1d35cd79-0968-4023-ab30-ddf3349b22ff)

I am using Ruby 0.33.0 currently.

Any clues on how to get verbosity to work? Also, any help with troubleshooting the linking issue with the original test would be nice too. I would post in the Forums section, but doesn't seem anyone is watching that location and the board is filled with bot postings so it didn't seem like a place I would get an answer. If this is the wrong place to pose these questions, all eyes on where I should post. Thank you!

**Comment by deltalejo** [comment]
Use the `--debug` option. e.g.: `ceedling --debug test:all`

**Comment by Daedaliss9** [comment]
> Use the `--debug` option. e.g.: `ceedling --debug test:all`. Your are using the development version of Ceedling, so make sure to be using the latest pre-release from [releases](https://github.com/ThrowTheSwitch/Ceedling/releases) page and take a look ate the [new docs](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md).

Thank you!
