### ISSUE TITLE
Mixins merging order

### ISSUE THREAD

**Issue by deltalejo** [ThrowTheSwitch/Ceedling#902]
Why are mixins merged in the following order?

1. Command line
2. Environment variables
3. Project configuration file

That gives mixins from project configuration file higher priority, so they effectively overwrite any configuration derived from the others mixins. I would expect the priority being the opposite:

1. Project configuration file
2. Environment variables
3. Command line

My thought is that by this way, one may set a base project file with some base mixins, and any configuration from them can be overwritten from a command line mixin. Does it make sence?

Let me know your thoughts.

**Comment by mkarlesky** [comment]
Thank you, @deltalejo. You're right. It's backwards! As you can imagine, getting ordering correct was a bit of a challenge. I think when we started with Mixins we had a slightly different idea of what merging meant and ordered around it. At any rate, we'll get this corrected in the next prerelease build.
