### ISSUE TITLE
Command Hooks with console output

### ISSUE THREAD

**Issue by claudiiolima** [ThrowTheSwitch/Ceedling#907]
If I have a script that prints/echoes some text result, running in some command hook task, it will be printed to the console.

I thought this worked in previous versions, but I'm testing it in the latest version and it no longer works.

For example, a `pre_release` task from `Command Hooks` I only received:

```shell
Running the pre_release command hook...
```

but I expected something like this:

```shell
Running the pre_release command hook...
--------------------------------------------------
   The code was generated successfully
--------------------------------------------------
```

It is possible to print the result of a specific task, from command_hooks, to the console, without using `--verbosity=obnoxious`.

**Comment by claudiiolima** [comment]
Could be something like

```ruby
  def run_hook_step(hook, name="")
      # ...

      if (hook[:printable])
        result       = shell_result[:output].strip
        msg = @ceedling[:reportinator].generate_progress( result )
        @ceedling[:loginator].log( msg )
      end

      # ...
  end
```

**Comment by mkarlesky** [comment]
Great point, @claudiiolima. The latest pre-release has this ability with the addition of an optional `:logging` setting for each hook configuration. See the Command Hooks plugin README for more details (the change implements the spirit of your suggestion but is slightly more sophisticated).
