### ISSUE TITLE
report_tests_log_factory error: EXCEPTION: undefined local variable or method `keys'

### ISSUE THREAD

**Issue by tyler-macinnis** [ThrowTheSwitch/Ceedling#910]
I'm getting the following error related to `report_tests_log_factory` for the prerelease

```
🚧 Loaded project configuration at default location using ./project.yml
🪲 ERROR: Exception raised while trying to load plugin: report_tests_log_factory

🧨 EXCEPTION: undefined local variable or method `keys' for #<JsonTestsReporter:0x0000556af1166d98 @handle=:json, @filename="json.report", @config=nil, @config_walkinator=#<ConfigWalkinator:0x0000556af087dad8>>
```

Disabling the `report_tests_log_factory` plugin works as a temporary fix. It also affects junit and html.

I think the issue is here: https://github.com/ThrowTheSwitch/Ceedling/commit/4d75a3e80c7eda467b29b996942c74f0971cdf4b#diff-433207d3ec0d0e1561d8e3af1fca049b4aca2d942ea1a30735baa7c514d443c9

**Comment by mkarlesky** [comment]
Thank you, @tyler-macinnis. Yes. That's an easy fix. Will get that bug squashed in a new prerelease soon.

**Comment by mkarlesky** [comment]
@tyler-macinnis, this should be fixed in the latest prerelease.
