### ISSUE TITLE
Module Generator creating files at wrong path

### ISSUE THREAD

**Issue by claudiiolima** [ThrowTheSwitch/Ceedling#912]
At latest release, when using `module_generator`, it does not work as supposed.

My project has the following structure:

```
📂 ./
 ┣ BSP
 ┃ ┃ 📂**
 ┃ ┗ 📜**
 ┣ Sources
 ┃ ┃ 📂ApplicationLayer
 ┃ ┃ 📂**
 ┃ ┗ 📜**
 ┗ Tests
     ┃ 📂**
     ┗ 📜**
```

```ruby
:module_generator:
  :project_root: ./
  :source_root: Sources/
  :test_root: Tests/
  :test_define: CTEST
  :naming: :snake #options: :bumpy, :camel, :caps, or :snake
```

and when I try to run:

```bash
ruby .\vendor\Ceedling\bin\ceedling module:create[ApplicationLayer/Network/CAN/buffer_can]
```

I get:

```bash
...

Ceedling set up completed in 45.81 seconds
File BSP/**/ApplicationLayer/Network/CAN/buffer_can.c created
File BSP/**/ApplicationLayer/Network/CAN/buffer_can.h created
File Tests/ApplicationLayer/ApplicationLayer/Network/CAN/test_buffer_can.c created
Generate Complete
```

Am I doing something wrong?

**Comment by deltalejo** [comment]
Try creating the path `Sources/ApplicationLayer/Network/CAN` beforehand and adding it to the corresponding sections under `:paths` configuration.
In previous Ceedling it honored the path you give for the module, but now that behavior has been changed and I've been also having a hard time figuring out how it is working now.

**Comment by claudiiolima** [comment]
I've already tried! It didn't work too.

It appears that the routine uses the first path listed for source, and test paths.

The path where source files are created, is the first result from `paths:source`
The same occurs with test files..

**Comment by claudiiolima** [comment]
I figure out, what I was doing wrong!

I was trying to use the old semantic to describe path where files shall be created.

Now it must use `:`, to split the path field to _module_, like:

```bash
module:create[ApplicationLayer/Network/CAN:buffer_can]
```
