### ISSUE TITLE
Changing comment length causes test to go from passing to blowing up

### ISSUE THREAD

**Issue by krispin-gradient** [ThrowTheSwitch/Ceedling#916]
I have a test that passes, of the form:

```c
/**
 * Verifies that Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu tincidunt risus. Nam quis felis quam. 
 * Etiam blandit volutpat est, ut venenatis odio vehicula a. Nam luctus eleifend massa sed rhoncus. 
 */
void test_myFunction_yyy(void) {
   ...
}
```

When I do nothing else but lengthen its preceding comment (for example, by repeating the original comment content 3X), e.g:
```c
/**
 * Verifies that Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu tincidunt risus. Nam quis felis quam. 
 * Etiam blandit volutpat est, ut venenatis odio vehicula a. Nam luctus eleifend massa sed rhoncus. 
 * Verifies that Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu tincidunt risus. Nam quis felis quam. 
 * Etiam blandit volutpat est, ut venenatis odio vehicula a. Nam luctus eleifend massa sed rhoncus. 
 * Verifies that Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu tincidunt risus. Nam quis felis quam. 
 * Etiam blandit volutpat est, ut venenatis odio vehicula a. Nam luctus eleifend massa sed rhoncus. 
 */
void test_myFunction_yyy(void) {
   ...
}
```

 the test blows up, with erroneous "duplicate symbol" errors:

```
duplicate symbol '_tearDown' in:
    ...
duplicate symbol '_setUp' in:
    ...
ld: 2 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: Shell command failed.
> Shell executed command:
'gcc "build_test/test/out/c/[...].o" "build_test/test/out/c/[...].o" "build_test/test/out/c/unity.o" "build_test/test/out/c/cmock.o" -o "build_test/test/out/[...].out" -lm -lm'
> And exited with status: [1].
```

Is this expected behavior with Ceedling?
Is there a way to prevent this from happening, short of keeping all comments within a certain, empirically determined limit?

Note: I'm experiencing this running on OSX, where the majority of my development team is NOT experiencing this, running under Linux. In case its relevant, the ruby version I am using is:
```
> ruby -v
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
```

**Comment by krispin-gradient** [comment]
Ho @mvandervoord - thanks for the ideas.

> is it possible you're doing a combination of /* */ style comments, // style comments, and/or #ifdef sections all in that area?

No, just one comment style, and no #ifdef sections.

Here's an example of a (gibberish) comment that passes:
```c
/**
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 */
```

... and an example of a comment that causes the same failure as described above:
```c
/**
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 */
```

> Where are your setup / teardown functions in relation to the comments in question?

The setup / teardown functions are at the top of the file, while this comment/function are near the bottom of the file; not proximal.

>Are you using gcc or another compiler?

I've been using this version of gcc:
```
> gcc -v
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
...but I also just tried switching to Homebrew's (GNU) gcc, and I get the same error.

>Do you rely on weak function definitions for setup / teardown?

Hmmm... I'm not sure; how would I check this (and should this be a factor, given the concrete comment examples above)?

Thanks again.

**Comment by krispin-gradient** [comment]
The issue seems to relate to the number of lines in a comment, rather than the length in characters.

For example, using this comment does _not_ result in the test blowing up:
```c
/**
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 * AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA AAAA A A A A AA A A A A A A A AA A A A A A A A AA AAAAAAAA A A AA AAAAAAAAAAAA
 */
```
while this comment _does_ result in the test blowing up:
```c
/**
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 */
```

**Comment by mvandervoord** [comment]
I'm not sure if the `weak` symbol handling is relevant or not. 

Outside of the "bad parsing" theory, I'm at a bit of a loss as to what could be happening. From what you've answered above, it seems very unlikely that it's a result of bad parsing.... those comments are just too "normal" and the setup/teardown functions don't seem like they'd be the only issue.

In your `build` folder, there are files that might be able to give us clues?

If you have the preprocessor enabled, then there will be a preprocessed version of this header. It'd be interesting to open that and see if it contains all the things you'd expect (the function definitions for your tests, as well as setup and teardown).

If you open the runner associated with this particular test, does it include its own setup and teardown function?

Sorry about sending you all over the place. I don't have a clearly defined theory at the moment and I'm casting a wide net in hopes we find clues. :/

**Comment by krispin-gradient** [comment]
I just looked in `build_test/test/preprocess/files/`, and:
* When the long (problematic) comment is used, the file in question holds only _one_ function: the function after the comment. (That function happens to be the last in the file).
* When the short comment is used, the file in question holds _all_ of the functions of the original file.

Does this suggest anything? Should I be looking elsewhere in `build_test`?

I've got the line `use_test_preprocessor: TRUE` in `project.yml`.  (When I try to set it to `FALSE`, _other_ things break that prevent me from easily testing what that change might do...)

**Comment by mvandervoord** [comment]
Interesting. 

So there is something about your test preprocessor that is causing it to chop out much of your output when the comment gets too long. If you're running with defaults, it's just using clang for this also... which I wouldn't expect to have any issues with this sort of thing (clang is used to handling very long files, etc... a comment block shouldn't confuse it). 

I assume you're using the last release, not the current release candidate, correct? I ask only because the preprocessing handling changes a lot in the new release.

**Comment by krispin-gradient** [comment]
> I assume you're using the last release, not the current release candidate, correct? I ask only because the preprocessing handling changes a lot in the new release.

It looks [here](https://releases.llvm.org/download.html) like the latest release is 18.1.8; I'm using 15.0.0 - so not "living on the edge" with an untested release candidate...

>If you're running with defaults, it's just using clang for this also... 

How would I check? Are there particular settings to look out for that might be over-riding some aspect of this?

Appreciate any recommendations re: how to go about debugging this sort of thing.

**Comment by mvandervoord** [comment]
> It looks [here](https://releases.llvm.org/download.html) like the latest release is 18.1.8; I'm using 15.0.0 - so not "living on the edge" with an untested release candidate...

Whoops. I wasn't very clear there. I was referring to the Ceedling version. If you do a `ceedling --version` I suspect it's `0.31.1`?

> How would I check? Are there particular settings to look out for that might be over-riding some aspect of this?

In your ceedling `project.yml` file, have you defined you own tools, particularly `test_preprocessor` ? Given your statements above, I strongly suspect you have not (which is a good thing in this case. The stock clang SHOULD be fine here)

**Comment by krispin-gradient** [comment]
> If you do a ceedling --version I suspect it's 0.31.1?

Strangely, `ceedling --version` causes the tests to run - but when they do, from error output, I see:
```
...gems/ceedling-0.31.1/lib/ceedling...
```
...so I'm guessing the version is 0.31.1.

> In your ceedling `project.yml` file, have you defined you own tools, particularly `test_preprocessor` ?
I don't _think_ so (but am still very much learning how this system works...)

From `project.yml`, here are the lines that seem possibly relevant:

```
:project:
  ...
  :use_test_preprocessor: TRUE
  :use_preprocessor_directives: TRUE
  ...
```
and:
```
...
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use
:tools:
  :test_file_preprocessor:
    :executable: gcc
    :name: default_test_file_preprocessor
    :stderr_redirect: :none
    :background_exec: :none
    :optional: false
    :arguments:
    - ''
    - ''
    - "-E"
    - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
    - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
    - "-D$": COLLECTION_DEFINES_TEST_AND_VENDOR
    - "-D$": DEFINES_TEST_PREPROCESS
    - "-DGNU_COMPILER"
    - "-include FreeRTOS.h"
    - '"${1}"'
    - -o "${2}"
  :test_file_preprocessor_directives:
    :executable: gcc
    :name: default_test_file_preprocessor_directives
    :stderr_redirect: :none
    :background_exec: :none
    :optional: false
    :arguments:
    - "-E"
    - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
    - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
    - "-D$": COLLECTION_DEFINES_TEST_AND_VENDOR
    - "-D$": DEFINES_TEST_PREPROCESS
    - "-DGNU_COMPILER"
    - "-include FreeRTOS.h"
    - "-fdirectives-only"
    - '"${1}"'
    - -o "${2}"
  :test_includes_preprocessor:
    :executable: gcc
    :name: default_test_includes_preprocessor
    :stderr_redirect: :none
    :background_exec: :none
    :optional: false
    :arguments:
    - ''
    - ''
    - "-E"
    - "-MM"
    - "-MG"
    - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
    - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
    - "-D$": COLLECTION_DEFINES_TEST_AND_VENDOR
    - "-D$": DEFINES_TEST_PREPROCESS
    - "-DGNU_COMPILER"
    - "-include FreeRTOS.h"
    - '"${1}"'
  :test_dependencies_generator:
    :executable: gcc
    :name: default_test_dependencies_generator
    :stderr_redirect: :none
    :background_exec: :none
    :optional: false
    :arguments:
    - ''
    - ''
    - "-E"
    - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
    - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
    - "-D$": COLLECTION_DEFINES_TEST_AND_VENDOR
    - "-D$": DEFINES_TEST_PREPROCESS
    - "-DGNU_COMPILER"
    - "-include FreeRTOS.h"
    - -MT "${3}"
    - "-MM"
    - "-MD"
    - "-MG"
    - -MF "${2}"
    - -c "${1}"
    ...
```

Does this suggest any solutions?
In case its relevant: gcc on the Macbook corresponds to clang.

Thanks again,
-K

**Comment by mkarlesky** [comment]
Hi, @krispin-gradient. Could you try your build with `:use_preprocessor_directives` disabled? It's very possible you need this feature in your test setup. If not, it _might_ be causing the shenanigans. It's not a particularly resilient feature in 0.31.1.

I ran some tests with Ceedling 1.0.0 prerelease. It handles your reported scenario just fine to the extent I am able to adequately replicate your specific scenario. Unfortunately, we don't have the resources to actively support two versions of Ceedling simultaneously. 1.0.0 is basically ready for release, save for finishing some stress testing and final packaging. It includes a long list of bug fixes, improvements, and new features users have asked for. In particular, its preprocessing abilities are greatly improved (though we did have to pull one advanced feature to be restored in a future release). With its impending official release I don't think we can spend the necessary time to troubleshoot and bug fix 0.31.1. Your issue definitely seems like a needed bug fix.

**Comment by krispin-gradient** [comment]
Hi @mkarlesky,

>Could you try your build with :use_preprocessor_directives disabled?

This seems to do the trick. I don't know that my organization can comment out this flag for *all* the tests we need to run, but I was able to at least verify that the tests that were failing in relation to long comments (when run on OSX) no longer fail when this flag is disabled.

Appreciate the recommendation, and look forward to Ceedling 1.0.0!

**Comment by mkarlesky** [comment]
The flag in question in 0.31.1 is an enhancement to Ceedling's preprocessing that tries to preserve certain macros (Unity's advanced test case range features) that would otherwise get preprocessed (by the compiler not Ceedling) in unhelpful ways. If you don't use Unity's test case range and related features, you can skip entirely this configuration flag.

In 1.0.0+ this behavior will not require a special flag but will just work (not there quite yet).
