### ISSUE TITLE
Print absolute path to configuration file

### ISSUE THREAD

**Issue by swaldhoer** [ThrowTheSwitch/Ceedling#918]
When ceedling `1.0.0-xxx` is run, it prints the path of the project configuration file (which I think is good), but it prints it **relative** to the cwd, which leads to something like that:

```text
Loaded project configuration at default location using ./project.yml
```

I think it would be beneficial if ceedling would print the **absolute** path of the project configuration file, because depending on the tool ceedling might be integrated, the cwd is not obvious and it makes debugging project configurations with relative paths in it harder.

- Nice to have: If ceedling would additionally print out it's cwd there would be no uncertainties about the command that is run.
- Even nicer to have: Normalize the path accordingly to the platform, i.e., use `/` or `\`.

**Comment by mkarlesky** [comment]
@swaldhoer Good request. This is complete—except for the final bullet—but not yet available in a pre-release build (soon).

Native path separators is complicated in a multi-platform tool. The Ruby language standardizes on forward slashes internally. I believe `gcc` requires forward slashes (or perhaps simply tolerates back slashes on Windows). I believe the C language requires forward slashes, at least in `#include` directives.  Windows itself accepts forward slashes in many but not all places. Ceedling has taken the approach of converting any input slashes to forward slashes, relies on Ruby's defaults, and logs as forward slashes. Perhaps we could support a display option for native separators in logging output. That's a non-trivial change. If we added it here now, it'd be the only place platform-specific slashes are visible. So… I think it best to punt on this one for now.

**Comment by swaldhoer** [comment]
Works as expexted! Thanks for the quick update :)

Regarding path normalization: okay make sense, didn't know that Ruby is not that agnostic (compared to e.g., Python). But anyway that part is not that imporant.
