### ISSUE TITLE
Where is unity.h?

### ISSUE THREAD

**Issue by rickymohk** [ThrowTheSwitch/Ceedling#923]
My project build and test without issue. But VS Code complain about `cannot open source file "unity.h"` What should I add to my include path so that VS Code can find it and give me IntelliSense for unity.h?

**Comment by mkarlesky** [comment]
Hi, @rickymohk. Which version of Ceedling are you using—0.31.1 or 1.0.0-prerelease? We can guide you specifically knowing that.

The former tucks unity.h away in Ceedling's installation directory. The latter copies it into your build directory. If you increase verbosity in your build you can see unity.c's source path in the compilation. unity.h is in the same path.

**Comment by rickymohk** [comment]
I am using 0.31.1

**Comment by mkarlesky** [comment]
First run `ceedling clobber`. Then `ceedling verbosity[4] test:<one of your tests>`. In the compilation output, look for `unity.c` being compiled. The path to `unity.c` is the same as to `unity.h`.

**Comment by rickymohk** [comment]
Got it. Thank you.
