### ISSUE TITLE
Including html_tests_report as Ceedling Ruby Gem

### ISSUE THREAD

**Issue by jyc-biz** [ThrowTheSwitch/Ceedling#935]
Hello,

The Ceedling package installed via Ruby (i.e., "gem install ceedling"; version 0.31.1) does not have html_tests_report in the plugins subfolder. Invoking any kind of ceedling command would generate an error saying that there is no rake or ruby class entry point for the plugin.

To resolve this, I had to clone the repo and copy the html_tests_report subfolder into plugins. At that point ceedling can run without issues.

Thanks for your time!

**Comment by mkarlesky** [comment]
Hello, @jyc-biz. Thank you for the report and so sorry for your trouble.

I see the trouble. The `html_tests_report` was added to the project via Pull Request roughly a year ago. We did not publish an updated 0.3x.x gem containing this plugin as we were deep into work on the giant 1.0.0 release that is now soon to be published. Support for 0.3x.x will soon be going away with all attention given to 1.0.0. Incidentally, the new 1.0.0 version of Ceedling does include this plugin, but it has been combined with other reporting functionality. Please see the [plugin renaming in _BreakingChanges_](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/BreakingChanges.md#built-in-plugin-name-changes).
