### ISSUE TITLE
Compiler error messages mixed with Ceedling text

### ISSUE THREAD

**Issue by radoslav06** [ThrowTheSwitch/Ceedling#937]
It is very inconvenient that when compiler messages are forwarded to the stdout, the first line is prepended with ceedling text (and the last line is appended with quote character). It makes harder to parse compiler messages inside an IDE (or outside the IDE as well).  

Example: first error is missed by the IDE, the second error is catch correctly:  
![image](https://github.com/user-attachments/assets/60bc89dc-fc6b-4b40-aca6-cbe5db0e8654)

Additionally, sometimes, the messages are displayed by the IDE with the `"` at the end that comes from Ceedling.

Proposed solution:  
1. Insert new line after `EXCEPTION: ShellExecutionException ==> '<compiler_name>' (<compiler_exe>) terminated with exit code [<code>] and output >> `  
2. Remove quotation characters `"` for the compiler messages or put them also in the separate lines.

I am using ceedling 1.0.0-a1e6b24 if that matters.

**Comment by mkarlesky** [comment]
Hi, @radoslav06. You're right. That's not a helpful log formatting, is it? It's fixed in the latest 1.0.0 prerelease. Apart from any last minute fixes, this is probably the very last change added to 1.0.0 before pushing it out as a proper release.
