### ISSUE TITLE
clang support  problem

### ISSUE THREAD

**Issue by jinxinyang** [ThrowTheSwitch/Ceedling#945]
I want to use your ceedling to carry out the unit test of the driver module of our embedded project, but we use keil's clang for compilation, and the routines here all use gcc. May I ask whether clang is supported now?
Here are our compile parameters

-xc -std=c99 --target=arm-arm-none-eabi -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -c
-fno-rtti -Werror -funsigned-char -fshort-enums -fshort-wchar

![image](https://github.com/user-attachments/assets/a448974b-90d8-4a2e-906c-97162e52806a)
May I ask how to write this configuration

**Comment by mvandervoord** [comment]
Yes, clang is fully supported (and always has been. We actually supported clang before gcc).

All tools can be customized in the project.yml file. You'll want to specify your arguments for the specific tool call, etc. You can see examples of the [`Ceedling tool definitions`](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md#ceedling-tool-definitions) section of the [CeedlingPacket.md ](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md#ceedling-tool-definitions) documentation.
