### ISSUE TITLE
Headerless C file specified as source, but not being included in a test

### ISSUE THREAD

**Issue by krispin-gradient** [ThrowTheSwitch/Ceedling#951]
I'm trying to create a set of tests for a UI widget that has, as a dependency, an auto-generated font which is a .c file _with no corresponding .h file_. (In the UI framework I'm using, the auto generated headerless font source is made available to other source files using `extern`, e.g. ```extern const lv_font_t font_switzer_35_semibold;```.

I've set up a yml file for the tests so that the .c font file (`font_switzer_30_regular.c`) is explicitly listed as one of the source files, e.g:

```
---
:paths:
  :test:
    - +:ui/src/widgets/scale/test/**
  :source:
      - ui/src/widgets/scale/ui_scale.c
      - ui/fonts/font_switzer_30_regular.c  <-- font file specified.
      ...
  :support:
    - test/esp_log
  :include:
    - ui/src/widgets/scale/include
    ...
...
```

...however when I run the test via `ceedling test:ui_scale`, I get "undefined symbol" errors corresponding to the content of the font .c file, and when I examine the command that the shell executed to build/run the test, its clear that no object file is being created for the font, i.e. no `font_switzer_30_regular.o`.

Is there a way, in ceedling, to specify that `font_switzer_30_regular.c` must be built, even though there is no corresponding header for this file included from the test source code?

**Comment by krispin-gradient** [comment]
>First, when specifying files instead of paths, you want to switch to the :files section instead of the :paths section:

Thanks @mvandervoord!

>If you want a file to get used in a test, you can include it in your test_ui_scale.c file using #include directly or (more tidily) using TEST_SOURCE_FILE("font_switzer_30_regular.c"). This latter option assumes you're using the pre-release of 1.0 which is soon to be released.

My team is still on ceedling-0.31.1... If I use the _first_ option - `#include`ing the font .c file directly - I run into a wrinkle I neglected to describe earlier, which is that (because of the way font .c files are auto-generated), each font file has some internal structure that is identical to the internal structure of other font files.

More specifically, the UI widget under test actually has _three_ fonts, and if I include the three corresponding .c files, e.g.

```c
#include "font_switzer_30_medium.c"
#include "font_switzer_30_medium.c"
#include "font_switzer_30_semibold.c"

```
... I run into lots of `error: redefinition of 'glyph_bitmap'` errors (where `glyph_bitmap` is one of the internal parts of an autogenerated font file...).

Does this wrinkle essentially mean I will need to create  "wrapper" .h/.c files for each font, including the actual .c font files from the .c wrapper file, and then include the wrapper .h files from my test file (so Ceedling will find and compile the actual .c font files)?

Is there any cleaner way to handle this, that you can think of?

Thanks again.

**Comment by krispin-gradient** [comment]
By "wrapper", I mean something like the following:

support_font_switzer_20_semibold.h
```c
#include "font_types.h"

#ifndef __SUPPORT_FONT_SWITZER_20_SEMIBOLD__
#define __SUPPORT_FONT_SWITZER_20_SEMIBOLD__

extern const lv_font_t font_switzer_20_semibold;

#endif  // __SUPPORT_FONT_SWITZER_20_SEMIBOLD__
```

support_font_switzer_20_semibold.c
```c
#include "support_font_switzer_20_semibold.h"

#include "../../../../fonts/font_switzer_20_semibold.c"
```

**Comment by mvandervoord** [comment]
Hm. Good question. 

Perhaps the simplest solution might be to create a header file for each of your font files which publishes the public interface for it... then you can do this the traditional way just including the headers? Those header files could even exist solely in your test support directory, and I believe it'd work?

Otherwise, I think you're right... you'd have to create some kind of wrapper and/or conditional compilation for these files.

**Comment by krispin-gradient** [comment]
Good to know.
Thanks again!
