### ISSUE TITLE
Allow to use a custom `project.yml` config file from CLI on test

### ISSUE THREAD

**Issue by saugat76** [ThrowTheSwitch/Ceedling#961]
### Feature Request: Allow Custom `project.yml` Config File from CLI for Tests

**Description:**
Request a feature that allows users to specify a custom `project.yml` configuration file from the command line interface (CLI) when creating a new tests project with Ceedling. This would enable users to pass a configuration file as an argument every time they call `ceedling new name`.

**Proposed Solution:**
Add an option to the CLI that accepts a custom `project.yml` file path. For example:
```
ceedling new name --config_file=/path/to/custom_project.yml
```

**Benefits:**
- Increased flexibility in managing multiple configurations.
- Simplifies the process of switching between different project setups.
- Enhances usability for projects with varying test requirements.

Thank you for considering this feature request.

**Comment by mvandervoord** [comment]
This is already a feature. In 0.31 or earlier, look at the config and user options. In the 1.0 pre-release branch, look for the documentation on mixins. :)
