### ISSUE TITLE
Parametrized tests with ceedling 1.0.0-*

### ISSUE THREAD

**Issue by radoslav06** [ThrowTheSwitch/Ceedling#973]
Hi,
I am using the following ceedling:
```
Ceedling => 1.0.0-a1e6b24
     CMock => 2.5.4
     Unity => 2.6.0
     CException => 1.3.4
```
What options are needed to enable parametrized tests in this version?
I have checked #241 but with no success on my version/setup. I checked also the ceedling docs, but also with no success.

**Comment by mkarlesky** [comment]
Hi, @radoslav06. When you say parameterized tests, are you referring to using Unity’s `TEST_CASE()` and `TEST_MATRIX()`?

```
:unity:
  :use_param_tests: TRUE
```

Which documentation were you looking at? This is documented in [Ceedling Packet here](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md#unity-configure-unitys-features).

**Comment by radoslav06** [comment]
Exactly, I am referring to `TEST_CASE()` and other macros.
I already figure out that the problem is caused by `:use_test_preprocessor: all`, but I am not sure how to fix it. Is there any workaround?

**Comment by mkarlesky** [comment]
Ah. Yes. Presently, these two features are simply incompatible. I see our warnings on this are throughout the documentation but not necessarily everywhere it needs to be. I will revise the docs further. I am also adding a warning if the incompatible settings are found in the project configuration.

Unity's parameterized tests rely on macros that are _positional_. They must come just before a test case function. Unfortunately, with preprocessing enabled, there's no reliable way to preserve those positions in a preprocessed test file. The best we can do is get it right sometimes and fail mysteriously other times. We hope to revamp parameterized test in future releases to fix this incompatibility.

The one workaround that is now possible in 1.0.0 — but it may not work for your case — is enabling preprocessing just for mocking and not your test files. See the much improved documentation [on preprocessing in Ceedling Packet](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/CeedlingPacket.md#ceedling-preprocessing-behavior-for-your-tests). It explains in detail when preprocessing is appropriate. If you do not need preprocessing for your test files, you can simply turn it off and go happily on using parameterized tests.

```
:project:
   :use_test_preprocessor: :mocks
```

**Comment by radoslav06** [comment]
Thanks for the detailed explanation and confirmation, and for the quick response; indeed, we do rely on preprocessing both mock and test files. I can probably find a workaround for the latter, so I'll try using `:use_test_preprocessor: mocks'.

**Comment by radoslav06** [comment]
Maybe I closed the issue too fast as you mention that you plan some follow up activities. For me it's done, but I reopen if you want to use it as a remainder for your activities, feel free to close whenever you want.

**Comment by mkarlesky** [comment]
Thank you for your thoughtfulness, @radoslav06. The documentation changes and the warning logging I mentioned are already done (just not pushed or built into a new prerelease). The revamp of parameterized tests to solve this problem is off in the distance but very much on the radar.

Happy New Year!
